# Generated by Django 5.2.17 on 2026-10-04 21:45

import django.contrib.postgres.constraints
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
import kpigo.platform.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("platform", "0003_extensions")]

    operations = [
        migrations.CreateModel(
            name="MetricFamily",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "family_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("display_name", models.TextField()),
                ("normalised_name", models.TextField()),
                ("description", models.TextField(db_default="")),
                ("owner_user_id", models.BigIntegerField(null=True)),
            ],
            options={
                "db_table": "metric_family",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["normalised_name"],
                        name="metric_family_name_trgm",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "normalised_name"),
                        name="metric_family_name_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "metric_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("metric_code", models.TextField()),
                ("display_name", models.TextField()),
                ("direction", models.TextField()),
                ("aggregation", models.TextField()),
                ("unit", models.TextField()),
                ("decimal_places", models.SmallIntegerField(db_default=0)),
                ("is_percentage", models.BooleanField(db_default=False)),
                ("target_scope", models.TextField(db_default="profile")),
                ("collection_method", models.TextField(db_default="feed")),
                ("status", models.TextField(db_default="draft")),
                ("computation_note", models.TextField(db_default="")),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
                (
                    "supersedes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="metrics.metric",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metrics",
                        to="metrics.metricfamily",
                    ),
                ),
            ],
            options={
                "db_table": "metric",
            },
        ),
        migrations.CreateModel(
            name="MetricProfileAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "metric_id",
                        "profile_code",
                        "product",
                        "effective_from",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_code", models.TextField()),
                ("product", models.TextField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "metric_profile_assignment",
            },
        ),
        migrations.CreateModel(
            name="MetricBinding",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "metric_id",
                        "product",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product", models.TextField()),
                ("is_active", models.BooleanField(db_default=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "metric_binding",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="metric_binding_product_valid",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(fields=["org_id", "metric_code"], name="metric_code_lookup"),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["higher_is_better", "lower_is_better"])),
                name="metric_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aggregation__in", ["sum", "average", "latest", "count", "ratio"])
                ),
                name="metric_aggregation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit__in",
                        ["currency", "count", "percent", "days", "hours", "score"],
                    )
                ),
                name="metric_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_scope__in", ["profile", "subject"])),
                name="metric_target_scope_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(("collection_method__in", ["feed", "manual_input"])),
                name="metric_collection_method_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "active", "inactive", "deprecated"])),
                name="metric_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(("decimal_places__gte", 0), ("decimal_places__lte", 6)),
                name="metric_decimal_places_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(("metric_code__regex", "^[a-z][a-z0-9_]*$")),
                name="metric_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="metric_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("org_id", "="),
                    ("metric_code", "="),
                    (
                        kpigo.platform.db.DateRange("effective_from", "effective_to"),
                        "&&",
                    ),
                ],
                name="metric_code_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricprofileassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "product__in",
                        [
                            "scorecards",
                            "agent_sales",
                            "agent_service",
                            "executive",
                            "campaign",
                        ],
                    )
                ),
                name="metric_profile_product_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricprofileassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="metric_profile_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricprofileassignment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("metric", "="),
                    ("profile_code", "="),
                    ("product", "="),
                    (
                        kpigo.platform.db.DateRange("effective_from", "effective_to"),
                        "&&",
                    ),
                ],
                name="metric_profile_no_overlap",
            ),
        ),
    ]
