# Generated by Django 5.2.17 on 2026-10-05 00:25

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metrics", "0001_initial"),
        ("periods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingBand",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "band_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField()),
                ("label", models.TextField()),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=8)),
                ("ramp_position", models.SmallIntegerField()),
                ("colour_hex", models.TextField(null=True)),
                ("sort_order", models.IntegerField(db_default=0)),
            ],
            options={
                "db_table": "rating_band",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="rating_band_product_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("org_id", "product", "label"),
                        name="rating_band_label_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("org_id", "product", "threshold"),
                        name="rating_band_threshold_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ramp_position__gte", 1), ("ramp_position__lte", 7)),
                        name="rating_band_ramp_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("colour_hex__isnull", True),
                            ("colour_hex__regex", "^#[0-9A-Fa-f]{6}$"),
                            _connector="OR",
                        ),
                        name="rating_band_colour_hex",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScorecardSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "weight_total",
                    models.DecimalField(db_default=100, decimal_places=3, max_digits=8),
                ),
                (
                    "weight_tolerance",
                    models.DecimalField(db_default=0.5, decimal_places=3, max_digits=8),
                ),
                (
                    "cap_min_ratio",
                    models.DecimalField(db_default=1, decimal_places=3, max_digits=6),
                ),
                (
                    "cap_max_ratio",
                    models.DecimalField(db_default=3, decimal_places=3, max_digits=6),
                ),
                ("denominator_policy", models.TextField(db_default="reduced")),
            ],
            options={
                "db_table": "scorecard_settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("denominator_policy__in", ["reduced", "redistribute"])),
                        name="scorecard_settings_policy_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weight_tolerance__gte", 0), ("weight_total__gt", 0)),
                        name="scorecard_settings_weights_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cap_min_ratio__gt", 0),
                            ("cap_max_ratio__gte", models.F("cap_min_ratio")),
                        ),
                        name="scorecard_settings_cap_ratios_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScorecardTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "template_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("name", models.TextField()),
                ("level_count", models.SmallIntegerField()),
                ("status", models.TextField(db_default="draft")),
            ],
            options={
                "db_table": "scorecard_template",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "name"), name="scorecard_template_name"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("org_id",),
                        name="scorecard_template_one_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("level_count__gte", 1), ("level_count__lte", 3)),
                        name="scorecard_template_levels_1_to_3",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["draft", "active", "inactive"])),
                        name="scorecard_template_status_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScorecardNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "node_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level_no", models.SmallIntegerField()),
                ("label", models.TextField()),
                ("sort_order", models.IntegerField(db_default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="scorecards.scorecardnode",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="scorecards.scorecardtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "scorecard_node",
            },
        ),
        migrations.CreateModel(
            name="ScorecardLevel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "template_id",
                        "level_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level_no", models.SmallIntegerField()),
                ("label", models.TextField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="levels",
                        to="scorecards.scorecardtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "scorecard_level",
            },
        ),
        migrations.CreateModel(
            name="TargetPublishBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                (
                    "period_keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=6), size=None
                    ),
                ),
                ("published_at", models.DateTimeField()),
                ("published_by", models.BigIntegerField(null=True)),
                (
                    "weight_check_result",
                    models.JSONField(db_default=models.Value({}, models.JSONField())),
                ),
                ("row_count", models.IntegerField()),
                ("note", models.TextField(db_default="")),
                ("status", models.TextField(db_default="published")),
                ("reverted_at", models.DateTimeField(null=True)),
                ("reverted_by", models.BigIntegerField(null=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="periods.performancecycle",
                    ),
                ),
            ],
            options={
                "db_table": "target_publish_batch",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "target_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("scope_type", models.TextField()),
                ("scope_code", models.TextField()),
                ("period_key", models.CharField(max_length=6)),
                ("series_type", models.TextField(db_default="target")),
                ("target_value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("target_type", models.TextField(db_default="monthly")),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, max_digits=6, null=True),
                ),
                ("cap", models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ("currency_code", models.CharField(max_length=3, null=True)),
                ("version", models.IntegerField()),
                ("state", models.TextField(db_default="draft")),
                ("source", models.TextField(db_default="workbench")),
                ("published_at", models.DateTimeField(null=True)),
                ("published_by", models.BigIntegerField(null=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targets",
                        to="scorecards.targetpublishbatch",
                    ),
                ),
            ],
            options={
                "db_table": "target",
            },
        ),
        migrations.CreateModel(
            name="ScorecardPlacement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "placement_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_code", models.TextField()),
                ("profile_code", models.TextField(null=True)),
                ("sort_order", models.IntegerField(db_default=0)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="scorecards.scorecardnode",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="scorecards.scorecardtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "scorecard_assignment",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "metric_code", "profile_code"),
                        name="scorecard_assignment_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scorecardnode",
            constraint=models.CheckConstraint(
                condition=models.Q(("level_no__gte", 1), ("level_no__lte", 3)),
                name="scorecard_node_level_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecardnode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("level_no", 1), ("parent__isnull", True)),
                    models.Q(("level_no__gt", 1), ("parent__isnull", False)),
                    _connector="OR",
                ),
                name="scorecard_node_parent_by_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecardnode",
            constraint=models.UniqueConstraint(
                fields=("template", "parent", "label"),
                name="scorecard_node_label_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecardlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("level_no__gte", 1), ("level_no__lte", 3)),
                name="scorecard_level_no_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetpublishbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["published", "reverted"])),
                name="target_publish_batch_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["org_id", "period_key", "state"], name="target_period_state"
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(fields=["scope_type", "scope_code"], name="target_scope"),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_type__in", ["profile", "subject"])),
                name="target_scope_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("series_type__in", ["target", "forecast", "budget"])),
                name="target_series_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_type__in",
                        ["monthly", "yearly", "cumulative", "quarterly", "prorated"],
                    )
                ),
                name="target_target_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "published", "superseded"])),
                name="target_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["upload", "copy_forward", "workbench"])),
                name="target_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                name="target_period_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=(
                    "metric",
                    "scope_type",
                    "scope_code",
                    "period_key",
                    "series_type",
                    "version",
                ),
                name="target_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "draft")),
                fields=(
                    "metric",
                    "scope_type",
                    "scope_code",
                    "period_key",
                    "series_type",
                ),
                name="target_one_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "published")),
                fields=(
                    "metric",
                    "scope_type",
                    "scope_code",
                    "period_key",
                    "series_type",
                ),
                name="target_one_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__isnull", True), ("weight__gte", 0), _connector="OR"),
                name="target_weight_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("cap__isnull", True), ("cap__gte", 0), _connector="OR"),
                name="target_cap_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "draft"), _negated=True),
                    ("batch__isnull", True),
                    _connector="OR",
                ),
                name="target_draft_unbatched",
            ),
        ),
    ]
