# Generated by Django 5.2.17 on 2026-10-05 00:58

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0001_initial"),
        ("scorecards", "0002_target_scope_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="Override",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "override_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("scope_type", models.TextField()),
                ("scope_code", models.TextField()),
                ("product", models.TextField(db_default="scorecards")),
                ("period_from", models.CharField(max_length=6)),
                ("period_to", models.CharField(max_length=6, null=True)),
                ("change_type", models.TextField()),
                (
                    "override_value",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                ("override_text", models.TextField(null=True)),
                ("reason", models.TextField()),
                ("status", models.TextField(db_default="pending")),
                ("requested_by", models.BigIntegerField(null=True)),
                ("approved_by", models.BigIntegerField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("decision_note", models.TextField(db_default="")),
                ("ended_by", models.BigIntegerField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "override",
                "indexes": [
                    models.Index(fields=["org_id", "product", "status"], name="override_status"),
                    models.Index(fields=["scope_type", "scope_code"], name="override_scope"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("scope_type__in", ["subject", "profile", "dimension"])),
                        name="override_scope_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "change_type__in",
                                ["target", "weight", "cap", "actual", "target_type"],
                            )
                        ),
                        name="override_change_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "pending",
                                    "approved",
                                    "rejected",
                                    "withdrawn",
                                    "revoked",
                                ],
                            )
                        ),
                        name="override_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="override_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_from__regex", "^[0-9]{4}(0[1-9]|1[0-2])$"),
                            models.Q(
                                ("period_to__isnull", True),
                                ("period_to__regex", "^[0-9]{4}(0[1-9]|1[0-2])$"),
                                _connector="OR",
                            ),
                        ),
                        name="override_period_key_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_to__isnull", True),
                            ("period_to__gte", models.F("period_from")),
                            _connector="OR",
                        ),
                        name="override_period_range_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="override_reason_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("change_type", "target_type"),
                                (
                                    "override_text__in",
                                    (
                                        "monthly",
                                        "yearly",
                                        "cumulative",
                                        "quarterly",
                                        "prorated",
                                    ),
                                ),
                            ),
                            models.Q(
                                models.Q(("change_type", "target_type"), _negated=True),
                                ("override_value__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="override_value_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "approved"), _negated=True),
                            models.Q(
                                ("approved_at__isnull", False),
                                ("approved_by__isnull", False),
                                models.Q(
                                    ("approved_by", models.F("requested_by")),
                                    _negated=True,
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="override_approved_by_other",
                    ),
                ],
            },
        ),
    ]
