# Generated by Django 5.2.17 on 2026-10-05 01:13

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0002_product_lines_available_members"),
        ("metrics", "0001_initial"),
        ("scorecards", "0003_overrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreSnapshot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "snapshot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField(db_default="scorecards")),
                ("period_key", models.CharField(max_length=6)),
                ("snapshot_version", models.IntegerField()),
                ("kind", models.TextField()),
                ("reason", models.TextField(db_default="")),
                ("subjects", models.IntegerField()),
            ],
            options={
                "db_table": "score_snapshot",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="score_snapshot_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["close", "restatement"])),
                        name="score_snapshot_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="score_snapshot_period_key_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("org_id", "product", "period_key", "snapshot_version"),
                        name="score_snapshot_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "close"), ("snapshot_version", 1)),
                            models.Q(("kind", "restatement"), ("snapshot_version__gt", 1)),
                            _connector="OR",
                        ),
                        name="score_snapshot_kind_matches_version",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreExclusion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "exclusion_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField(db_default="scorecards")),
                ("period_key", models.CharField(max_length=6)),
                ("reason", models.TextField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.subject",
                    ),
                ),
            ],
            options={
                "db_table": "score_exclusion",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="score_exclusion_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="score_exclusion_period_key_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="score_exclusion_reason_required",
                    ),
                    models.UniqueConstraint(
                        fields=("org_id", "product", "period_key", "metric", "subject"),
                        name="score_exclusion_unique",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreHistory",
            fields=[
                (
                    "score_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField(db_default="scorecards")),
                ("period_key", models.CharField(max_length=6)),
                ("sort_order", models.SmallIntegerField()),
                ("state", models.TextField()),
                ("target_version", models.IntegerField(null=True)),
                ("target_scope", models.TextField(null=True)),
                (
                    "base_target",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                ("target_type", models.TextField(null=True)),
                ("target_currency", models.CharField(max_length=3, null=True)),
                (
                    "target_value",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "reported_actual",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                ("actual_currency", models.CharField(max_length=3, null=True)),
                (
                    "fx_rate_applied",
                    models.DecimalField(decimal_places=10, max_digits=24, null=True),
                ),
                (
                    "actual_value",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "run_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "cap",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "pct_achieved",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "override_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                ("overrides", models.JSONField(default=list)),
                ("exclusion_reason", models.TextField(null=True)),
                ("computed_at", models.DateTimeField()),
                ("snapshot_version", models.IntegerField()),
                ("is_current", models.BooleanField(db_default=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.assignment",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.subject",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="scorecards.target",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="scorecards.scoresnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "score_history",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_current", True)),
                        fields=["subject", "product", "period_key"],
                        name="score_history_current",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "scored",
                                    "zero_actual",
                                    "not_reported",
                                    "no_target",
                                    "no_fx_rate",
                                    "excluded",
                                ],
                            )
                        ),
                        name="score_history_state_valid",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "subject",
                            "metric",
                            "product",
                            "period_key",
                            "snapshot_version",
                        ),
                        name="score_history_version_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreTotal",
            fields=[
                (
                    "score_total_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField(db_default="scorecards")),
                ("period_key", models.CharField(max_length=6)),
                ("profile_code", models.TextField()),
                ("policy", models.TextField()),
                ("months_elapsed", models.SmallIntegerField()),
                ("quarters_elapsed", models.SmallIntegerField()),
                ("cycle_months", models.SmallIntegerField()),
                ("total_score", models.DecimalField(decimal_places=6, max_digits=18)),
                ("total_cap", models.DecimalField(decimal_places=6, max_digits=18)),
                ("weight_scored", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "weight_expected",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "graded_score",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "achievement_pct",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                ("metrics_scored", models.SmallIntegerField()),
                ("metrics_total", models.SmallIntegerField()),
                ("not_reported", models.SmallIntegerField()),
                ("no_target", models.SmallIntegerField()),
                ("excluded", models.SmallIntegerField()),
                ("band_id", models.UUIDField(null=True)),
                ("band_label", models.TextField(null=True)),
                (
                    "band_threshold",
                    models.DecimalField(decimal_places=4, max_digits=8, null=True),
                ),
                ("band_ramp_position", models.SmallIntegerField(null=True)),
                ("band_colour_hex", models.TextField(null=True)),
                ("snapshot_version", models.IntegerField()),
                ("is_current", models.BooleanField(db_default=True)),
                ("computed_at", models.DateTimeField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.assignment",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="totals",
                        to="scorecards.scoresnapshot",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.subject",
                    ),
                ),
            ],
            options={
                "db_table": "score_total",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_current", True)),
                        fields=["org_id", "product", "period_key"],
                        name="score_total_current",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject", "product", "period_key", "snapshot_version"),
                        name="score_total_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("subject", "product", "period_key"),
                        name="score_total_one_current",
                    ),
                ],
            },
        ),
    ]
