# Generated by Django 5.2.17 on 2026-10-05 01:33

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0002_product_lines_available_members"),
        ("metrics", "0001_initial"),
        ("scorecards", "0005_snapshots_immutable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScorecardInteraction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "interaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("period_key", models.CharField(max_length=6)),
                ("product", models.TextField(db_default="scorecards")),
                ("interaction_type", models.TextField()),
                ("body", models.TextField(db_default="")),
                ("author_user_id", models.BigIntegerField(null=True)),
                ("visibility", models.TextField(db_default="subject")),
                ("snapshot_version", models.IntegerField(null=True)),
                ("resolved_at", models.DateTimeField(null=True)),
                ("resolved_by", models.BigIntegerField(null=True)),
                ("outcome", models.TextField(null=True)),
                ("resolution", models.TextField(null=True)),
                (
                    "metric",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
                (
                    "resulting_override",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="scorecards.override",
                    ),
                ),
                (
                    "routed_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.subject",
                    ),
                ),
            ],
            options={
                "db_table": "scorecard_interaction",
                "indexes": [
                    models.Index(
                        fields=["subject", "period_key"],
                        name="scorecard_interaction_subject",
                    ),
                    models.Index(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=["org_id", "interaction_type"],
                        name="scorecard_interaction_open",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "interaction_type__in",
                                ["acknowledgement", "query", "manager_comment"],
                            )
                        ),
                        name="scorecard_interaction_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("visibility__in", ["subject", "managers"])),
                        name="scorecard_interaction_visibility_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="scorecard_interaction_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="scorecard_interaction_period_key_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outcome__isnull", True),
                            ("outcome__in", ("explained", "adjusted")),
                            _connector="OR",
                        ),
                        name="scorecard_interaction_outcome_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("interaction_type", "query"), _negated=True),
                            ("metric__isnull", False),
                            _connector="OR",
                        ),
                        name="scorecard_interaction_query_has_metric",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resolved_at__isnull", True),
                            models.Q(
                                ("interaction_type", "query"),
                                ("outcome__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="scorecard_interaction_resolution_shape",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("interaction_type", "acknowledgement")),
                        fields=("subject", "product", "period_key", "snapshot_version"),
                        name="scorecard_interaction_one_ack_per_version",
                    ),
                ],
            },
        ),
    ]
