# Generated by Django 5.2.17 on 2026-10-05 01:57

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import kpigo.platform.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
        ("metrics", "0001_initial"),
        ("scorecards", "0006_interactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("metric_code", models.TextField()),
                ("scope_type", models.TextField()),
                ("scope_code", models.TextField()),
                ("assignee_type", models.TextField()),
                ("assignee_role", models.TextField(null=True)),
                (
                    "escalation_config",
                    models.JSONField(db_default=models.Value({}, output_field=models.JSONField())),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
                (
                    "assignee_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="access.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "input_assignment",
            },
        ),
        migrations.CreateModel(
            name="InputSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "schedule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("period_key", models.CharField(max_length=6)),
                ("due_at", models.DateTimeField()),
                ("last_reminder_step", models.SmallIntegerField(db_default=0)),
                ("last_reminded_at", models.DateTimeField(null=True)),
                (
                    "input_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="scorecards.inputassignment",
                    ),
                ),
                (
                    "reminded_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="access.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "input_schedule",
            },
        ),
        migrations.CreateModel(
            name="InputSubmission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "submission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("metric_code", models.TextField()),
                ("scope_type", models.TextField()),
                ("scope_code", models.TextField()),
                ("period_key", models.CharField(max_length=6)),
                (
                    "value",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                ("note", models.TextField(db_default="")),
                ("submitted_by", models.BigIntegerField(null=True)),
                ("submitted_at", models.DateTimeField(null=True)),
                ("state", models.TextField(db_default="draft")),
                ("approval_request_id", models.UUIDField(null=True)),
                ("version", models.IntegerField(db_default=1)),
                ("is_current", models.BooleanField(db_default=True)),
                (
                    "input_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="scorecards.inputassignment",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "input_submission",
            },
        ),
        migrations.AddField(
            model_name="scorecardsettings",
            name="input_due_working_day",
            field=models.SmallIntegerField(db_default=5),
        ),
        migrations.AddField(
            model_name="scorecardsettings",
            name="input_reminder_working_days",
            field=models.SmallIntegerField(db_default=2),
        ),
        migrations.AddConstraint(
            model_name="scorecardsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("input_due_working_day__gte", 1),
                    ("input_due_working_day__lte", 20),
                    ("input_reminder_working_days__gte", 0),
                    ("input_reminder_working_days__lte", 10),
                ),
                name="scorecard_settings_input_schedule_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_type__in", ["subject", "profile", "dimension"])),
                name="input_assignment_scope_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("assignee_type__in", ["user", "role_relative"])),
                name="input_assignment_assignee_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assignee_role__isnull", True),
                        ("assignee_type", "user"),
                        ("assignee_user__isnull", False),
                    ),
                    models.Q(
                        ("assignee_role__in", ("line_manager_of",)),
                        ("assignee_type", "role_relative"),
                        ("assignee_user__isnull", True),
                        ("scope_type", "subject"),
                    ),
                    _connector="OR",
                ),
                name="input_assignment_assignee_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="input_assignment_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputassignment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("org_id", "="),
                    ("metric_code", "="),
                    ("scope_type", "="),
                    ("scope_code", "="),
                    (
                        kpigo.platform.db.DateRange("effective_from", "effective_to"),
                        "&&",
                    ),
                ],
                name="input_assignment_no_overlap",
            ),
        ),
        migrations.AddIndex(
            model_name="inputschedule",
            index=models.Index(
                condition=models.Q(("last_reminder_step__lt", 3)),
                fields=["period_key", "due_at"],
                name="input_schedule_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                name="input_schedule_period_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputschedule",
            constraint=models.UniqueConstraint(
                fields=("input_assignment", "period_key"),
                name="input_schedule_one_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "submitted", "restated"])),
                name="input_submission_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_type__in", ["subject", "profile", "dimension"])),
                name="input_submission_scope_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                name="input_submission_period_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state", "draft"),
                    models.Q(("submitted_at__isnull", False), ("value__isnull", False)),
                    _connector="OR",
                ),
                name="input_submission_submitted_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputsubmission",
            constraint=models.UniqueConstraint(
                fields=(
                    "org_id",
                    "metric_code",
                    "scope_type",
                    "scope_code",
                    "period_key",
                    "version",
                ),
                name="input_submission_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=(
                    "org_id",
                    "metric_code",
                    "scope_type",
                    "scope_code",
                    "period_key",
                ),
                name="input_submission_one_current",
            ),
        ),
    ]
