# Generated by Django 5.2.17 on 2026-10-05 09:13

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
        ("scorecards", "0007_manual_input"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputEscalation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "escalation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("step", models.SmallIntegerField()),
                ("sent_at", models.DateTimeField()),
                ("emailed", models.BooleanField(null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="scorecards.inputschedule",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="access.appuser",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="access.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "input_escalation",
            },
        ),
        migrations.AddField(
            model_name="scorecardsettings",
            name="input_manager_working_days",
            field=models.SmallIntegerField(db_default=0, null=True),
        ),
        migrations.AddField(
            model_name="scorecardsettings",
            name="input_stakeholder_working_days",
            field=models.SmallIntegerField(db_default=1, null=True),
        ),
        migrations.AddField(
            model_name="scorecardsettings",
            name="input_stakeholders",
            field=models.JSONField(db_default=models.Value([], output_field=models.JSONField())),
        ),
        migrations.AddConstraint(
            model_name="scorecardsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("input_manager_working_days__isnull", True),
                        models.Q(
                            ("input_manager_working_days__gte", -10),
                            ("input_manager_working_days__lte", 10),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("input_stakeholder_working_days__isnull", True),
                        models.Q(
                            ("input_stakeholder_working_days__gte", -10),
                            ("input_stakeholder_working_days__lte", 10),
                        ),
                        _connector="OR",
                    ),
                ),
                name="scorecard_settings_input_ladder_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="inputescalation",
            index=models.Index(fields=["recipient", "sent_at"], name="input_escalation_to"),
        ),
        migrations.AddConstraint(
            model_name="inputescalation",
            constraint=models.CheckConstraint(
                condition=models.Q(("step__in", [1, 2, 3])),
                name="input_escalation_step_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputescalation",
            constraint=models.UniqueConstraint(
                fields=("schedule", "step", "recipient"), name="input_escalation_once"
            ),
        ),
    ]
