# Generated by Django 5.2.17 on 2026-10-05 12:13; the new keys are added before the
# narrower ones are dropped, so a target key is never unguarded.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0001_initial"),
        ("scorecards", "0008_escalation_ladder"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="product_line_code",
            field=models.TextField(db_default=""),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=(
                    "metric",
                    "scope_type",
                    "scope_code",
                    "period_key",
                    "series_type",
                    "product_line_code",
                    "version",
                ),
                name="target_line_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "draft")),
                fields=(
                    "metric",
                    "scope_type",
                    "scope_code",
                    "period_key",
                    "series_type",
                    "product_line_code",
                ),
                name="target_line_one_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "published")),
                fields=(
                    "metric",
                    "scope_type",
                    "scope_code",
                    "period_key",
                    "series_type",
                    "product_line_code",
                ),
                name="target_line_one_published",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="target",
            name="target_version_unique",
        ),
        migrations.RemoveConstraint(
            model_name="target",
            name="target_one_draft",
        ),
        migrations.RemoveConstraint(
            model_name="target",
            name="target_one_published",
        ),
    ]
