# Generated by Django 5.2.17 on 2026-10-04 23:13

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "licence_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("install_fingerprint", models.TextField()),
                ("licence_key", models.TextField()),
                ("customer", models.TextField(db_default="")),
                ("tier", models.TextField(db_default="")),
                ("seats", models.IntegerField()),
                ("modules", models.JSONField()),
                ("max_major_version", models.IntegerField()),
                ("instance_kind", models.TextField()),
                ("trial_major_until", models.DateTimeField(null=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("last_heartbeat_at", models.DateTimeField(null=True)),
                ("state", models.TextField(db_default="active")),
                ("key_id", models.TextField()),
                ("document", models.TextField()),
            ],
            options={
                "db_table": "licence",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("instance_kind__in", ["production", "non_production"])),
                        name="licence_instance_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["active", "superseded"])),
                        name="licence_state_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state", "active")),
                        fields=("org_id",),
                        name="licence_one_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                        name="licence_expires_after_issue",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_major_version__gte", 0), ("seats__gte", 0)),
                        name="licence_counts_positive",
                    ),
                ],
            },
        ),
    ]
