# Generated by Django 5.2.17 on 2026-10-04 23:13

import django.db.models.deletion
import django.db.models.functions.datetime
import kpigo.platform.db
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hierarchy", "0002_product_lines_available_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("email", kpigo.platform.db.CITextField()),
                ("display_name", models.TextField()),
                ("auth_provider", models.TextField()),
                ("external_id", models.TextField(null=True)),
                ("status", models.TextField(db_default="invited")),
                ("last_login_at", models.DateTimeField(null=True)),
                ("failed_logins", models.IntegerField(db_default=0)),
                ("locked_until", models.DateTimeField(null=True)),
                ("invite_token_hash", models.TextField(null=True)),
                ("invite_expires_at", models.DateTimeField(null=True)),
                ("disabled_at", models.DateTimeField(null=True)),
                ("disabled_reason", models.TextField(db_default="")),
                (
                    "auth_user",
                    models.OneToOneField(
                        db_column="auth_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="app_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="app_users",
                        to="hierarchy.subject",
                    ),
                ),
            ],
            options={
                "db_table": "app_user",
            },
        ),
        migrations.CreateModel(
            name="AuthFlowState",
            fields=[
                ("state", models.TextField(primary_key=True, serialize=False)),
                ("org_id", models.UUIDField()),
                ("provider", models.TextField()),
                ("nonce", models.TextField(db_default="")),
                ("code_verifier", models.TextField(db_default="")),
                ("next_path", models.TextField(db_default="/")),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "auth_flow_state",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("provider__in", ["oidc", "saml"])),
                        name="auth_flow_state_provider_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataScopeGrant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "grant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("role_code", models.TextField(null=True)),
                ("module", models.TextField()),
                ("dimension_type", models.TextField()),
                ("member_code", models.TextField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
                (
                    "app_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scope_grants",
                        to="access.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "data_scope_grant",
            },
        ),
        migrations.CreateModel(
            name="DirectoryImport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "import_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("source", models.TextField()),
                ("status", models.TextField(db_default="previewed")),
                ("full_roster", models.BooleanField(db_default=True)),
                ("records", models.JSONField()),
                ("diff", models.JSONField()),
                ("summary", models.JSONField()),
                ("applied_at", models.DateTimeField(null=True)),
                ("applied_by", models.BigIntegerField(null=True)),
            ],
            options={
                "db_table": "directory_import",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source__in", ["ldap", "entra", "file"])),
                        name="directory_import_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["previewed", "applied", "discarded"])),
                        name="directory_import_status_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "role_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("code", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(db_default="")),
                ("cloned_from", models.TextField(null=True)),
            ],
            options={
                "db_table": "role",
                "constraints": [
                    models.UniqueConstraint(fields=("org_id", "code"), name="role_code_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePageAccess",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_key", models.TextField()),
                ("access", models.TextField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="access.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_page_access",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("permission", models.TextField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="access.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_permission",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("role_code", models.TextField()),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="access.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "user_role",
            },
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.UniqueConstraint(
                fields=("org_id", "email"), name="app_user_email_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.UniqueConstraint(
                fields=("org_id", "auth_provider", "external_id"),
                name="app_user_external_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subject__isnull", False)),
                fields=("org_id", "subject"),
                name="app_user_subject_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("auth_provider__in", ["local", "ldap", "oidc", "saml"])),
                name="app_user_provider_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["invited", "active", "disabled"])),
                name="app_user_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="datascopegrant",
            index=models.Index(fields=["org_id", "module"], name="data_scope_grant_module"),
        ),
        migrations.AddConstraint(
            model_name="datascopegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("module__in", ["executive", "campaign"])),
                name="data_scope_grant_module_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="datascopegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("app_user__isnull", True), ("role_code__isnull", False)),
                    models.Q(("app_user__isnull", False), ("role_code__isnull", True)),
                    _connector="OR",
                ),
                name="data_scope_grant_one_holder",
            ),
        ),
        migrations.AddConstraint(
            model_name="datascopegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="data_scope_grant_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepageaccess",
            constraint=models.UniqueConstraint(
                fields=("role", "page_key"), name="role_page_access_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepageaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(("access__in", ["none", "view", "edit"])),
                name="role_page_access_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="role_permission_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("app_user", "role_code"), name="user_role_unique"
            ),
        ),
    ]
