# Generated by Django 5.2.17 on 2026-10-07 19:22

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_user_preference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "token_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("name", models.TextField()),
                ("token_hash", models.TextField()),
                ("prefix", models.TextField()),
                ("status", models.TextField(db_default="active")),
                ("expires_at", models.DateTimeField(null=True)),
                ("last_used_at", models.DateTimeField(null=True)),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="access.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "api_token",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "name"), name="api_token_name_unique"
                    ),
                    models.UniqueConstraint(fields=("token_hash",), name="api_token_hash_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "revoked"])),
                        name="api_token_status_valid",
                    ),
                ],
            },
        ),
    ]
