// Generated by scripts/gen-actions.mjs from openapi.json. Do not edit.
import type { operations } from "./schema";

export const ROUTES = {
  "agent.cohort.list": { method: "GET", path: "/api/v1/actions/agent.cohort.list", pathParams: [], public: false },
  "agent.cohort.set": { method: "POST", path: "/api/v1/actions/agent.cohort.set", pathParams: [], public: false },
  "agent.daily.archive": { method: "POST", path: "/api/v1/actions/agent.daily.archive", pathParams: [], public: false },
  "agent.daily.archive.list": { method: "GET", path: "/api/v1/actions/agent.daily.archive.list", pathParams: [], public: false },
  "agent.daily.restore": { method: "POST", path: "/api/v1/actions/agent.daily.restore", pathParams: [], public: false },
  "agent.distribution": { method: "GET", path: "/api/v1/actions/agent.distribution", pathParams: [], public: false },
  "agent.heatmap": { method: "GET", path: "/api/v1/actions/agent.heatmap", pathParams: [], public: false },
  "agent.leaderboard": { method: "GET", path: "/api/v1/actions/agent.leaderboard", pathParams: [], public: false },
  "agent.leaderboard.refresh": { method: "POST", path: "/api/v1/actions/agent.leaderboard.refresh", pathParams: [], public: false },
  "agent.matrix": { method: "GET", path: "/api/v1/actions/agent.matrix", pathParams: [], public: false },
  "agent.pace": { method: "GET", path: "/api/v1/actions/agent.pace", pathParams: [], public: false },
  "agent.pipeline": { method: "GET", path: "/api/v1/actions/agent.pipeline", pathParams: [], public: false },
  "agent.preset": { method: "GET", path: "/api/v1/actions/agent.preset", pathParams: [], public: false },
  "agent.settings.get": { method: "GET", path: "/api/v1/actions/agent.settings.get", pathParams: [], public: false },
  "agent.settings.set": { method: "POST", path: "/api/v1/actions/agent.settings.set", pathParams: [], public: false },
  "agent.trend": { method: "GET", path: "/api/v1/actions/agent.trend", pathParams: [], public: false },
  "agent.visibility.clear": { method: "POST", path: "/api/v1/actions/agent.visibility.clear", pathParams: [], public: false },
  "agent.visibility.list": { method: "GET", path: "/api/v1/actions/agent.visibility.list", pathParams: [], public: false },
  "agent.visibility.set": { method: "POST", path: "/api/v1/actions/agent.visibility.set", pathParams: [], public: false },
  "apitoken.issue": { method: "POST", path: "/api/v1/api-tokens", pathParams: [], public: false },
  "apitoken.list": { method: "GET", path: "/api/v1/api-tokens", pathParams: [], public: false },
  "apitoken.revoke": { method: "POST", path: "/api/v1/api-tokens/revoke", pathParams: [], public: false },
  "approval.policy.list": { method: "GET", path: "/api/v1/approval-policies", pathParams: [], public: false },
  "approval.policy.set": { method: "POST", path: "/api/v1/actions/approval.policy.set", pathParams: [], public: false },
  "assignment.create": { method: "POST", path: "/api/v1/actions/assignment.create", pathParams: [], public: false },
  "assignment.end": { method: "POST", path: "/api/v1/actions/assignment.end", pathParams: [], public: false },
  "assignment.list": { method: "GET", path: "/api/v1/actions/assignment.list", pathParams: [], public: false },
  "auth.invite.accept": { method: "POST", path: "/api/v1/auth/invite/accept", pathParams: [], public: true },
  "auth.login": { method: "POST", path: "/api/v1/auth/login", pathParams: [], public: true },
  "auth.logout": { method: "POST", path: "/api/v1/auth/logout", pathParams: [], public: false },
  "auth.me": { method: "GET", path: "/api/v1/auth/me", pathParams: [], public: false },
  "auth.oidc.complete": { method: "POST", path: "/api/v1/auth/oidc/complete", pathParams: [], public: true },
  "auth.oidc.start": { method: "POST", path: "/api/v1/auth/oidc/start", pathParams: [], public: true },
  "auth.password.change": { method: "POST", path: "/api/v1/actions/auth.password.change", pathParams: [], public: false },
  "auth.providers": { method: "GET", path: "/api/v1/auth/providers", pathParams: [], public: true },
  "auth.saml.start": { method: "POST", path: "/api/v1/auth/saml/start", pathParams: [], public: true },
  "band.list": { method: "GET", path: "/api/v1/actions/band.list", pathParams: [], public: false },
  "band.set": { method: "POST", path: "/api/v1/actions/band.set", pathParams: [], public: false },
  "calendar.business_date": { method: "GET", path: "/api/v1/actions/calendar.business_date", pathParams: [], public: false },
  "calendar.list": { method: "GET", path: "/api/v1/actions/calendar.list", pathParams: [], public: false },
  "calendar.set_days": { method: "POST", path: "/api/v1/actions/calendar.set_days", pathParams: [], public: false },
  "campaign.attribution.rule.set": { method: "POST", path: "/api/v1/actions/campaign.attribution.rule.set", pathParams: [], public: false },
  "campaign.attribution.run": { method: "POST", path: "/api/v1/actions/campaign.attribution.run", pathParams: [], public: false },
  "campaign.audience.estimate": { method: "GET", path: "/api/v1/actions/campaign.audience.estimate", pathParams: [], public: false },
  "campaign.board": { method: "GET", path: "/api/v1/actions/campaign.board", pathParams: [], public: false },
  "campaign.builder.reference": { method: "GET", path: "/api/v1/actions/campaign.builder.reference", pathParams: [], public: false },
  "campaign.close": { method: "POST", path: "/api/v1/actions/campaign.close", pathParams: [], public: false },
  "campaign.create": { method: "POST", path: "/api/v1/actions/campaign.create", pathParams: [], public: false },
  "campaign.event.add": { method: "POST", path: "/api/v1/actions/campaign.event.add", pathParams: [], public: false },
  "campaign.event.budget.set": { method: "POST", path: "/api/v1/actions/campaign.event.budget.set", pathParams: [], public: false },
  "campaign.event.history": { method: "GET", path: "/api/v1/actions/campaign.event.history", pathParams: [], public: false },
  "campaign.event.publish": { method: "POST", path: "/api/v1/actions/campaign.event.publish", pathParams: [], public: false },
  "campaign.event.remove": { method: "POST", path: "/api/v1/actions/campaign.event.remove", pathParams: [], public: false },
  "campaign.event.repeat": { method: "POST", path: "/api/v1/actions/campaign.event.repeat", pathParams: [], public: false },
  "campaign.event.status": { method: "POST", path: "/api/v1/actions/campaign.event.status", pathParams: [], public: false },
  "campaign.event.update": { method: "POST", path: "/api/v1/actions/campaign.event.update", pathParams: [], public: false },
  "campaign.get": { method: "GET", path: "/api/v1/actions/campaign.get", pathParams: [], public: false },
  "campaign.list": { method: "GET", path: "/api/v1/actions/campaign.list", pathParams: [], public: false },
  "campaign.metric.publish": { method: "POST", path: "/api/v1/actions/campaign.metric.publish", pathParams: [], public: false },
  "campaign.metric.withdraw": { method: "POST", path: "/api/v1/actions/campaign.metric.withdraw", pathParams: [], public: false },
  "campaign.metrics": { method: "GET", path: "/api/v1/actions/campaign.metrics", pathParams: [], public: false },
  "campaign.objective.list": { method: "GET", path: "/api/v1/actions/campaign.objective.list", pathParams: [], public: false },
  "campaign.objective.set": { method: "POST", path: "/api/v1/actions/campaign.objective.set", pathParams: [], public: false },
  "campaign.reach": { method: "GET", path: "/api/v1/actions/campaign.reach", pathParams: [], public: false },
  "campaign.reconciliation": { method: "GET", path: "/api/v1/actions/campaign.reconciliation", pathParams: [], public: false },
  "campaign.update": { method: "POST", path: "/api/v1/actions/campaign.update", pathParams: [], public: false },
  "campaign.value": { method: "GET", path: "/api/v1/actions/campaign.value", pathParams: [], public: false },
  "campaign.value_basis.set": { method: "POST", path: "/api/v1/actions/campaign.value_basis.set", pathParams: [], public: false },
  "campaign.winback.retention.set": { method: "POST", path: "/api/v1/actions/campaign.winback.retention.set", pathParams: [], public: false },
  "campaign.winbacks": { method: "GET", path: "/api/v1/actions/campaign.winbacks", pathParams: [], public: false },
  "connection.create": { method: "POST", path: "/api/v1/actions/connection.create", pathParams: [], public: false },
  "connection.list": { method: "GET", path: "/api/v1/actions/connection.list", pathParams: [], public: false },
  "connection.test": { method: "GET", path: "/api/v1/actions/connection.test", pathParams: [], public: false },
  "connection.update": { method: "POST", path: "/api/v1/actions/connection.update", pathParams: [], public: false },
  "currency.list": { method: "GET", path: "/api/v1/actions/currency.list", pathParams: [], public: false },
  "currency.upsert": { method: "POST", path: "/api/v1/actions/currency.upsert", pathParams: [], public: false },
  "cycle.bind": { method: "POST", path: "/api/v1/actions/cycle.bind", pathParams: [], public: false },
  "cycle.create": { method: "POST", path: "/api/v1/actions/cycle.create", pathParams: [], public: false },
  "cycle.list": { method: "GET", path: "/api/v1/actions/cycle.list", pathParams: [], public: false },
  "demo.reset": { method: "POST", path: "/api/v1/demo/reset", pathParams: [], public: false },
  "demo.seed": { method: "POST", path: "/api/v1/demo/seed", pathParams: [], public: false },
  "demo.status": { method: "GET", path: "/api/v1/demo/status", pathParams: [], public: false },
  "dimension.define": { method: "POST", path: "/api/v1/actions/dimension.define", pathParams: [], public: false },
  "dimension.list": { method: "GET", path: "/api/v1/actions/dimension.list", pathParams: [], public: false },
  "dimension.member.list": { method: "GET", path: "/api/v1/actions/dimension.member.list", pathParams: [], public: false },
  "dimension.member.upsert": { method: "POST", path: "/api/v1/actions/dimension.member.upsert", pathParams: [], public: false },
  "directory.import.apply": { method: "POST", path: "/api/v1/actions/directory.import.apply", pathParams: [], public: false },
  "directory.import.discard": { method: "POST", path: "/api/v1/actions/directory.import.discard", pathParams: [], public: false },
  "directory.import.list": { method: "GET", path: "/api/v1/actions/directory.import.list", pathParams: [], public: false },
  "directory.import.preview": { method: "POST", path: "/api/v1/actions/directory.import.preview", pathParams: [], public: false },
  "directory.test": { method: "GET", path: "/api/v1/actions/directory.test", pathParams: [], public: false },
  "executive.input.list": { method: "GET", path: "/api/v1/actions/executive.input.list", pathParams: [], public: false },
  "executive.input.set": { method: "POST", path: "/api/v1/actions/executive.input.set", pathParams: [], public: false },
  "executive.view.delete": { method: "POST", path: "/api/v1/actions/executive.view.delete", pathParams: [], public: false },
  "executive.view.list": { method: "GET", path: "/api/v1/actions/executive.view.list", pathParams: [], public: false },
  "executive.view.save": { method: "POST", path: "/api/v1/actions/executive.view.save", pathParams: [], public: false },
  "feed.contract.export": { method: "GET", path: "/api/v1/actions/feed.contract.export", pathParams: [], public: false },
  "feed.dry_run": { method: "POST", path: "/api/v1/actions/feed.dry_run", pathParams: [], public: false },
  "feed.get": { method: "GET", path: "/api/v1/actions/feed.get", pathParams: [], public: false },
  "feed.list": { method: "GET", path: "/api/v1/actions/feed.list", pathParams: [], public: false },
  "feed.register": { method: "POST", path: "/api/v1/actions/feed.register", pathParams: [], public: false },
  "feed.rejections.export": { method: "GET", path: "/api/v1/actions/feed.rejections.export", pathParams: [], public: false },
  "feed.run": { method: "POST", path: "/api/v1/actions/feed.run", pathParams: [], public: false },
  "feed.run.get": { method: "GET", path: "/api/v1/actions/feed.run.get", pathParams: [], public: false },
  "feed.run.list": { method: "GET", path: "/api/v1/actions/feed.run.list", pathParams: [], public: false },
  "feed.tick": { method: "POST", path: "/api/v1/actions/feed.tick", pathParams: [], public: false },
  "feed.update": { method: "POST", path: "/api/v1/actions/feed.update", pathParams: [], public: false },
  "fx.list": { method: "GET", path: "/api/v1/actions/fx.list", pathParams: [], public: false },
  "fx.set": { method: "POST", path: "/api/v1/actions/fx.set", pathParams: [], public: false },
  "input.assignment.create": { method: "POST", path: "/api/v1/actions/input.assignment.create", pathParams: [], public: false },
  "input.assignment.end": { method: "POST", path: "/api/v1/actions/input.assignment.end", pathParams: [], public: false },
  "input.assignment.list": { method: "GET", path: "/api/v1/actions/input.assignment.list", pathParams: [], public: false },
  "input.assignment.set_stakeholders": { method: "POST", path: "/api/v1/actions/input.assignment.set_stakeholders", pathParams: [], public: false },
  "input.compliance": { method: "GET", path: "/api/v1/actions/input.compliance", pathParams: [], public: false },
  "input.escalation.list": { method: "GET", path: "/api/v1/actions/input.escalation.list", pathParams: [], public: false },
  "input.ladder.get": { method: "GET", path: "/api/v1/actions/input.ladder.get", pathParams: [], public: false },
  "input.ladder.set": { method: "POST", path: "/api/v1/actions/input.ladder.set", pathParams: [], public: false },
  "input.remind": { method: "POST", path: "/api/v1/actions/input.remind", pathParams: [], public: false },
  "input.save": { method: "POST", path: "/api/v1/actions/input.save", pathParams: [], public: false },
  "input.submit": { method: "POST", path: "/api/v1/actions/input.submit", pathParams: [], public: false },
  "input.task.list": { method: "GET", path: "/api/v1/actions/input.task.list", pathParams: [], public: false },
  "licence.activate": { method: "POST", path: "/api/v1/licence/activate", pathParams: [], public: false },
  "licence.entitlement.check": { method: "GET", path: "/api/v1/actions/licence.entitlement.check", pathParams: [], public: false },
  "licence.heartbeat": { method: "POST", path: "/api/v1/actions/licence.heartbeat", pathParams: [], public: false },
  "licence.status": { method: "GET", path: "/api/v1/licence", pathParams: [], public: false },
  "mcp.status": { method: "GET", path: "/api/v1/mcp/status", pathParams: [], public: false },
  "metric.binding.set": { method: "POST", path: "/api/v1/actions/metric.binding.set", pathParams: [], public: false },
  "metric.check_name": { method: "GET", path: "/api/v1/actions/metric.check_name", pathParams: [], public: false },
  "metric.get": { method: "GET", path: "/api/v1/actions/metric.get", pathParams: [], public: false },
  "metric.list": { method: "GET", path: "/api/v1/actions/metric.list", pathParams: [], public: false },
  "metric.profile.assign": { method: "POST", path: "/api/v1/actions/metric.profile.assign", pathParams: [], public: false },
  "metric.register": { method: "POST", path: "/api/v1/actions/metric.register", pathParams: [], public: false },
  "metric.set_status": { method: "POST", path: "/api/v1/actions/metric.set_status", pathParams: [], public: false },
  "metric.update": { method: "POST", path: "/api/v1/actions/metric.update", pathParams: [], public: false },
  "notification.digest": { method: "POST", path: "/api/v1/actions/notification.digest", pathParams: [], public: false },
  "notification.list": { method: "GET", path: "/api/v1/notifications", pathParams: [], public: false },
  "notification.mark_read": { method: "POST", path: "/api/v1/notifications/read", pathParams: [], public: false },
  "override.approve": { method: "POST", path: "/api/v1/actions/override.approve", pathParams: [], public: false },
  "override.list": { method: "GET", path: "/api/v1/actions/override.list", pathParams: [], public: false },
  "override.reject": { method: "POST", path: "/api/v1/actions/override.reject", pathParams: [], public: false },
  "override.request": { method: "POST", path: "/api/v1/actions/override.request", pathParams: [], public: false },
  "override.revoke": { method: "POST", path: "/api/v1/actions/override.revoke", pathParams: [], public: false },
  "override.withdraw": { method: "POST", path: "/api/v1/actions/override.withdraw", pathParams: [], public: false },
  "pack.list": { method: "GET", path: "/api/v1/packs", pathParams: [], public: false },
  "pack.load": { method: "POST", path: "/api/v1/packs/load", pathParams: [], public: false },
  "period.deadline.list": { method: "GET", path: "/api/v1/actions/period.deadline.list", pathParams: [], public: false },
  "period.deadline.set": { method: "POST", path: "/api/v1/actions/period.deadline.set", pathParams: [], public: false },
  "period.list": { method: "GET", path: "/api/v1/actions/period.list", pathParams: [], public: false },
  "period.transition": { method: "POST", path: "/api/v1/actions/period.transition", pathParams: [], public: false },
  "pipeline.stage.list": { method: "GET", path: "/api/v1/actions/pipeline.stage.list", pathParams: [], public: false },
  "pipeline.stage.remove": { method: "POST", path: "/api/v1/actions/pipeline.stage.remove", pathParams: [], public: false },
  "pipeline.stage.set": { method: "POST", path: "/api/v1/actions/pipeline.stage.set", pathParams: [], public: false },
  "platform.approval.approve": { method: "POST", path: "/api/v1/actions/platform.approval.approve", pathParams: [], public: false },
  "platform.approval.reject": { method: "POST", path: "/api/v1/actions/platform.approval.reject", pathParams: [], public: false },
  "platform.hello": { method: "GET", path: "/api/v1/hello", pathParams: [], public: false },
  "platform.migrations.plan": { method: "GET", path: "/api/v1/actions/platform.migrations.plan", pathParams: [], public: false },
  "platform.registry.list": { method: "GET", path: "/api/v1/registry", pathParams: [], public: false },
  "preference.list": { method: "GET", path: "/api/v1/actions/preference.list", pathParams: [], public: false },
  "preference.set": { method: "POST", path: "/api/v1/actions/preference.set", pathParams: [], public: false },
  "product_group.set": { method: "POST", path: "/api/v1/actions/product_group.set", pathParams: [], public: false },
  "product_line.activate": { method: "POST", path: "/api/v1/actions/product_line.activate", pathParams: [], public: false },
  "product_line.list": { method: "GET", path: "/api/v1/actions/product_line.list", pathParams: [], public: false },
  "product_line.move": { method: "POST", path: "/api/v1/actions/product_line.move", pathParams: [], public: false },
  "product_line.registry": { method: "GET", path: "/api/v1/actions/product_line.registry", pathParams: [], public: false },
  "product_line.reorder": { method: "POST", path: "/api/v1/actions/product_line.reorder", pathParams: [], public: false },
  "product_line.retire": { method: "POST", path: "/api/v1/actions/product_line.retire", pathParams: [], public: false },
  "product_line.update": { method: "POST", path: "/api/v1/actions/product_line.update", pathParams: [], public: false },
  "reporting_edge.create": { method: "POST", path: "/api/v1/actions/reporting_edge.create", pathParams: [], public: false },
  "reporting_edge.end": { method: "POST", path: "/api/v1/actions/reporting_edge.end", pathParams: [], public: false },
  "reporting_edge.list": { method: "GET", path: "/api/v1/actions/reporting_edge.list", pathParams: [], public: false },
  "role.clone": { method: "POST", path: "/api/v1/actions/role.clone", pathParams: [], public: false },
  "role.get": { method: "GET", path: "/api/v1/actions/role.get", pathParams: [], public: false },
  "role.list": { method: "GET", path: "/api/v1/roles", pathParams: [], public: false },
  "role.update": { method: "POST", path: "/api/v1/actions/role.update", pathParams: [], public: false },
  "rollup_policy.list": { method: "GET", path: "/api/v1/actions/rollup_policy.list", pathParams: [], public: false },
  "rollup_policy.set": { method: "POST", path: "/api/v1/actions/rollup_policy.set", pathParams: [], public: false },
  "scope.grant.create": { method: "POST", path: "/api/v1/actions/scope.grant.create", pathParams: [], public: false },
  "scope.grant.end": { method: "POST", path: "/api/v1/actions/scope.grant.end", pathParams: [], public: false },
  "scope.grant.list": { method: "GET", path: "/api/v1/scope-grants", pathParams: [], public: false },
  "scorecard.acknowledge": { method: "POST", path: "/api/v1/actions/scorecard.acknowledge", pathParams: [], public: false },
  "scorecard.close.check": { method: "GET", path: "/api/v1/actions/scorecard.close.check", pathParams: [], public: false },
  "scorecard.comment.add": { method: "POST", path: "/api/v1/actions/scorecard.comment.add", pathParams: [], public: false },
  "scorecard.compute": { method: "GET", path: "/api/v1/actions/scorecard.compute", pathParams: [], public: false },
  "scorecard.exclusion.add": { method: "POST", path: "/api/v1/actions/scorecard.exclusion.add", pathParams: [], public: false },
  "scorecard.exclusion.list": { method: "GET", path: "/api/v1/actions/scorecard.exclusion.list", pathParams: [], public: false },
  "scorecard.exclusion.remove": { method: "POST", path: "/api/v1/actions/scorecard.exclusion.remove", pathParams: [], public: false },
  "scorecard.export.pdf": { method: "GET", path: "/api/v1/actions/scorecard.export.pdf", pathParams: [], public: false },
  "scorecard.history": { method: "GET", path: "/api/v1/actions/scorecard.history", pathParams: [], public: false },
  "scorecard.interaction.list": { method: "GET", path: "/api/v1/actions/scorecard.interaction.list", pathParams: [], public: false },
  "scorecard.node.delete": { method: "POST", path: "/api/v1/actions/scorecard.node.delete", pathParams: [], public: false },
  "scorecard.node.save": { method: "POST", path: "/api/v1/actions/scorecard.node.save", pathParams: [], public: false },
  "scorecard.period.close": { method: "POST", path: "/api/v1/actions/scorecard.period.close", pathParams: [], public: false },
  "scorecard.period.list": { method: "GET", path: "/api/v1/actions/scorecard.period.list", pathParams: [], public: false },
  "scorecard.period.restate": { method: "POST", path: "/api/v1/actions/scorecard.period.restate", pathParams: [], public: false },
  "scorecard.placement.clear": { method: "POST", path: "/api/v1/actions/scorecard.placement.clear", pathParams: [], public: false },
  "scorecard.placement.set": { method: "POST", path: "/api/v1/actions/scorecard.placement.set", pathParams: [], public: false },
  "scorecard.profile.list": { method: "GET", path: "/api/v1/actions/scorecard.profile.list", pathParams: [], public: false },
  "scorecard.profile.set_metrics": { method: "POST", path: "/api/v1/actions/scorecard.profile.set_metrics", pathParams: [], public: false },
  "scorecard.query.list": { method: "GET", path: "/api/v1/actions/scorecard.query.list", pathParams: [], public: false },
  "scorecard.query.raise": { method: "POST", path: "/api/v1/actions/scorecard.query.raise", pathParams: [], public: false },
  "scorecard.query.resolve": { method: "POST", path: "/api/v1/actions/scorecard.query.resolve", pathParams: [], public: false },
  "scorecard.settings.get": { method: "GET", path: "/api/v1/actions/scorecard.settings.get", pathParams: [], public: false },
  "scorecard.settings.set": { method: "POST", path: "/api/v1/actions/scorecard.settings.set", pathParams: [], public: false },
  "scorecard.snapshot.list": { method: "GET", path: "/api/v1/actions/scorecard.snapshot.list", pathParams: [], public: false },
  "scorecard.template.activate": { method: "POST", path: "/api/v1/actions/scorecard.template.activate", pathParams: [], public: false },
  "scorecard.template.get": { method: "GET", path: "/api/v1/actions/scorecard.template.get", pathParams: [], public: false },
  "scorecard.template.list": { method: "GET", path: "/api/v1/actions/scorecard.template.list", pathParams: [], public: false },
  "scorecard.template.save": { method: "POST", path: "/api/v1/actions/scorecard.template.save", pathParams: [], public: false },
  "settings.get": { method: "GET", path: "/api/v1/actions/settings.get", pathParams: [], public: false },
  "settings.update": { method: "POST", path: "/api/v1/actions/settings.update", pathParams: [], public: false },
  "setup.bootstrap": { method: "POST", path: "/api/v1/setup/bootstrap", pathParams: [], public: true },
  "setup.status": { method: "GET", path: "/api/v1/setup", pathParams: [], public: true },
  "subject.get": { method: "GET", path: "/api/v1/actions/subject.get", pathParams: [], public: false },
  "subject.list": { method: "GET", path: "/api/v1/actions/subject.list", pathParams: [], public: false },
  "subject.register": { method: "POST", path: "/api/v1/actions/subject.register", pathParams: [], public: false },
  "subject.update": { method: "POST", path: "/api/v1/actions/subject.update", pathParams: [], public: false },
  "system.backup": { method: "POST", path: "/api/v1/ops/backup", pathParams: [], public: false },
  "system.backup.list": { method: "GET", path: "/api/v1/ops/backups", pathParams: [], public: false },
  "system.diagnostics": { method: "GET", path: "/api/v1/ops/diagnostics", pathParams: [], public: false },
  "system.health": { method: "GET", path: "/api/v1/health", pathParams: [], public: false },
  "system.update.apply": { method: "POST", path: "/api/v1/ops/update/apply", pathParams: [], public: false },
  "system.update.check": { method: "GET", path: "/api/v1/ops/update/check", pathParams: [], public: false },
  "system.update.history": { method: "GET", path: "/api/v1/ops/update/history", pathParams: [], public: false },
  "target.batch.list": { method: "GET", path: "/api/v1/actions/target.batch.list", pathParams: [], public: false },
  "target.batch.revert": { method: "POST", path: "/api/v1/actions/target.batch.revert", pathParams: [], public: false },
  "target.copy_forward": { method: "POST", path: "/api/v1/actions/target.copy_forward", pathParams: [], public: false },
  "target.coverage": { method: "GET", path: "/api/v1/actions/target.coverage", pathParams: [], public: false },
  "target.draft.discard": { method: "POST", path: "/api/v1/actions/target.draft.discard", pathParams: [], public: false },
  "target.get": { method: "GET", path: "/api/v1/actions/target.get", pathParams: [], public: false },
  "target.list": { method: "GET", path: "/api/v1/actions/target.list", pathParams: [], public: false },
  "target.publish": { method: "POST", path: "/api/v1/actions/target.publish", pathParams: [], public: false },
  "target.upload": { method: "POST", path: "/api/v1/actions/target.upload", pathParams: [], public: false },
  "user.disable": { method: "POST", path: "/api/v1/actions/user.disable", pathParams: [], public: false },
  "user.enable": { method: "POST", path: "/api/v1/actions/user.enable", pathParams: [], public: false },
  "user.get": { method: "GET", path: "/api/v1/actions/user.get", pathParams: [], public: false },
  "user.invite": { method: "POST", path: "/api/v1/users/invite", pathParams: [], public: false },
  "user.invite.resend": { method: "POST", path: "/api/v1/actions/user.invite.resend", pathParams: [], public: false },
  "user.list": { method: "GET", path: "/api/v1/users", pathParams: [], public: false },
  "user.reassign": { method: "POST", path: "/api/v1/actions/user.reassign", pathParams: [], public: false },
  "user.update": { method: "POST", path: "/api/v1/actions/user.update", pathParams: [], public: false },
  "visibility.list": { method: "GET", path: "/api/v1/actions/visibility.list", pathParams: [], public: false },
  "visibility.rebuild": { method: "POST", path: "/api/v1/actions/visibility.rebuild", pathParams: [], public: false },
  "webhook.list": { method: "GET", path: "/api/v1/webhooks", pathParams: [], public: false },
  "webhook.register": { method: "POST", path: "/api/v1/webhooks", pathParams: [], public: false },
  "webhook.remove": { method: "POST", path: "/api/v1/webhooks/remove", pathParams: [], public: false },
  "webhook.test": { method: "POST", path: "/api/v1/webhooks/test", pathParams: [], public: false },
  "widget.dashboard": { method: "GET", path: "/api/v1/actions/widget.dashboard", pathParams: [], public: false },
  "widget.data": { method: "GET", path: "/api/v1/actions/widget.data", pathParams: [], public: false },
  "widget.history": { method: "GET", path: "/api/v1/actions/widget.history", pathParams: [], public: false },
  "widget.list": { method: "GET", path: "/api/v1/actions/widget.list", pathParams: [], public: false },
  "widget.place": { method: "POST", path: "/api/v1/actions/widget.place", pathParams: [], public: false },
  "widget.remove": { method: "POST", path: "/api/v1/actions/widget.remove", pathParams: [], public: false },
  "widget.thresholds.set": { method: "POST", path: "/api/v1/actions/widget.thresholds.set", pathParams: [], public: false },
  "widget.update": { method: "POST", path: "/api/v1/actions/widget.update", pathParams: [], public: false },
} as const;

export interface Actions {
  "agent.cohort.list": { input: NonNullable<operations["agent_cohort_list"]["parameters"]["query"]>; output: operations["agent_cohort_list"]["responses"][200]["content"]["application/json"] };
  "agent.cohort.set": { input: NonNullable<operations["agent_cohort_set"]["requestBody"]>["content"]["application/json"]; output: operations["agent_cohort_set"]["responses"][200]["content"]["application/json"] };
  "agent.daily.archive": { input: NonNullable<operations["agent_daily_archive"]["requestBody"]>["content"]["application/json"]; output: operations["agent_daily_archive"]["responses"][200]["content"]["application/json"] };
  "agent.daily.archive.list": { input: NonNullable<operations["agent_daily_archive_list"]["parameters"]["query"]>; output: operations["agent_daily_archive_list"]["responses"][200]["content"]["application/json"] };
  "agent.daily.restore": { input: NonNullable<operations["agent_daily_restore"]["requestBody"]>["content"]["application/json"]; output: operations["agent_daily_restore"]["responses"][200]["content"]["application/json"] };
  "agent.distribution": { input: NonNullable<operations["agent_distribution"]["parameters"]["query"]>; output: operations["agent_distribution"]["responses"][200]["content"]["application/json"] };
  "agent.heatmap": { input: NonNullable<operations["agent_heatmap"]["parameters"]["query"]>; output: operations["agent_heatmap"]["responses"][200]["content"]["application/json"] };
  "agent.leaderboard": { input: NonNullable<operations["agent_leaderboard"]["parameters"]["query"]>; output: operations["agent_leaderboard"]["responses"][200]["content"]["application/json"] };
  "agent.leaderboard.refresh": { input: NonNullable<operations["agent_leaderboard_refresh"]["requestBody"]>["content"]["application/json"]; output: operations["agent_leaderboard_refresh"]["responses"][200]["content"]["application/json"] };
  "agent.matrix": { input: NonNullable<operations["agent_matrix"]["parameters"]["query"]>; output: operations["agent_matrix"]["responses"][200]["content"]["application/json"] };
  "agent.pace": { input: NonNullable<operations["agent_pace"]["parameters"]["query"]>; output: operations["agent_pace"]["responses"][200]["content"]["application/json"] };
  "agent.pipeline": { input: NonNullable<operations["agent_pipeline"]["parameters"]["query"]>; output: operations["agent_pipeline"]["responses"][200]["content"]["application/json"] };
  "agent.preset": { input: NonNullable<operations["agent_preset"]["parameters"]["query"]>; output: operations["agent_preset"]["responses"][200]["content"]["application/json"] };
  "agent.settings.get": { input: NonNullable<operations["agent_settings_get"]["parameters"]["query"]>; output: operations["agent_settings_get"]["responses"][200]["content"]["application/json"] };
  "agent.settings.set": { input: NonNullable<operations["agent_settings_set"]["requestBody"]>["content"]["application/json"]; output: operations["agent_settings_set"]["responses"][200]["content"]["application/json"] };
  "agent.trend": { input: NonNullable<operations["agent_trend"]["parameters"]["query"]>; output: operations["agent_trend"]["responses"][200]["content"]["application/json"] };
  "agent.visibility.clear": { input: NonNullable<operations["agent_visibility_clear"]["requestBody"]>["content"]["application/json"]; output: operations["agent_visibility_clear"]["responses"][200]["content"]["application/json"] };
  "agent.visibility.list": { input: NonNullable<operations["agent_visibility_list"]["parameters"]["query"]>; output: operations["agent_visibility_list"]["responses"][200]["content"]["application/json"] };
  "agent.visibility.set": { input: NonNullable<operations["agent_visibility_set"]["requestBody"]>["content"]["application/json"]; output: operations["agent_visibility_set"]["responses"][200]["content"]["application/json"] };
  "apitoken.issue": { input: NonNullable<operations["apitoken_issue"]["requestBody"]>["content"]["application/json"]; output: operations["apitoken_issue"]["responses"][200]["content"]["application/json"] };
  "apitoken.list": { input: Record<string, never>; output: operations["apitoken_list"]["responses"][200]["content"]["application/json"] };
  "apitoken.revoke": { input: NonNullable<operations["apitoken_revoke"]["requestBody"]>["content"]["application/json"]; output: operations["apitoken_revoke"]["responses"][200]["content"]["application/json"] };
  "approval.policy.list": { input: Record<string, never>; output: operations["approval_policy_list"]["responses"][200]["content"]["application/json"] };
  "approval.policy.set": { input: NonNullable<operations["approval_policy_set"]["requestBody"]>["content"]["application/json"]; output: operations["approval_policy_set"]["responses"][200]["content"]["application/json"] };
  "assignment.create": { input: NonNullable<operations["assignment_create"]["requestBody"]>["content"]["application/json"]; output: operations["assignment_create"]["responses"][200]["content"]["application/json"] };
  "assignment.end": { input: NonNullable<operations["assignment_end"]["requestBody"]>["content"]["application/json"]; output: operations["assignment_end"]["responses"][200]["content"]["application/json"] };
  "assignment.list": { input: NonNullable<operations["assignment_list"]["parameters"]["query"]>; output: operations["assignment_list"]["responses"][200]["content"]["application/json"] };
  "auth.invite.accept": { input: NonNullable<operations["auth_invite_accept"]["requestBody"]>["content"]["application/json"]; output: operations["auth_invite_accept"]["responses"][200]["content"]["application/json"] };
  "auth.login": { input: NonNullable<operations["auth_login"]["requestBody"]>["content"]["application/json"]; output: operations["auth_login"]["responses"][200]["content"]["application/json"] };
  "auth.logout": { input: NonNullable<operations["auth_logout"]["requestBody"]>["content"]["application/json"]; output: operations["auth_logout"]["responses"][200]["content"]["application/json"] };
  "auth.me": { input: Record<string, never>; output: operations["auth_me"]["responses"][200]["content"]["application/json"] };
  "auth.oidc.complete": { input: NonNullable<operations["auth_oidc_complete"]["requestBody"]>["content"]["application/json"]; output: operations["auth_oidc_complete"]["responses"][200]["content"]["application/json"] };
  "auth.oidc.start": { input: NonNullable<operations["auth_oidc_start"]["requestBody"]>["content"]["application/json"]; output: operations["auth_oidc_start"]["responses"][200]["content"]["application/json"] };
  "auth.password.change": { input: NonNullable<operations["auth_password_change"]["requestBody"]>["content"]["application/json"]; output: operations["auth_password_change"]["responses"][200]["content"]["application/json"] };
  "auth.providers": { input: Record<string, never>; output: operations["auth_providers"]["responses"][200]["content"]["application/json"] };
  "auth.saml.start": { input: NonNullable<operations["auth_saml_start"]["requestBody"]>["content"]["application/json"]; output: operations["auth_saml_start"]["responses"][200]["content"]["application/json"] };
  "band.list": { input: Record<string, never>; output: operations["band_list"]["responses"][200]["content"]["application/json"] };
  "band.set": { input: NonNullable<operations["band_set"]["requestBody"]>["content"]["application/json"]; output: operations["band_set"]["responses"][200]["content"]["application/json"] };
  "calendar.business_date": { input: NonNullable<operations["calendar_business_date"]["parameters"]["query"]>; output: operations["calendar_business_date"]["responses"][200]["content"]["application/json"] };
  "calendar.list": { input: NonNullable<operations["calendar_list"]["parameters"]["query"]>; output: operations["calendar_list"]["responses"][200]["content"]["application/json"] };
  "calendar.set_days": { input: NonNullable<operations["calendar_set_days"]["requestBody"]>["content"]["application/json"]; output: operations["calendar_set_days"]["responses"][200]["content"]["application/json"] };
  "campaign.attribution.rule.set": { input: NonNullable<operations["campaign_attribution_rule_set"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_attribution_rule_set"]["responses"][200]["content"]["application/json"] };
  "campaign.attribution.run": { input: NonNullable<operations["campaign_attribution_run"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_attribution_run"]["responses"][200]["content"]["application/json"] };
  "campaign.audience.estimate": { input: NonNullable<operations["campaign_audience_estimate"]["parameters"]["query"]>; output: operations["campaign_audience_estimate"]["responses"][200]["content"]["application/json"] };
  "campaign.board": { input: NonNullable<operations["campaign_board"]["parameters"]["query"]>; output: operations["campaign_board"]["responses"][200]["content"]["application/json"] };
  "campaign.builder.reference": { input: Record<string, never>; output: operations["campaign_builder_reference"]["responses"][200]["content"]["application/json"] };
  "campaign.close": { input: NonNullable<operations["campaign_close"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_close"]["responses"][200]["content"]["application/json"] };
  "campaign.create": { input: NonNullable<operations["campaign_create"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_create"]["responses"][200]["content"]["application/json"] };
  "campaign.event.add": { input: NonNullable<operations["campaign_event_add"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_event_add"]["responses"][200]["content"]["application/json"] };
  "campaign.event.budget.set": { input: NonNullable<operations["campaign_event_budget_set"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_event_budget_set"]["responses"][200]["content"]["application/json"] };
  "campaign.event.history": { input: NonNullable<operations["campaign_event_history"]["parameters"]["query"]>; output: operations["campaign_event_history"]["responses"][200]["content"]["application/json"] };
  "campaign.event.publish": { input: NonNullable<operations["campaign_event_publish"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_event_publish"]["responses"][200]["content"]["application/json"] };
  "campaign.event.remove": { input: NonNullable<operations["campaign_event_remove"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_event_remove"]["responses"][200]["content"]["application/json"] };
  "campaign.event.repeat": { input: NonNullable<operations["campaign_event_repeat"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_event_repeat"]["responses"][200]["content"]["application/json"] };
  "campaign.event.status": { input: NonNullable<operations["campaign_event_status"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_event_status"]["responses"][200]["content"]["application/json"] };
  "campaign.event.update": { input: NonNullable<operations["campaign_event_update"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_event_update"]["responses"][200]["content"]["application/json"] };
  "campaign.get": { input: NonNullable<operations["campaign_get"]["parameters"]["query"]>; output: operations["campaign_get"]["responses"][200]["content"]["application/json"] };
  "campaign.list": { input: NonNullable<operations["campaign_list"]["parameters"]["query"]>; output: operations["campaign_list"]["responses"][200]["content"]["application/json"] };
  "campaign.metric.publish": { input: NonNullable<operations["campaign_metric_publish"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_metric_publish"]["responses"][200]["content"]["application/json"] };
  "campaign.metric.withdraw": { input: NonNullable<operations["campaign_metric_withdraw"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_metric_withdraw"]["responses"][200]["content"]["application/json"] };
  "campaign.metrics": { input: NonNullable<operations["campaign_metrics"]["parameters"]["query"]>; output: operations["campaign_metrics"]["responses"][200]["content"]["application/json"] };
  "campaign.objective.list": { input: Record<string, never>; output: operations["campaign_objective_list"]["responses"][200]["content"]["application/json"] };
  "campaign.objective.set": { input: NonNullable<operations["campaign_objective_set"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_objective_set"]["responses"][200]["content"]["application/json"] };
  "campaign.reach": { input: NonNullable<operations["campaign_reach"]["parameters"]["query"]>; output: operations["campaign_reach"]["responses"][200]["content"]["application/json"] };
  "campaign.reconciliation": { input: NonNullable<operations["campaign_reconciliation"]["parameters"]["query"]>; output: operations["campaign_reconciliation"]["responses"][200]["content"]["application/json"] };
  "campaign.update": { input: NonNullable<operations["campaign_update"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_update"]["responses"][200]["content"]["application/json"] };
  "campaign.value": { input: NonNullable<operations["campaign_value"]["parameters"]["query"]>; output: operations["campaign_value"]["responses"][200]["content"]["application/json"] };
  "campaign.value_basis.set": { input: NonNullable<operations["campaign_value_basis_set"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_value_basis_set"]["responses"][200]["content"]["application/json"] };
  "campaign.winback.retention.set": { input: NonNullable<operations["campaign_winback_retention_set"]["requestBody"]>["content"]["application/json"]; output: operations["campaign_winback_retention_set"]["responses"][200]["content"]["application/json"] };
  "campaign.winbacks": { input: NonNullable<operations["campaign_winbacks"]["parameters"]["query"]>; output: operations["campaign_winbacks"]["responses"][200]["content"]["application/json"] };
  "connection.create": { input: NonNullable<operations["connection_create"]["requestBody"]>["content"]["application/json"]; output: operations["connection_create"]["responses"][200]["content"]["application/json"] };
  "connection.list": { input: Record<string, never>; output: operations["connection_list"]["responses"][200]["content"]["application/json"] };
  "connection.test": { input: NonNullable<operations["connection_test"]["parameters"]["query"]>; output: operations["connection_test"]["responses"][200]["content"]["application/json"] };
  "connection.update": { input: NonNullable<operations["connection_update"]["requestBody"]>["content"]["application/json"]; output: operations["connection_update"]["responses"][200]["content"]["application/json"] };
  "currency.list": { input: NonNullable<operations["currency_list"]["parameters"]["query"]>; output: operations["currency_list"]["responses"][200]["content"]["application/json"] };
  "currency.upsert": { input: NonNullable<operations["currency_upsert"]["requestBody"]>["content"]["application/json"]; output: operations["currency_upsert"]["responses"][200]["content"]["application/json"] };
  "cycle.bind": { input: NonNullable<operations["cycle_bind"]["requestBody"]>["content"]["application/json"]; output: operations["cycle_bind"]["responses"][200]["content"]["application/json"] };
  "cycle.create": { input: NonNullable<operations["cycle_create"]["requestBody"]>["content"]["application/json"]; output: operations["cycle_create"]["responses"][200]["content"]["application/json"] };
  "cycle.list": { input: Record<string, never>; output: operations["cycle_list"]["responses"][200]["content"]["application/json"] };
  "demo.reset": { input: NonNullable<operations["demo_reset"]["requestBody"]>["content"]["application/json"]; output: operations["demo_reset"]["responses"][200]["content"]["application/json"] };
  "demo.seed": { input: NonNullable<operations["demo_seed"]["requestBody"]>["content"]["application/json"]; output: operations["demo_seed"]["responses"][200]["content"]["application/json"] };
  "demo.status": { input: Record<string, never>; output: operations["demo_status"]["responses"][200]["content"]["application/json"] };
  "dimension.define": { input: NonNullable<operations["dimension_define"]["requestBody"]>["content"]["application/json"]; output: operations["dimension_define"]["responses"][200]["content"]["application/json"] };
  "dimension.list": { input: Record<string, never>; output: operations["dimension_list"]["responses"][200]["content"]["application/json"] };
  "dimension.member.list": { input: NonNullable<operations["dimension_member_list"]["parameters"]["query"]>; output: operations["dimension_member_list"]["responses"][200]["content"]["application/json"] };
  "dimension.member.upsert": { input: NonNullable<operations["dimension_member_upsert"]["requestBody"]>["content"]["application/json"]; output: operations["dimension_member_upsert"]["responses"][200]["content"]["application/json"] };
  "directory.import.apply": { input: NonNullable<operations["directory_import_apply"]["requestBody"]>["content"]["application/json"]; output: operations["directory_import_apply"]["responses"][200]["content"]["application/json"] };
  "directory.import.discard": { input: NonNullable<operations["directory_import_discard"]["requestBody"]>["content"]["application/json"]; output: operations["directory_import_discard"]["responses"][200]["content"]["application/json"] };
  "directory.import.list": { input: NonNullable<operations["directory_import_list"]["parameters"]["query"]>; output: operations["directory_import_list"]["responses"][200]["content"]["application/json"] };
  "directory.import.preview": { input: NonNullable<operations["directory_import_preview"]["requestBody"]>["content"]["application/json"]; output: operations["directory_import_preview"]["responses"][200]["content"]["application/json"] };
  "directory.test": { input: NonNullable<operations["directory_test"]["parameters"]["query"]>; output: operations["directory_test"]["responses"][200]["content"]["application/json"] };
  "executive.input.list": { input: NonNullable<operations["executive_input_list"]["parameters"]["query"]>; output: operations["executive_input_list"]["responses"][200]["content"]["application/json"] };
  "executive.input.set": { input: NonNullable<operations["executive_input_set"]["requestBody"]>["content"]["application/json"]; output: operations["executive_input_set"]["responses"][200]["content"]["application/json"] };
  "executive.view.delete": { input: NonNullable<operations["executive_view_delete"]["requestBody"]>["content"]["application/json"]; output: operations["executive_view_delete"]["responses"][200]["content"]["application/json"] };
  "executive.view.list": { input: Record<string, never>; output: operations["executive_view_list"]["responses"][200]["content"]["application/json"] };
  "executive.view.save": { input: NonNullable<operations["executive_view_save"]["requestBody"]>["content"]["application/json"]; output: operations["executive_view_save"]["responses"][200]["content"]["application/json"] };
  "feed.contract.export": { input: NonNullable<operations["feed_contract_export"]["parameters"]["query"]>; output: operations["feed_contract_export"]["responses"][200]["content"]["application/json"] };
  "feed.dry_run": { input: NonNullable<operations["feed_dry_run"]["requestBody"]>["content"]["application/json"]; output: operations["feed_dry_run"]["responses"][200]["content"]["application/json"] };
  "feed.get": { input: NonNullable<operations["feed_get"]["parameters"]["query"]>; output: operations["feed_get"]["responses"][200]["content"]["application/json"] };
  "feed.list": { input: NonNullable<operations["feed_list"]["parameters"]["query"]>; output: operations["feed_list"]["responses"][200]["content"]["application/json"] };
  "feed.register": { input: NonNullable<operations["feed_register"]["requestBody"]>["content"]["application/json"]; output: operations["feed_register"]["responses"][200]["content"]["application/json"] };
  "feed.rejections.export": { input: NonNullable<operations["feed_rejections_export"]["parameters"]["query"]>; output: operations["feed_rejections_export"]["responses"][200]["content"]["application/json"] };
  "feed.run": { input: NonNullable<operations["feed_run"]["requestBody"]>["content"]["application/json"]; output: operations["feed_run"]["responses"][200]["content"]["application/json"] };
  "feed.run.get": { input: NonNullable<operations["feed_run_get"]["parameters"]["query"]>; output: operations["feed_run_get"]["responses"][200]["content"]["application/json"] };
  "feed.run.list": { input: NonNullable<operations["feed_run_list"]["parameters"]["query"]>; output: operations["feed_run_list"]["responses"][200]["content"]["application/json"] };
  "feed.tick": { input: NonNullable<operations["feed_tick"]["requestBody"]>["content"]["application/json"]; output: operations["feed_tick"]["responses"][200]["content"]["application/json"] };
  "feed.update": { input: NonNullable<operations["feed_update"]["requestBody"]>["content"]["application/json"]; output: operations["feed_update"]["responses"][200]["content"]["application/json"] };
  "fx.list": { input: NonNullable<operations["fx_list"]["parameters"]["query"]>; output: operations["fx_list"]["responses"][200]["content"]["application/json"] };
  "fx.set": { input: NonNullable<operations["fx_set"]["requestBody"]>["content"]["application/json"]; output: operations["fx_set"]["responses"][200]["content"]["application/json"] };
  "input.assignment.create": { input: NonNullable<operations["input_assignment_create"]["requestBody"]>["content"]["application/json"]; output: operations["input_assignment_create"]["responses"][200]["content"]["application/json"] };
  "input.assignment.end": { input: NonNullable<operations["input_assignment_end"]["requestBody"]>["content"]["application/json"]; output: operations["input_assignment_end"]["responses"][200]["content"]["application/json"] };
  "input.assignment.list": { input: NonNullable<operations["input_assignment_list"]["parameters"]["query"]>; output: operations["input_assignment_list"]["responses"][200]["content"]["application/json"] };
  "input.assignment.set_stakeholders": { input: NonNullable<operations["input_assignment_set_stakeholders"]["requestBody"]>["content"]["application/json"]; output: operations["input_assignment_set_stakeholders"]["responses"][200]["content"]["application/json"] };
  "input.compliance": { input: NonNullable<operations["input_compliance"]["parameters"]["query"]>; output: operations["input_compliance"]["responses"][200]["content"]["application/json"] };
  "input.escalation.list": { input: Record<string, never>; output: operations["input_escalation_list"]["responses"][200]["content"]["application/json"] };
  "input.ladder.get": { input: NonNullable<operations["input_ladder_get"]["parameters"]["query"]>; output: operations["input_ladder_get"]["responses"][200]["content"]["application/json"] };
  "input.ladder.set": { input: NonNullable<operations["input_ladder_set"]["requestBody"]>["content"]["application/json"]; output: operations["input_ladder_set"]["responses"][200]["content"]["application/json"] };
  "input.remind": { input: NonNullable<operations["input_remind"]["requestBody"]>["content"]["application/json"]; output: operations["input_remind"]["responses"][200]["content"]["application/json"] };
  "input.save": { input: NonNullable<operations["input_save"]["requestBody"]>["content"]["application/json"]; output: operations["input_save"]["responses"][200]["content"]["application/json"] };
  "input.submit": { input: NonNullable<operations["input_submit"]["requestBody"]>["content"]["application/json"]; output: operations["input_submit"]["responses"][200]["content"]["application/json"] };
  "input.task.list": { input: NonNullable<operations["input_task_list"]["parameters"]["query"]>; output: operations["input_task_list"]["responses"][200]["content"]["application/json"] };
  "licence.activate": { input: NonNullable<operations["licence_activate"]["requestBody"]>["content"]["application/json"]; output: operations["licence_activate"]["responses"][200]["content"]["application/json"] };
  "licence.entitlement.check": { input: NonNullable<operations["licence_entitlement_check"]["parameters"]["query"]>; output: operations["licence_entitlement_check"]["responses"][200]["content"]["application/json"] };
  "licence.heartbeat": { input: NonNullable<operations["licence_heartbeat"]["requestBody"]>["content"]["application/json"]; output: operations["licence_heartbeat"]["responses"][200]["content"]["application/json"] };
  "licence.status": { input: Record<string, never>; output: operations["licence_status"]["responses"][200]["content"]["application/json"] };
  "mcp.status": { input: Record<string, never>; output: operations["mcp_status"]["responses"][200]["content"]["application/json"] };
  "metric.binding.set": { input: NonNullable<operations["metric_binding_set"]["requestBody"]>["content"]["application/json"]; output: operations["metric_binding_set"]["responses"][200]["content"]["application/json"] };
  "metric.check_name": { input: NonNullable<operations["metric_check_name"]["parameters"]["query"]>; output: operations["metric_check_name"]["responses"][200]["content"]["application/json"] };
  "metric.get": { input: NonNullable<operations["metric_get"]["parameters"]["query"]>; output: operations["metric_get"]["responses"][200]["content"]["application/json"] };
  "metric.list": { input: NonNullable<operations["metric_list"]["parameters"]["query"]>; output: operations["metric_list"]["responses"][200]["content"]["application/json"] };
  "metric.profile.assign": { input: NonNullable<operations["metric_profile_assign"]["requestBody"]>["content"]["application/json"]; output: operations["metric_profile_assign"]["responses"][200]["content"]["application/json"] };
  "metric.register": { input: NonNullable<operations["metric_register"]["requestBody"]>["content"]["application/json"]; output: operations["metric_register"]["responses"][200]["content"]["application/json"] };
  "metric.set_status": { input: NonNullable<operations["metric_set_status"]["requestBody"]>["content"]["application/json"]; output: operations["metric_set_status"]["responses"][200]["content"]["application/json"] };
  "metric.update": { input: NonNullable<operations["metric_update"]["requestBody"]>["content"]["application/json"]; output: operations["metric_update"]["responses"][200]["content"]["application/json"] };
  "notification.digest": { input: NonNullable<operations["notification_digest"]["requestBody"]>["content"]["application/json"]; output: operations["notification_digest"]["responses"][200]["content"]["application/json"] };
  "notification.list": { input: NonNullable<operations["notification_list"]["parameters"]["query"]>; output: operations["notification_list"]["responses"][200]["content"]["application/json"] };
  "notification.mark_read": { input: NonNullable<operations["notification_mark_read"]["requestBody"]>["content"]["application/json"]; output: operations["notification_mark_read"]["responses"][200]["content"]["application/json"] };
  "override.approve": { input: NonNullable<operations["override_approve"]["requestBody"]>["content"]["application/json"]; output: operations["override_approve"]["responses"][200]["content"]["application/json"] };
  "override.list": { input: NonNullable<operations["override_list"]["parameters"]["query"]>; output: operations["override_list"]["responses"][200]["content"]["application/json"] };
  "override.reject": { input: NonNullable<operations["override_reject"]["requestBody"]>["content"]["application/json"]; output: operations["override_reject"]["responses"][200]["content"]["application/json"] };
  "override.request": { input: NonNullable<operations["override_request"]["requestBody"]>["content"]["application/json"]; output: operations["override_request"]["responses"][200]["content"]["application/json"] };
  "override.revoke": { input: NonNullable<operations["override_revoke"]["requestBody"]>["content"]["application/json"]; output: operations["override_revoke"]["responses"][200]["content"]["application/json"] };
  "override.withdraw": { input: NonNullable<operations["override_withdraw"]["requestBody"]>["content"]["application/json"]; output: operations["override_withdraw"]["responses"][200]["content"]["application/json"] };
  "pack.list": { input: Record<string, never>; output: operations["pack_list"]["responses"][200]["content"]["application/json"] };
  "pack.load": { input: NonNullable<operations["pack_load"]["requestBody"]>["content"]["application/json"]; output: operations["pack_load"]["responses"][200]["content"]["application/json"] };
  "period.deadline.list": { input: NonNullable<operations["period_deadline_list"]["parameters"]["query"]>; output: operations["period_deadline_list"]["responses"][200]["content"]["application/json"] };
  "period.deadline.set": { input: NonNullable<operations["period_deadline_set"]["requestBody"]>["content"]["application/json"]; output: operations["period_deadline_set"]["responses"][200]["content"]["application/json"] };
  "period.list": { input: NonNullable<operations["period_list"]["parameters"]["query"]>; output: operations["period_list"]["responses"][200]["content"]["application/json"] };
  "period.transition": { input: NonNullable<operations["period_transition"]["requestBody"]>["content"]["application/json"]; output: operations["period_transition"]["responses"][200]["content"]["application/json"] };
  "pipeline.stage.list": { input: NonNullable<operations["pipeline_stage_list"]["parameters"]["query"]>; output: operations["pipeline_stage_list"]["responses"][200]["content"]["application/json"] };
  "pipeline.stage.remove": { input: NonNullable<operations["pipeline_stage_remove"]["requestBody"]>["content"]["application/json"]; output: operations["pipeline_stage_remove"]["responses"][200]["content"]["application/json"] };
  "pipeline.stage.set": { input: NonNullable<operations["pipeline_stage_set"]["requestBody"]>["content"]["application/json"]; output: operations["pipeline_stage_set"]["responses"][200]["content"]["application/json"] };
  "platform.approval.approve": { input: NonNullable<operations["platform_approval_approve"]["requestBody"]>["content"]["application/json"]; output: operations["platform_approval_approve"]["responses"][200]["content"]["application/json"] };
  "platform.approval.reject": { input: NonNullable<operations["platform_approval_reject"]["requestBody"]>["content"]["application/json"]; output: operations["platform_approval_reject"]["responses"][200]["content"]["application/json"] };
  "platform.hello": { input: NonNullable<operations["platform_hello"]["parameters"]["query"]>; output: operations["platform_hello"]["responses"][200]["content"]["application/json"] };
  "platform.migrations.plan": { input: Record<string, never>; output: operations["platform_migrations_plan"]["responses"][200]["content"]["application/json"] };
  "platform.registry.list": { input: NonNullable<operations["platform_registry_list"]["parameters"]["query"]>; output: operations["platform_registry_list"]["responses"][200]["content"]["application/json"] };
  "preference.list": { input: Record<string, never>; output: operations["preference_list"]["responses"][200]["content"]["application/json"] };
  "preference.set": { input: NonNullable<operations["preference_set"]["requestBody"]>["content"]["application/json"]; output: operations["preference_set"]["responses"][200]["content"]["application/json"] };
  "product_group.set": { input: NonNullable<operations["product_group_set"]["requestBody"]>["content"]["application/json"]; output: operations["product_group_set"]["responses"][200]["content"]["application/json"] };
  "product_line.activate": { input: NonNullable<operations["product_line_activate"]["requestBody"]>["content"]["application/json"]; output: operations["product_line_activate"]["responses"][200]["content"]["application/json"] };
  "product_line.list": { input: NonNullable<operations["product_line_list"]["parameters"]["query"]>; output: operations["product_line_list"]["responses"][200]["content"]["application/json"] };
  "product_line.move": { input: NonNullable<operations["product_line_move"]["requestBody"]>["content"]["application/json"]; output: operations["product_line_move"]["responses"][200]["content"]["application/json"] };
  "product_line.registry": { input: NonNullable<operations["product_line_registry"]["parameters"]["query"]>; output: operations["product_line_registry"]["responses"][200]["content"]["application/json"] };
  "product_line.reorder": { input: NonNullable<operations["product_line_reorder"]["requestBody"]>["content"]["application/json"]; output: operations["product_line_reorder"]["responses"][200]["content"]["application/json"] };
  "product_line.retire": { input: NonNullable<operations["product_line_retire"]["requestBody"]>["content"]["application/json"]; output: operations["product_line_retire"]["responses"][200]["content"]["application/json"] };
  "product_line.update": { input: NonNullable<operations["product_line_update"]["requestBody"]>["content"]["application/json"]; output: operations["product_line_update"]["responses"][200]["content"]["application/json"] };
  "reporting_edge.create": { input: NonNullable<operations["reporting_edge_create"]["requestBody"]>["content"]["application/json"]; output: operations["reporting_edge_create"]["responses"][200]["content"]["application/json"] };
  "reporting_edge.end": { input: NonNullable<operations["reporting_edge_end"]["requestBody"]>["content"]["application/json"]; output: operations["reporting_edge_end"]["responses"][200]["content"]["application/json"] };
  "reporting_edge.list": { input: NonNullable<operations["reporting_edge_list"]["parameters"]["query"]>; output: operations["reporting_edge_list"]["responses"][200]["content"]["application/json"] };
  "role.clone": { input: NonNullable<operations["role_clone"]["requestBody"]>["content"]["application/json"]; output: operations["role_clone"]["responses"][200]["content"]["application/json"] };
  "role.get": { input: NonNullable<operations["role_get"]["parameters"]["query"]>; output: operations["role_get"]["responses"][200]["content"]["application/json"] };
  "role.list": { input: Record<string, never>; output: operations["role_list"]["responses"][200]["content"]["application/json"] };
  "role.update": { input: NonNullable<operations["role_update"]["requestBody"]>["content"]["application/json"]; output: operations["role_update"]["responses"][200]["content"]["application/json"] };
  "rollup_policy.list": { input: NonNullable<operations["rollup_policy_list"]["parameters"]["query"]>; output: operations["rollup_policy_list"]["responses"][200]["content"]["application/json"] };
  "rollup_policy.set": { input: NonNullable<operations["rollup_policy_set"]["requestBody"]>["content"]["application/json"]; output: operations["rollup_policy_set"]["responses"][200]["content"]["application/json"] };
  "scope.grant.create": { input: NonNullable<operations["scope_grant_create"]["requestBody"]>["content"]["application/json"]; output: operations["scope_grant_create"]["responses"][200]["content"]["application/json"] };
  "scope.grant.end": { input: NonNullable<operations["scope_grant_end"]["requestBody"]>["content"]["application/json"]; output: operations["scope_grant_end"]["responses"][200]["content"]["application/json"] };
  "scope.grant.list": { input: NonNullable<operations["scope_grant_list"]["parameters"]["query"]>; output: operations["scope_grant_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.acknowledge": { input: NonNullable<operations["scorecard_acknowledge"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_acknowledge"]["responses"][200]["content"]["application/json"] };
  "scorecard.close.check": { input: NonNullable<operations["scorecard_close_check"]["parameters"]["query"]>; output: operations["scorecard_close_check"]["responses"][200]["content"]["application/json"] };
  "scorecard.comment.add": { input: NonNullable<operations["scorecard_comment_add"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_comment_add"]["responses"][200]["content"]["application/json"] };
  "scorecard.compute": { input: NonNullable<operations["scorecard_compute"]["parameters"]["query"]>; output: operations["scorecard_compute"]["responses"][200]["content"]["application/json"] };
  "scorecard.exclusion.add": { input: NonNullable<operations["scorecard_exclusion_add"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_exclusion_add"]["responses"][200]["content"]["application/json"] };
  "scorecard.exclusion.list": { input: NonNullable<operations["scorecard_exclusion_list"]["parameters"]["query"]>; output: operations["scorecard_exclusion_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.exclusion.remove": { input: NonNullable<operations["scorecard_exclusion_remove"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_exclusion_remove"]["responses"][200]["content"]["application/json"] };
  "scorecard.export.pdf": { input: NonNullable<operations["scorecard_export_pdf"]["parameters"]["query"]>; output: operations["scorecard_export_pdf"]["responses"][200]["content"]["application/json"] };
  "scorecard.history": { input: NonNullable<operations["scorecard_history"]["parameters"]["query"]>; output: operations["scorecard_history"]["responses"][200]["content"]["application/json"] };
  "scorecard.interaction.list": { input: NonNullable<operations["scorecard_interaction_list"]["parameters"]["query"]>; output: operations["scorecard_interaction_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.node.delete": { input: NonNullable<operations["scorecard_node_delete"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_node_delete"]["responses"][200]["content"]["application/json"] };
  "scorecard.node.save": { input: NonNullable<operations["scorecard_node_save"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_node_save"]["responses"][200]["content"]["application/json"] };
  "scorecard.period.close": { input: NonNullable<operations["scorecard_period_close"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_period_close"]["responses"][200]["content"]["application/json"] };
  "scorecard.period.list": { input: NonNullable<operations["scorecard_period_list"]["parameters"]["query"]>; output: operations["scorecard_period_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.period.restate": { input: NonNullable<operations["scorecard_period_restate"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_period_restate"]["responses"][200]["content"]["application/json"] };
  "scorecard.placement.clear": { input: NonNullable<operations["scorecard_placement_clear"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_placement_clear"]["responses"][200]["content"]["application/json"] };
  "scorecard.placement.set": { input: NonNullable<operations["scorecard_placement_set"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_placement_set"]["responses"][200]["content"]["application/json"] };
  "scorecard.profile.list": { input: NonNullable<operations["scorecard_profile_list"]["parameters"]["query"]>; output: operations["scorecard_profile_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.profile.set_metrics": { input: NonNullable<operations["scorecard_profile_set_metrics"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_profile_set_metrics"]["responses"][200]["content"]["application/json"] };
  "scorecard.query.list": { input: NonNullable<operations["scorecard_query_list"]["parameters"]["query"]>; output: operations["scorecard_query_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.query.raise": { input: NonNullable<operations["scorecard_query_raise"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_query_raise"]["responses"][200]["content"]["application/json"] };
  "scorecard.query.resolve": { input: NonNullable<operations["scorecard_query_resolve"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_query_resolve"]["responses"][200]["content"]["application/json"] };
  "scorecard.settings.get": { input: Record<string, never>; output: operations["scorecard_settings_get"]["responses"][200]["content"]["application/json"] };
  "scorecard.settings.set": { input: NonNullable<operations["scorecard_settings_set"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_settings_set"]["responses"][200]["content"]["application/json"] };
  "scorecard.snapshot.list": { input: NonNullable<operations["scorecard_snapshot_list"]["parameters"]["query"]>; output: operations["scorecard_snapshot_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.activate": { input: NonNullable<operations["scorecard_template_activate"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_template_activate"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.get": { input: NonNullable<operations["scorecard_template_get"]["parameters"]["query"]>; output: operations["scorecard_template_get"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.list": { input: Record<string, never>; output: operations["scorecard_template_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.save": { input: NonNullable<operations["scorecard_template_save"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_template_save"]["responses"][200]["content"]["application/json"] };
  "settings.get": { input: Record<string, never>; output: operations["settings_get"]["responses"][200]["content"]["application/json"] };
  "settings.update": { input: NonNullable<operations["settings_update"]["requestBody"]>["content"]["application/json"]; output: operations["settings_update"]["responses"][200]["content"]["application/json"] };
  "setup.bootstrap": { input: NonNullable<operations["setup_bootstrap"]["requestBody"]>["content"]["application/json"]; output: operations["setup_bootstrap"]["responses"][200]["content"]["application/json"] };
  "setup.status": { input: Record<string, never>; output: operations["setup_status"]["responses"][200]["content"]["application/json"] };
  "subject.get": { input: NonNullable<operations["subject_get"]["parameters"]["query"]>; output: operations["subject_get"]["responses"][200]["content"]["application/json"] };
  "subject.list": { input: NonNullable<operations["subject_list"]["parameters"]["query"]>; output: operations["subject_list"]["responses"][200]["content"]["application/json"] };
  "subject.register": { input: NonNullable<operations["subject_register"]["requestBody"]>["content"]["application/json"]; output: operations["subject_register"]["responses"][200]["content"]["application/json"] };
  "subject.update": { input: NonNullable<operations["subject_update"]["requestBody"]>["content"]["application/json"]; output: operations["subject_update"]["responses"][200]["content"]["application/json"] };
  "system.backup": { input: NonNullable<operations["system_backup"]["requestBody"]>["content"]["application/json"]; output: operations["system_backup"]["responses"][200]["content"]["application/json"] };
  "system.backup.list": { input: NonNullable<operations["system_backup_list"]["parameters"]["query"]>; output: operations["system_backup_list"]["responses"][200]["content"]["application/json"] };
  "system.diagnostics": { input: Record<string, never>; output: operations["system_diagnostics"]["responses"][200]["content"]["application/json"] };
  "system.health": { input: NonNullable<operations["system_health"]["parameters"]["query"]>; output: operations["system_health"]["responses"][200]["content"]["application/json"] };
  "system.update.apply": { input: NonNullable<operations["system_update_apply"]["requestBody"]>["content"]["application/json"]; output: operations["system_update_apply"]["responses"][200]["content"]["application/json"] };
  "system.update.check": { input: Record<string, never>; output: operations["system_update_check"]["responses"][200]["content"]["application/json"] };
  "system.update.history": { input: NonNullable<operations["system_update_history"]["parameters"]["query"]>; output: operations["system_update_history"]["responses"][200]["content"]["application/json"] };
  "target.batch.list": { input: NonNullable<operations["target_batch_list"]["parameters"]["query"]>; output: operations["target_batch_list"]["responses"][200]["content"]["application/json"] };
  "target.batch.revert": { input: NonNullable<operations["target_batch_revert"]["requestBody"]>["content"]["application/json"]; output: operations["target_batch_revert"]["responses"][200]["content"]["application/json"] };
  "target.copy_forward": { input: NonNullable<operations["target_copy_forward"]["requestBody"]>["content"]["application/json"]; output: operations["target_copy_forward"]["responses"][200]["content"]["application/json"] };
  "target.coverage": { input: NonNullable<operations["target_coverage"]["parameters"]["query"]>; output: operations["target_coverage"]["responses"][200]["content"]["application/json"] };
  "target.draft.discard": { input: NonNullable<operations["target_draft_discard"]["requestBody"]>["content"]["application/json"]; output: operations["target_draft_discard"]["responses"][200]["content"]["application/json"] };
  "target.get": { input: NonNullable<operations["target_get"]["parameters"]["query"]>; output: operations["target_get"]["responses"][200]["content"]["application/json"] };
  "target.list": { input: NonNullable<operations["target_list"]["parameters"]["query"]>; output: operations["target_list"]["responses"][200]["content"]["application/json"] };
  "target.publish": { input: NonNullable<operations["target_publish"]["requestBody"]>["content"]["application/json"]; output: operations["target_publish"]["responses"][200]["content"]["application/json"] };
  "target.upload": { input: NonNullable<operations["target_upload"]["requestBody"]>["content"]["application/json"]; output: operations["target_upload"]["responses"][200]["content"]["application/json"] };
  "user.disable": { input: NonNullable<operations["user_disable"]["requestBody"]>["content"]["application/json"]; output: operations["user_disable"]["responses"][200]["content"]["application/json"] };
  "user.enable": { input: NonNullable<operations["user_enable"]["requestBody"]>["content"]["application/json"]; output: operations["user_enable"]["responses"][200]["content"]["application/json"] };
  "user.get": { input: NonNullable<operations["user_get"]["parameters"]["query"]>; output: operations["user_get"]["responses"][200]["content"]["application/json"] };
  "user.invite": { input: NonNullable<operations["user_invite"]["requestBody"]>["content"]["application/json"]; output: operations["user_invite"]["responses"][200]["content"]["application/json"] };
  "user.invite.resend": { input: NonNullable<operations["user_invite_resend"]["requestBody"]>["content"]["application/json"]; output: operations["user_invite_resend"]["responses"][200]["content"]["application/json"] };
  "user.list": { input: NonNullable<operations["user_list"]["parameters"]["query"]>; output: operations["user_list"]["responses"][200]["content"]["application/json"] };
  "user.reassign": { input: NonNullable<operations["user_reassign"]["requestBody"]>["content"]["application/json"]; output: operations["user_reassign"]["responses"][200]["content"]["application/json"] };
  "user.update": { input: NonNullable<operations["user_update"]["requestBody"]>["content"]["application/json"]; output: operations["user_update"]["responses"][200]["content"]["application/json"] };
  "visibility.list": { input: NonNullable<operations["visibility_list"]["parameters"]["query"]>; output: operations["visibility_list"]["responses"][200]["content"]["application/json"] };
  "visibility.rebuild": { input: NonNullable<operations["visibility_rebuild"]["requestBody"]>["content"]["application/json"]; output: operations["visibility_rebuild"]["responses"][200]["content"]["application/json"] };
  "webhook.list": { input: Record<string, never>; output: operations["webhook_list"]["responses"][200]["content"]["application/json"] };
  "webhook.register": { input: NonNullable<operations["webhook_register"]["requestBody"]>["content"]["application/json"]; output: operations["webhook_register"]["responses"][200]["content"]["application/json"] };
  "webhook.remove": { input: NonNullable<operations["webhook_remove"]["requestBody"]>["content"]["application/json"]; output: operations["webhook_remove"]["responses"][200]["content"]["application/json"] };
  "webhook.test": { input: NonNullable<operations["webhook_test"]["requestBody"]>["content"]["application/json"]; output: operations["webhook_test"]["responses"][200]["content"]["application/json"] };
  "widget.dashboard": { input: Record<string, never>; output: operations["widget_dashboard"]["responses"][200]["content"]["application/json"] };
  "widget.data": { input: NonNullable<operations["widget_data"]["parameters"]["query"]>; output: operations["widget_data"]["responses"][200]["content"]["application/json"] };
  "widget.history": { input: NonNullable<operations["widget_history"]["parameters"]["query"]>; output: operations["widget_history"]["responses"][200]["content"]["application/json"] };
  "widget.list": { input: NonNullable<operations["widget_list"]["parameters"]["query"]>; output: operations["widget_list"]["responses"][200]["content"]["application/json"] };
  "widget.place": { input: NonNullable<operations["widget_place"]["requestBody"]>["content"]["application/json"]; output: operations["widget_place"]["responses"][200]["content"]["application/json"] };
  "widget.remove": { input: NonNullable<operations["widget_remove"]["requestBody"]>["content"]["application/json"]; output: operations["widget_remove"]["responses"][200]["content"]["application/json"] };
  "widget.thresholds.set": { input: NonNullable<operations["widget_thresholds_set"]["requestBody"]>["content"]["application/json"]; output: operations["widget_thresholds_set"]["responses"][200]["content"]["application/json"] };
  "widget.update": { input: NonNullable<operations["widget_update"]["requestBody"]>["content"]["application/json"]; output: operations["widget_update"]["responses"][200]["content"]["application/json"] };
}

export type ActionName = keyof Actions;
export type Input<N extends ActionName> = Actions[N]["input"];
export type Output<N extends ActionName> = Actions[N]["output"];
