// Generated by scripts/gen-actions.mjs from openapi.json. Do not edit.
import type { operations } from "./schema";

export const ROUTES = {
  "approval.policy.list": { method: "GET", path: "/api/v1/approval-policies", pathParams: [], public: false },
  "approval.policy.set": { method: "POST", path: "/api/v1/actions/approval.policy.set", pathParams: [], public: false },
  "assignment.create": { method: "POST", path: "/api/v1/actions/assignment.create", pathParams: [], public: false },
  "assignment.end": { method: "POST", path: "/api/v1/actions/assignment.end", pathParams: [], public: false },
  "assignment.list": { method: "GET", path: "/api/v1/actions/assignment.list", pathParams: [], public: false },
  "auth.invite.accept": { method: "POST", path: "/api/v1/auth/invite/accept", pathParams: [], public: true },
  "auth.login": { method: "POST", path: "/api/v1/auth/login", pathParams: [], public: true },
  "auth.logout": { method: "POST", path: "/api/v1/auth/logout", pathParams: [], public: false },
  "auth.me": { method: "GET", path: "/api/v1/auth/me", pathParams: [], public: false },
  "auth.oidc.complete": { method: "POST", path: "/api/v1/auth/oidc/complete", pathParams: [], public: true },
  "auth.oidc.start": { method: "POST", path: "/api/v1/auth/oidc/start", pathParams: [], public: true },
  "auth.password.change": { method: "POST", path: "/api/v1/actions/auth.password.change", pathParams: [], public: false },
  "auth.providers": { method: "GET", path: "/api/v1/auth/providers", pathParams: [], public: true },
  "auth.saml.start": { method: "POST", path: "/api/v1/auth/saml/start", pathParams: [], public: true },
  "band.list": { method: "GET", path: "/api/v1/actions/band.list", pathParams: [], public: false },
  "band.set": { method: "POST", path: "/api/v1/actions/band.set", pathParams: [], public: false },
  "calendar.business_date": { method: "GET", path: "/api/v1/actions/calendar.business_date", pathParams: [], public: false },
  "calendar.list": { method: "GET", path: "/api/v1/actions/calendar.list", pathParams: [], public: false },
  "calendar.set_days": { method: "POST", path: "/api/v1/actions/calendar.set_days", pathParams: [], public: false },
  "connection.create": { method: "POST", path: "/api/v1/actions/connection.create", pathParams: [], public: false },
  "connection.list": { method: "GET", path: "/api/v1/actions/connection.list", pathParams: [], public: false },
  "connection.test": { method: "GET", path: "/api/v1/actions/connection.test", pathParams: [], public: false },
  "connection.update": { method: "POST", path: "/api/v1/actions/connection.update", pathParams: [], public: false },
  "currency.list": { method: "GET", path: "/api/v1/actions/currency.list", pathParams: [], public: false },
  "currency.upsert": { method: "POST", path: "/api/v1/actions/currency.upsert", pathParams: [], public: false },
  "cycle.bind": { method: "POST", path: "/api/v1/actions/cycle.bind", pathParams: [], public: false },
  "cycle.create": { method: "POST", path: "/api/v1/actions/cycle.create", pathParams: [], public: false },
  "cycle.list": { method: "GET", path: "/api/v1/actions/cycle.list", pathParams: [], public: false },
  "dimension.define": { method: "POST", path: "/api/v1/actions/dimension.define", pathParams: [], public: false },
  "dimension.list": { method: "GET", path: "/api/v1/actions/dimension.list", pathParams: [], public: false },
  "dimension.member.list": { method: "GET", path: "/api/v1/actions/dimension.member.list", pathParams: [], public: false },
  "dimension.member.upsert": { method: "POST", path: "/api/v1/actions/dimension.member.upsert", pathParams: [], public: false },
  "directory.import.apply": { method: "POST", path: "/api/v1/actions/directory.import.apply", pathParams: [], public: false },
  "directory.import.discard": { method: "POST", path: "/api/v1/actions/directory.import.discard", pathParams: [], public: false },
  "directory.import.list": { method: "GET", path: "/api/v1/actions/directory.import.list", pathParams: [], public: false },
  "directory.import.preview": { method: "POST", path: "/api/v1/actions/directory.import.preview", pathParams: [], public: false },
  "directory.test": { method: "GET", path: "/api/v1/actions/directory.test", pathParams: [], public: false },
  "feed.contract.export": { method: "GET", path: "/api/v1/actions/feed.contract.export", pathParams: [], public: false },
  "feed.dry_run": { method: "POST", path: "/api/v1/actions/feed.dry_run", pathParams: [], public: false },
  "feed.get": { method: "GET", path: "/api/v1/actions/feed.get", pathParams: [], public: false },
  "feed.list": { method: "GET", path: "/api/v1/actions/feed.list", pathParams: [], public: false },
  "feed.register": { method: "POST", path: "/api/v1/actions/feed.register", pathParams: [], public: false },
  "feed.rejections.export": { method: "GET", path: "/api/v1/actions/feed.rejections.export", pathParams: [], public: false },
  "feed.run": { method: "POST", path: "/api/v1/actions/feed.run", pathParams: [], public: false },
  "feed.run.get": { method: "GET", path: "/api/v1/actions/feed.run.get", pathParams: [], public: false },
  "feed.run.list": { method: "GET", path: "/api/v1/actions/feed.run.list", pathParams: [], public: false },
  "feed.tick": { method: "POST", path: "/api/v1/actions/feed.tick", pathParams: [], public: false },
  "feed.update": { method: "POST", path: "/api/v1/actions/feed.update", pathParams: [], public: false },
  "fx.list": { method: "GET", path: "/api/v1/actions/fx.list", pathParams: [], public: false },
  "fx.set": { method: "POST", path: "/api/v1/actions/fx.set", pathParams: [], public: false },
  "licence.activate": { method: "POST", path: "/api/v1/licence/activate", pathParams: [], public: false },
  "licence.entitlement.check": { method: "GET", path: "/api/v1/actions/licence.entitlement.check", pathParams: [], public: false },
  "licence.heartbeat": { method: "POST", path: "/api/v1/actions/licence.heartbeat", pathParams: [], public: false },
  "licence.status": { method: "GET", path: "/api/v1/licence", pathParams: [], public: false },
  "metric.binding.set": { method: "POST", path: "/api/v1/actions/metric.binding.set", pathParams: [], public: false },
  "metric.check_name": { method: "GET", path: "/api/v1/actions/metric.check_name", pathParams: [], public: false },
  "metric.get": { method: "GET", path: "/api/v1/actions/metric.get", pathParams: [], public: false },
  "metric.list": { method: "GET", path: "/api/v1/actions/metric.list", pathParams: [], public: false },
  "metric.profile.assign": { method: "POST", path: "/api/v1/actions/metric.profile.assign", pathParams: [], public: false },
  "metric.register": { method: "POST", path: "/api/v1/actions/metric.register", pathParams: [], public: false },
  "metric.set_status": { method: "POST", path: "/api/v1/actions/metric.set_status", pathParams: [], public: false },
  "metric.update": { method: "POST", path: "/api/v1/actions/metric.update", pathParams: [], public: false },
  "period.deadline.list": { method: "GET", path: "/api/v1/actions/period.deadline.list", pathParams: [], public: false },
  "period.deadline.set": { method: "POST", path: "/api/v1/actions/period.deadline.set", pathParams: [], public: false },
  "period.list": { method: "GET", path: "/api/v1/actions/period.list", pathParams: [], public: false },
  "period.transition": { method: "POST", path: "/api/v1/actions/period.transition", pathParams: [], public: false },
  "platform.approval.approve": { method: "POST", path: "/api/v1/actions/platform.approval.approve", pathParams: [], public: false },
  "platform.approval.reject": { method: "POST", path: "/api/v1/actions/platform.approval.reject", pathParams: [], public: false },
  "platform.hello": { method: "GET", path: "/api/v1/hello", pathParams: [], public: false },
  "platform.migrations.plan": { method: "GET", path: "/api/v1/actions/platform.migrations.plan", pathParams: [], public: false },
  "platform.registry.list": { method: "GET", path: "/api/v1/registry", pathParams: [], public: false },
  "product_line.list": { method: "GET", path: "/api/v1/actions/product_line.list", pathParams: [], public: false },
  "reporting_edge.create": { method: "POST", path: "/api/v1/actions/reporting_edge.create", pathParams: [], public: false },
  "reporting_edge.end": { method: "POST", path: "/api/v1/actions/reporting_edge.end", pathParams: [], public: false },
  "reporting_edge.list": { method: "GET", path: "/api/v1/actions/reporting_edge.list", pathParams: [], public: false },
  "role.clone": { method: "POST", path: "/api/v1/actions/role.clone", pathParams: [], public: false },
  "role.get": { method: "GET", path: "/api/v1/actions/role.get", pathParams: [], public: false },
  "role.list": { method: "GET", path: "/api/v1/roles", pathParams: [], public: false },
  "role.update": { method: "POST", path: "/api/v1/actions/role.update", pathParams: [], public: false },
  "rollup_policy.list": { method: "GET", path: "/api/v1/actions/rollup_policy.list", pathParams: [], public: false },
  "rollup_policy.set": { method: "POST", path: "/api/v1/actions/rollup_policy.set", pathParams: [], public: false },
  "scope.grant.create": { method: "POST", path: "/api/v1/actions/scope.grant.create", pathParams: [], public: false },
  "scope.grant.end": { method: "POST", path: "/api/v1/actions/scope.grant.end", pathParams: [], public: false },
  "scope.grant.list": { method: "GET", path: "/api/v1/scope-grants", pathParams: [], public: false },
  "scorecard.node.delete": { method: "POST", path: "/api/v1/actions/scorecard.node.delete", pathParams: [], public: false },
  "scorecard.node.save": { method: "POST", path: "/api/v1/actions/scorecard.node.save", pathParams: [], public: false },
  "scorecard.placement.clear": { method: "POST", path: "/api/v1/actions/scorecard.placement.clear", pathParams: [], public: false },
  "scorecard.placement.set": { method: "POST", path: "/api/v1/actions/scorecard.placement.set", pathParams: [], public: false },
  "scorecard.profile.list": { method: "GET", path: "/api/v1/actions/scorecard.profile.list", pathParams: [], public: false },
  "scorecard.profile.set_metrics": { method: "POST", path: "/api/v1/actions/scorecard.profile.set_metrics", pathParams: [], public: false },
  "scorecard.settings.get": { method: "GET", path: "/api/v1/actions/scorecard.settings.get", pathParams: [], public: false },
  "scorecard.settings.set": { method: "POST", path: "/api/v1/actions/scorecard.settings.set", pathParams: [], public: false },
  "scorecard.template.activate": { method: "POST", path: "/api/v1/actions/scorecard.template.activate", pathParams: [], public: false },
  "scorecard.template.get": { method: "GET", path: "/api/v1/actions/scorecard.template.get", pathParams: [], public: false },
  "scorecard.template.list": { method: "GET", path: "/api/v1/actions/scorecard.template.list", pathParams: [], public: false },
  "scorecard.template.save": { method: "POST", path: "/api/v1/actions/scorecard.template.save", pathParams: [], public: false },
  "settings.get": { method: "GET", path: "/api/v1/actions/settings.get", pathParams: [], public: false },
  "settings.update": { method: "POST", path: "/api/v1/actions/settings.update", pathParams: [], public: false },
  "setup.bootstrap": { method: "POST", path: "/api/v1/setup/bootstrap", pathParams: [], public: true },
  "setup.status": { method: "GET", path: "/api/v1/setup", pathParams: [], public: true },
  "subject.get": { method: "GET", path: "/api/v1/actions/subject.get", pathParams: [], public: false },
  "subject.list": { method: "GET", path: "/api/v1/actions/subject.list", pathParams: [], public: false },
  "subject.register": { method: "POST", path: "/api/v1/actions/subject.register", pathParams: [], public: false },
  "subject.update": { method: "POST", path: "/api/v1/actions/subject.update", pathParams: [], public: false },
  "system.health": { method: "GET", path: "/api/v1/health", pathParams: [], public: false },
  "target.batch.list": { method: "GET", path: "/api/v1/actions/target.batch.list", pathParams: [], public: false },
  "target.batch.revert": { method: "POST", path: "/api/v1/actions/target.batch.revert", pathParams: [], public: false },
  "target.copy_forward": { method: "POST", path: "/api/v1/actions/target.copy_forward", pathParams: [], public: false },
  "target.coverage": { method: "GET", path: "/api/v1/actions/target.coverage", pathParams: [], public: false },
  "target.draft.discard": { method: "POST", path: "/api/v1/actions/target.draft.discard", pathParams: [], public: false },
  "target.get": { method: "GET", path: "/api/v1/actions/target.get", pathParams: [], public: false },
  "target.list": { method: "GET", path: "/api/v1/actions/target.list", pathParams: [], public: false },
  "target.publish": { method: "POST", path: "/api/v1/actions/target.publish", pathParams: [], public: false },
  "target.upload": { method: "POST", path: "/api/v1/actions/target.upload", pathParams: [], public: false },
  "user.disable": { method: "POST", path: "/api/v1/actions/user.disable", pathParams: [], public: false },
  "user.enable": { method: "POST", path: "/api/v1/actions/user.enable", pathParams: [], public: false },
  "user.get": { method: "GET", path: "/api/v1/actions/user.get", pathParams: [], public: false },
  "user.invite": { method: "POST", path: "/api/v1/users/invite", pathParams: [], public: false },
  "user.invite.resend": { method: "POST", path: "/api/v1/actions/user.invite.resend", pathParams: [], public: false },
  "user.list": { method: "GET", path: "/api/v1/users", pathParams: [], public: false },
  "user.reassign": { method: "POST", path: "/api/v1/actions/user.reassign", pathParams: [], public: false },
  "user.update": { method: "POST", path: "/api/v1/actions/user.update", pathParams: [], public: false },
  "visibility.list": { method: "GET", path: "/api/v1/actions/visibility.list", pathParams: [], public: false },
  "visibility.rebuild": { method: "POST", path: "/api/v1/actions/visibility.rebuild", pathParams: [], public: false },
} as const;

export interface Actions {
  "approval.policy.list": { input: Record<string, never>; output: operations["approval_policy_list"]["responses"][200]["content"]["application/json"] };
  "approval.policy.set": { input: NonNullable<operations["approval_policy_set"]["requestBody"]>["content"]["application/json"]; output: operations["approval_policy_set"]["responses"][200]["content"]["application/json"] };
  "assignment.create": { input: NonNullable<operations["assignment_create"]["requestBody"]>["content"]["application/json"]; output: operations["assignment_create"]["responses"][200]["content"]["application/json"] };
  "assignment.end": { input: NonNullable<operations["assignment_end"]["requestBody"]>["content"]["application/json"]; output: operations["assignment_end"]["responses"][200]["content"]["application/json"] };
  "assignment.list": { input: NonNullable<operations["assignment_list"]["parameters"]["query"]>; output: operations["assignment_list"]["responses"][200]["content"]["application/json"] };
  "auth.invite.accept": { input: NonNullable<operations["auth_invite_accept"]["requestBody"]>["content"]["application/json"]; output: operations["auth_invite_accept"]["responses"][200]["content"]["application/json"] };
  "auth.login": { input: NonNullable<operations["auth_login"]["requestBody"]>["content"]["application/json"]; output: operations["auth_login"]["responses"][200]["content"]["application/json"] };
  "auth.logout": { input: NonNullable<operations["auth_logout"]["requestBody"]>["content"]["application/json"]; output: operations["auth_logout"]["responses"][200]["content"]["application/json"] };
  "auth.me": { input: Record<string, never>; output: operations["auth_me"]["responses"][200]["content"]["application/json"] };
  "auth.oidc.complete": { input: NonNullable<operations["auth_oidc_complete"]["requestBody"]>["content"]["application/json"]; output: operations["auth_oidc_complete"]["responses"][200]["content"]["application/json"] };
  "auth.oidc.start": { input: NonNullable<operations["auth_oidc_start"]["requestBody"]>["content"]["application/json"]; output: operations["auth_oidc_start"]["responses"][200]["content"]["application/json"] };
  "auth.password.change": { input: NonNullable<operations["auth_password_change"]["requestBody"]>["content"]["application/json"]; output: operations["auth_password_change"]["responses"][200]["content"]["application/json"] };
  "auth.providers": { input: Record<string, never>; output: operations["auth_providers"]["responses"][200]["content"]["application/json"] };
  "auth.saml.start": { input: NonNullable<operations["auth_saml_start"]["requestBody"]>["content"]["application/json"]; output: operations["auth_saml_start"]["responses"][200]["content"]["application/json"] };
  "band.list": { input: Record<string, never>; output: operations["band_list"]["responses"][200]["content"]["application/json"] };
  "band.set": { input: NonNullable<operations["band_set"]["requestBody"]>["content"]["application/json"]; output: operations["band_set"]["responses"][200]["content"]["application/json"] };
  "calendar.business_date": { input: NonNullable<operations["calendar_business_date"]["parameters"]["query"]>; output: operations["calendar_business_date"]["responses"][200]["content"]["application/json"] };
  "calendar.list": { input: NonNullable<operations["calendar_list"]["parameters"]["query"]>; output: operations["calendar_list"]["responses"][200]["content"]["application/json"] };
  "calendar.set_days": { input: NonNullable<operations["calendar_set_days"]["requestBody"]>["content"]["application/json"]; output: operations["calendar_set_days"]["responses"][200]["content"]["application/json"] };
  "connection.create": { input: NonNullable<operations["connection_create"]["requestBody"]>["content"]["application/json"]; output: operations["connection_create"]["responses"][200]["content"]["application/json"] };
  "connection.list": { input: Record<string, never>; output: operations["connection_list"]["responses"][200]["content"]["application/json"] };
  "connection.test": { input: NonNullable<operations["connection_test"]["parameters"]["query"]>; output: operations["connection_test"]["responses"][200]["content"]["application/json"] };
  "connection.update": { input: NonNullable<operations["connection_update"]["requestBody"]>["content"]["application/json"]; output: operations["connection_update"]["responses"][200]["content"]["application/json"] };
  "currency.list": { input: NonNullable<operations["currency_list"]["parameters"]["query"]>; output: operations["currency_list"]["responses"][200]["content"]["application/json"] };
  "currency.upsert": { input: NonNullable<operations["currency_upsert"]["requestBody"]>["content"]["application/json"]; output: operations["currency_upsert"]["responses"][200]["content"]["application/json"] };
  "cycle.bind": { input: NonNullable<operations["cycle_bind"]["requestBody"]>["content"]["application/json"]; output: operations["cycle_bind"]["responses"][200]["content"]["application/json"] };
  "cycle.create": { input: NonNullable<operations["cycle_create"]["requestBody"]>["content"]["application/json"]; output: operations["cycle_create"]["responses"][200]["content"]["application/json"] };
  "cycle.list": { input: Record<string, never>; output: operations["cycle_list"]["responses"][200]["content"]["application/json"] };
  "dimension.define": { input: NonNullable<operations["dimension_define"]["requestBody"]>["content"]["application/json"]; output: operations["dimension_define"]["responses"][200]["content"]["application/json"] };
  "dimension.list": { input: Record<string, never>; output: operations["dimension_list"]["responses"][200]["content"]["application/json"] };
  "dimension.member.list": { input: NonNullable<operations["dimension_member_list"]["parameters"]["query"]>; output: operations["dimension_member_list"]["responses"][200]["content"]["application/json"] };
  "dimension.member.upsert": { input: NonNullable<operations["dimension_member_upsert"]["requestBody"]>["content"]["application/json"]; output: operations["dimension_member_upsert"]["responses"][200]["content"]["application/json"] };
  "directory.import.apply": { input: NonNullable<operations["directory_import_apply"]["requestBody"]>["content"]["application/json"]; output: operations["directory_import_apply"]["responses"][200]["content"]["application/json"] };
  "directory.import.discard": { input: NonNullable<operations["directory_import_discard"]["requestBody"]>["content"]["application/json"]; output: operations["directory_import_discard"]["responses"][200]["content"]["application/json"] };
  "directory.import.list": { input: NonNullable<operations["directory_import_list"]["parameters"]["query"]>; output: operations["directory_import_list"]["responses"][200]["content"]["application/json"] };
  "directory.import.preview": { input: NonNullable<operations["directory_import_preview"]["requestBody"]>["content"]["application/json"]; output: operations["directory_import_preview"]["responses"][200]["content"]["application/json"] };
  "directory.test": { input: NonNullable<operations["directory_test"]["parameters"]["query"]>; output: operations["directory_test"]["responses"][200]["content"]["application/json"] };
  "feed.contract.export": { input: NonNullable<operations["feed_contract_export"]["parameters"]["query"]>; output: operations["feed_contract_export"]["responses"][200]["content"]["application/json"] };
  "feed.dry_run": { input: NonNullable<operations["feed_dry_run"]["requestBody"]>["content"]["application/json"]; output: operations["feed_dry_run"]["responses"][200]["content"]["application/json"] };
  "feed.get": { input: NonNullable<operations["feed_get"]["parameters"]["query"]>; output: operations["feed_get"]["responses"][200]["content"]["application/json"] };
  "feed.list": { input: NonNullable<operations["feed_list"]["parameters"]["query"]>; output: operations["feed_list"]["responses"][200]["content"]["application/json"] };
  "feed.register": { input: NonNullable<operations["feed_register"]["requestBody"]>["content"]["application/json"]; output: operations["feed_register"]["responses"][200]["content"]["application/json"] };
  "feed.rejections.export": { input: NonNullable<operations["feed_rejections_export"]["parameters"]["query"]>; output: operations["feed_rejections_export"]["responses"][200]["content"]["application/json"] };
  "feed.run": { input: NonNullable<operations["feed_run"]["requestBody"]>["content"]["application/json"]; output: operations["feed_run"]["responses"][200]["content"]["application/json"] };
  "feed.run.get": { input: NonNullable<operations["feed_run_get"]["parameters"]["query"]>; output: operations["feed_run_get"]["responses"][200]["content"]["application/json"] };
  "feed.run.list": { input: NonNullable<operations["feed_run_list"]["parameters"]["query"]>; output: operations["feed_run_list"]["responses"][200]["content"]["application/json"] };
  "feed.tick": { input: NonNullable<operations["feed_tick"]["requestBody"]>["content"]["application/json"]; output: operations["feed_tick"]["responses"][200]["content"]["application/json"] };
  "feed.update": { input: NonNullable<operations["feed_update"]["requestBody"]>["content"]["application/json"]; output: operations["feed_update"]["responses"][200]["content"]["application/json"] };
  "fx.list": { input: NonNullable<operations["fx_list"]["parameters"]["query"]>; output: operations["fx_list"]["responses"][200]["content"]["application/json"] };
  "fx.set": { input: NonNullable<operations["fx_set"]["requestBody"]>["content"]["application/json"]; output: operations["fx_set"]["responses"][200]["content"]["application/json"] };
  "licence.activate": { input: NonNullable<operations["licence_activate"]["requestBody"]>["content"]["application/json"]; output: operations["licence_activate"]["responses"][200]["content"]["application/json"] };
  "licence.entitlement.check": { input: NonNullable<operations["licence_entitlement_check"]["parameters"]["query"]>; output: operations["licence_entitlement_check"]["responses"][200]["content"]["application/json"] };
  "licence.heartbeat": { input: NonNullable<operations["licence_heartbeat"]["requestBody"]>["content"]["application/json"]; output: operations["licence_heartbeat"]["responses"][200]["content"]["application/json"] };
  "licence.status": { input: Record<string, never>; output: operations["licence_status"]["responses"][200]["content"]["application/json"] };
  "metric.binding.set": { input: NonNullable<operations["metric_binding_set"]["requestBody"]>["content"]["application/json"]; output: operations["metric_binding_set"]["responses"][200]["content"]["application/json"] };
  "metric.check_name": { input: NonNullable<operations["metric_check_name"]["parameters"]["query"]>; output: operations["metric_check_name"]["responses"][200]["content"]["application/json"] };
  "metric.get": { input: NonNullable<operations["metric_get"]["parameters"]["query"]>; output: operations["metric_get"]["responses"][200]["content"]["application/json"] };
  "metric.list": { input: NonNullable<operations["metric_list"]["parameters"]["query"]>; output: operations["metric_list"]["responses"][200]["content"]["application/json"] };
  "metric.profile.assign": { input: NonNullable<operations["metric_profile_assign"]["requestBody"]>["content"]["application/json"]; output: operations["metric_profile_assign"]["responses"][200]["content"]["application/json"] };
  "metric.register": { input: NonNullable<operations["metric_register"]["requestBody"]>["content"]["application/json"]; output: operations["metric_register"]["responses"][200]["content"]["application/json"] };
  "metric.set_status": { input: NonNullable<operations["metric_set_status"]["requestBody"]>["content"]["application/json"]; output: operations["metric_set_status"]["responses"][200]["content"]["application/json"] };
  "metric.update": { input: NonNullable<operations["metric_update"]["requestBody"]>["content"]["application/json"]; output: operations["metric_update"]["responses"][200]["content"]["application/json"] };
  "period.deadline.list": { input: NonNullable<operations["period_deadline_list"]["parameters"]["query"]>; output: operations["period_deadline_list"]["responses"][200]["content"]["application/json"] };
  "period.deadline.set": { input: NonNullable<operations["period_deadline_set"]["requestBody"]>["content"]["application/json"]; output: operations["period_deadline_set"]["responses"][200]["content"]["application/json"] };
  "period.list": { input: NonNullable<operations["period_list"]["parameters"]["query"]>; output: operations["period_list"]["responses"][200]["content"]["application/json"] };
  "period.transition": { input: NonNullable<operations["period_transition"]["requestBody"]>["content"]["application/json"]; output: operations["period_transition"]["responses"][200]["content"]["application/json"] };
  "platform.approval.approve": { input: NonNullable<operations["platform_approval_approve"]["requestBody"]>["content"]["application/json"]; output: operations["platform_approval_approve"]["responses"][200]["content"]["application/json"] };
  "platform.approval.reject": { input: NonNullable<operations["platform_approval_reject"]["requestBody"]>["content"]["application/json"]; output: operations["platform_approval_reject"]["responses"][200]["content"]["application/json"] };
  "platform.hello": { input: NonNullable<operations["platform_hello"]["parameters"]["query"]>; output: operations["platform_hello"]["responses"][200]["content"]["application/json"] };
  "platform.migrations.plan": { input: Record<string, never>; output: operations["platform_migrations_plan"]["responses"][200]["content"]["application/json"] };
  "platform.registry.list": { input: NonNullable<operations["platform_registry_list"]["parameters"]["query"]>; output: operations["platform_registry_list"]["responses"][200]["content"]["application/json"] };
  "product_line.list": { input: NonNullable<operations["product_line_list"]["parameters"]["query"]>; output: operations["product_line_list"]["responses"][200]["content"]["application/json"] };
  "reporting_edge.create": { input: NonNullable<operations["reporting_edge_create"]["requestBody"]>["content"]["application/json"]; output: operations["reporting_edge_create"]["responses"][200]["content"]["application/json"] };
  "reporting_edge.end": { input: NonNullable<operations["reporting_edge_end"]["requestBody"]>["content"]["application/json"]; output: operations["reporting_edge_end"]["responses"][200]["content"]["application/json"] };
  "reporting_edge.list": { input: NonNullable<operations["reporting_edge_list"]["parameters"]["query"]>; output: operations["reporting_edge_list"]["responses"][200]["content"]["application/json"] };
  "role.clone": { input: NonNullable<operations["role_clone"]["requestBody"]>["content"]["application/json"]; output: operations["role_clone"]["responses"][200]["content"]["application/json"] };
  "role.get": { input: NonNullable<operations["role_get"]["parameters"]["query"]>; output: operations["role_get"]["responses"][200]["content"]["application/json"] };
  "role.list": { input: Record<string, never>; output: operations["role_list"]["responses"][200]["content"]["application/json"] };
  "role.update": { input: NonNullable<operations["role_update"]["requestBody"]>["content"]["application/json"]; output: operations["role_update"]["responses"][200]["content"]["application/json"] };
  "rollup_policy.list": { input: NonNullable<operations["rollup_policy_list"]["parameters"]["query"]>; output: operations["rollup_policy_list"]["responses"][200]["content"]["application/json"] };
  "rollup_policy.set": { input: NonNullable<operations["rollup_policy_set"]["requestBody"]>["content"]["application/json"]; output: operations["rollup_policy_set"]["responses"][200]["content"]["application/json"] };
  "scope.grant.create": { input: NonNullable<operations["scope_grant_create"]["requestBody"]>["content"]["application/json"]; output: operations["scope_grant_create"]["responses"][200]["content"]["application/json"] };
  "scope.grant.end": { input: NonNullable<operations["scope_grant_end"]["requestBody"]>["content"]["application/json"]; output: operations["scope_grant_end"]["responses"][200]["content"]["application/json"] };
  "scope.grant.list": { input: NonNullable<operations["scope_grant_list"]["parameters"]["query"]>; output: operations["scope_grant_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.node.delete": { input: NonNullable<operations["scorecard_node_delete"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_node_delete"]["responses"][200]["content"]["application/json"] };
  "scorecard.node.save": { input: NonNullable<operations["scorecard_node_save"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_node_save"]["responses"][200]["content"]["application/json"] };
  "scorecard.placement.clear": { input: NonNullable<operations["scorecard_placement_clear"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_placement_clear"]["responses"][200]["content"]["application/json"] };
  "scorecard.placement.set": { input: NonNullable<operations["scorecard_placement_set"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_placement_set"]["responses"][200]["content"]["application/json"] };
  "scorecard.profile.list": { input: NonNullable<operations["scorecard_profile_list"]["parameters"]["query"]>; output: operations["scorecard_profile_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.profile.set_metrics": { input: NonNullable<operations["scorecard_profile_set_metrics"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_profile_set_metrics"]["responses"][200]["content"]["application/json"] };
  "scorecard.settings.get": { input: Record<string, never>; output: operations["scorecard_settings_get"]["responses"][200]["content"]["application/json"] };
  "scorecard.settings.set": { input: NonNullable<operations["scorecard_settings_set"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_settings_set"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.activate": { input: NonNullable<operations["scorecard_template_activate"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_template_activate"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.get": { input: NonNullable<operations["scorecard_template_get"]["parameters"]["query"]>; output: operations["scorecard_template_get"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.list": { input: Record<string, never>; output: operations["scorecard_template_list"]["responses"][200]["content"]["application/json"] };
  "scorecard.template.save": { input: NonNullable<operations["scorecard_template_save"]["requestBody"]>["content"]["application/json"]; output: operations["scorecard_template_save"]["responses"][200]["content"]["application/json"] };
  "settings.get": { input: Record<string, never>; output: operations["settings_get"]["responses"][200]["content"]["application/json"] };
  "settings.update": { input: NonNullable<operations["settings_update"]["requestBody"]>["content"]["application/json"]; output: operations["settings_update"]["responses"][200]["content"]["application/json"] };
  "setup.bootstrap": { input: NonNullable<operations["setup_bootstrap"]["requestBody"]>["content"]["application/json"]; output: operations["setup_bootstrap"]["responses"][200]["content"]["application/json"] };
  "setup.status": { input: Record<string, never>; output: operations["setup_status"]["responses"][200]["content"]["application/json"] };
  "subject.get": { input: NonNullable<operations["subject_get"]["parameters"]["query"]>; output: operations["subject_get"]["responses"][200]["content"]["application/json"] };
  "subject.list": { input: NonNullable<operations["subject_list"]["parameters"]["query"]>; output: operations["subject_list"]["responses"][200]["content"]["application/json"] };
  "subject.register": { input: NonNullable<operations["subject_register"]["requestBody"]>["content"]["application/json"]; output: operations["subject_register"]["responses"][200]["content"]["application/json"] };
  "subject.update": { input: NonNullable<operations["subject_update"]["requestBody"]>["content"]["application/json"]; output: operations["subject_update"]["responses"][200]["content"]["application/json"] };
  "system.health": { input: NonNullable<operations["system_health"]["parameters"]["query"]>; output: operations["system_health"]["responses"][200]["content"]["application/json"] };
  "target.batch.list": { input: NonNullable<operations["target_batch_list"]["parameters"]["query"]>; output: operations["target_batch_list"]["responses"][200]["content"]["application/json"] };
  "target.batch.revert": { input: NonNullable<operations["target_batch_revert"]["requestBody"]>["content"]["application/json"]; output: operations["target_batch_revert"]["responses"][200]["content"]["application/json"] };
  "target.copy_forward": { input: NonNullable<operations["target_copy_forward"]["requestBody"]>["content"]["application/json"]; output: operations["target_copy_forward"]["responses"][200]["content"]["application/json"] };
  "target.coverage": { input: NonNullable<operations["target_coverage"]["parameters"]["query"]>; output: operations["target_coverage"]["responses"][200]["content"]["application/json"] };
  "target.draft.discard": { input: NonNullable<operations["target_draft_discard"]["requestBody"]>["content"]["application/json"]; output: operations["target_draft_discard"]["responses"][200]["content"]["application/json"] };
  "target.get": { input: NonNullable<operations["target_get"]["parameters"]["query"]>; output: operations["target_get"]["responses"][200]["content"]["application/json"] };
  "target.list": { input: NonNullable<operations["target_list"]["parameters"]["query"]>; output: operations["target_list"]["responses"][200]["content"]["application/json"] };
  "target.publish": { input: NonNullable<operations["target_publish"]["requestBody"]>["content"]["application/json"]; output: operations["target_publish"]["responses"][200]["content"]["application/json"] };
  "target.upload": { input: NonNullable<operations["target_upload"]["requestBody"]>["content"]["application/json"]; output: operations["target_upload"]["responses"][200]["content"]["application/json"] };
  "user.disable": { input: NonNullable<operations["user_disable"]["requestBody"]>["content"]["application/json"]; output: operations["user_disable"]["responses"][200]["content"]["application/json"] };
  "user.enable": { input: NonNullable<operations["user_enable"]["requestBody"]>["content"]["application/json"]; output: operations["user_enable"]["responses"][200]["content"]["application/json"] };
  "user.get": { input: NonNullable<operations["user_get"]["parameters"]["query"]>; output: operations["user_get"]["responses"][200]["content"]["application/json"] };
  "user.invite": { input: NonNullable<operations["user_invite"]["requestBody"]>["content"]["application/json"]; output: operations["user_invite"]["responses"][200]["content"]["application/json"] };
  "user.invite.resend": { input: NonNullable<operations["user_invite_resend"]["requestBody"]>["content"]["application/json"]; output: operations["user_invite_resend"]["responses"][200]["content"]["application/json"] };
  "user.list": { input: NonNullable<operations["user_list"]["parameters"]["query"]>; output: operations["user_list"]["responses"][200]["content"]["application/json"] };
  "user.reassign": { input: NonNullable<operations["user_reassign"]["requestBody"]>["content"]["application/json"]; output: operations["user_reassign"]["responses"][200]["content"]["application/json"] };
  "user.update": { input: NonNullable<operations["user_update"]["requestBody"]>["content"]["application/json"]; output: operations["user_update"]["responses"][200]["content"]["application/json"] };
  "visibility.list": { input: NonNullable<operations["visibility_list"]["parameters"]["query"]>; output: operations["visibility_list"]["responses"][200]["content"]["application/json"] };
  "visibility.rebuild": { input: NonNullable<operations["visibility_rebuild"]["requestBody"]>["content"]["application/json"]; output: operations["visibility_rebuild"]["responses"][200]["content"]["application/json"] };
}

export type ActionName = keyof Actions;
export type Input<N extends ActionName> = Actions[N]["input"];
export type Output<N extends ActionName> = Actions[N]["output"];
