# Generated by Django 5.2.17 on 2026-10-04 21:45

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import kpigo.platform.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("platform", "0003_extensions")]

    operations = [
        migrations.CreateModel(
            name="CalendarDay",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "day_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("date", models.DateField()),
                ("is_working_day", models.BooleanField()),
                ("holiday_name", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "calendar_day",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "date", "region_code"),
                        name="calendar_day_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceCycle",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "cycle_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("name", models.TextField()),
                ("start_month", models.SmallIntegerField()),
                ("end_month", models.SmallIntegerField()),
                ("status", models.TextField(db_default="active")),
            ],
            options={
                "db_table": "performance_cycle",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "name"), name="performance_cycle_name_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_month__gte", 1),
                            ("start_month__lte", 12),
                            ("end_month__gte", 1),
                            ("end_month__lte", 12),
                        ),
                        name="performance_cycle_months_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "inactive"])),
                        name="performance_cycle_status_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PeriodDeadline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "feed_id",
                        "period_key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("feed_id", models.UUIDField()),
                ("period_key", models.CharField(max_length=6)),
                ("due_at", models.DateTimeField()),
            ],
            options={
                "db_table": "period_deadline",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="period_deadline_period_key_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PeriodStatus",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "product",
                        "period_key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField()),
                ("period_key", models.CharField(max_length=6)),
                ("status", models.TextField(db_default="open")),
                ("closed_at", models.DateTimeField(null=True)),
                ("closed_by", models.BigIntegerField(null=True)),
                ("snapshot_version", models.IntegerField(db_default=0)),
                ("auto_close_at", models.DateTimeField(null=True)),
                ("grace_until", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "period_status",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="period_status_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["open", "closing", "closed", "restating"])
                        ),
                        name="period_status_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="period_status_period_key_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CycleBinding",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "binding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="periods.performancecycle",
                    ),
                ),
            ],
            options={
                "db_table": "cycle_binding",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "product__in",
                                [
                                    "scorecards",
                                    "agent_sales",
                                    "agent_service",
                                    "executive",
                                    "campaign",
                                ],
                            )
                        ),
                        name="cycle_binding_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="cycle_binding_range_valid",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            ("org_id", "="),
                            ("product", "="),
                            (
                                kpigo.platform.db.DateRange("effective_from", "effective_to"),
                                "&&",
                            ),
                        ],
                        name="cycle_binding_no_overlap",
                    ),
                ],
            },
        ),
    ]
