# Generated by Django 5.2.17 on 2026-10-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("periods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodstatus",
            name="status_reason",
            field=models.TextField(null=True),
        ),
    ]
