// Writes src/api/actions.ts from openapi.json: each registered action's route and
// its input and output types, keyed by the action name. Run by `npm run gen:api`.
import { readFileSync, writeFileSync } from "node:fs";

const spec = JSON.parse(readFileSync(new URL("../openapi.json", import.meta.url), "utf8"));
const rows = [];
for (const [path, item] of Object.entries(spec.paths)) {
  for (const [method, op] of Object.entries(item)) {
    const name = op["x-kpigo-action"];
    if (!name) throw new Error(`${path}: no x-kpigo-action`);
    const content = op.requestBody?.content ?? {};
    // Form posts come from an identity provider, never from this app.
    if (Object.keys(content).length && !content["application/json"]) continue;
    const params = op.parameters ?? [];
    const parts = [];
    const ref = `operations["${op.operationId}"]`;
    if (content["application/json"]) {
      parts.push(`NonNullable<${ref}["requestBody"]>["content"]["application/json"]`);
    }
    if (params.some((p) => p.in === "query")) parts.push(`NonNullable<${ref}["parameters"]["query"]>`);
    if (params.some((p) => p.in === "path")) parts.push(`${ref}["parameters"]["path"]`);
    rows.push({
      name,
      method: method.toUpperCase(),
      path,
      pathParams: params.filter((p) => p.in === "path").map((p) => p.name),
      // Public actions (sign-in, first run) declare no security requirement.
      public: !(op.security ?? spec.security ?? []).length,
      input: parts.length ? parts.join(" & ") : "Record<string, never>",
      output: `${ref}["responses"][200]["content"]["application/json"]`,
    });
  }
}
rows.sort((a, b) => a.name.localeCompare(b.name));

const out = [
  "// Generated by scripts/gen-actions.mjs from openapi.json. Do not edit.",
  'import type { operations } from "./schema";',
  "",
  "export const ROUTES = {",
  ...rows.map(
    (r) =>
      `  ${JSON.stringify(r.name)}: { method: ${JSON.stringify(r.method)}, path: ${JSON.stringify(r.path)}, pathParams: ${JSON.stringify(r.pathParams)}, public: ${r.public} },`,
  ),
  "} as const;",
  "",
  "export interface Actions {",
  ...rows.map((r) => `  ${JSON.stringify(r.name)}: { input: ${r.input}; output: ${r.output} };`),
  "}",
  "",
  "export type ActionName = keyof Actions;",
  'export type Input<N extends ActionName> = Actions[N]["input"];',
  'export type Output<N extends ActionName> = Actions[N]["output"];',
  "",
];
writeFileSync(new URL("../src/api/actions.ts", import.meta.url), out.join("\n"));
console.log(`actions.ts: ${rows.length} actions`);
