# Generated by Django 5.2.17 on 2026-10-04 21:45

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0003_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("code", models.CharField(max_length=3)),
                ("name", models.TextField()),
                ("minor_units", models.SmallIntegerField(db_default=2)),
                ("is_active", models.BooleanField(db_default=True)),
            ],
            options={
                "db_table": "currency",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^[A-Z]{3}$")),
                        name="currency_code_iso",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minor_units__gte", 0), ("minor_units__lte", 4)),
                        name="currency_minor_units_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "from_currency",
                        "to_currency",
                        "period_key",
                        "rate_type",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(max_length=3)),
                ("period_key", models.CharField(max_length=6)),
                ("rate_type", models.TextField()),
                ("rate", models.DecimalField(decimal_places=10, max_digits=24)),
            ],
            options={
                "db_table": "fx_rate",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rate_type__in", ["average", "closing", "budget"])),
                        name="fx_rate_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate__gt", 0)), name="fx_rate_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_currency", models.F("to_currency")), _negated=True
                        ),
                        name="fx_rate_distinct_currencies",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="fx_rate_period_key_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrgSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField(primary_key=True, serialize=False)),
                ("reporting_currency", models.CharField(max_length=3, null=True)),
                ("reporting_timezone", models.TextField(db_default="UTC")),
                ("business_day_cutoff", models.TimeField(null=True)),
                ("config_version", models.BigIntegerField(db_default=0)),
            ],
            options={
                "db_table": "org_settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("config_version__gte", 0)),
                        name="org_settings_version_positive",
                    )
                ],
            },
        ),
    ]
