# Generated by Django 5.2.17 on 2026-10-04 23:13

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0004_org_settings_currency_fx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "approval_class",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("approval_class", models.TextField()),
                ("enabled", models.BooleanField(db_default=False)),
            ],
            options={
                "db_table": "approval_policy",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "approval_class__in",
                                [
                                    "metric_change",
                                    "hierarchy_change",
                                    "calendar_change",
                                    "period_close",
                                    "config_change",
                                    "access_change",
                                ],
                            )
                        ),
                        name="approval_policy_class_valid",
                    )
                ],
            },
        ),
    ]
