# Generated by Django 5.2.17 on 2026-10-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0006_approval_classes_r1"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="approvalpolicy",
            name="approval_policy_class_valid",
        ),
        migrations.AddConstraint(
            model_name="approvalpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "approval_class__in",
                        [
                            "metric_change",
                            "hierarchy_change",
                            "calendar_change",
                            "period_close",
                            "config_change",
                            "access_change",
                            "target_publish",
                            "manual_input",
                            "budget",
                        ],
                    )
                ),
                name="approval_policy_class_valid",
            ),
        ),
    ]
