# Generated by Django 5.2.17 on 2026-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0007_approval_class_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgsettings",
            name="attribution_rule",
            field=models.TextField(db_default="last_touch"),
        ),
        migrations.AddConstraint(
            model_name="orgsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "attribution_rule__in",
                        ("last_touch", "first_touch", "priority", "split_even"),
                    )
                ),
                name="org_settings_attribution_rule_valid",
            ),
        ),
    ]
