# Generated by Django 5.2.17 on 2026-10-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0008_org_attribution_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgsettings",
            name="campaign_value_basis",
            field=models.TextField(db_default="incremental"),
        ),
        migrations.AddField(
            model_name="orgsettings",
            name="value_basis_changed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="orgsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("campaign_value_basis__in", ("incremental", "gross"))),
                name="org_settings_value_basis_valid",
            ),
        ),
    ]
