# Generated by Django 5.2.17 on 2026-10-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0009_campaign_value_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgsettings",
            name="winback_retention_days",
            field=models.SmallIntegerField(db_default=90),
        ),
        migrations.AddConstraint(
            model_name="orgsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("winback_retention_days__gte", 1),
                    ("winback_retention_days__lte", 730),
                ),
                name="org_settings_winback_retention_valid",
            ),
        ),
    ]
