# Generated by Django 5.2.17 on 2026-10-07 13:04

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0011_approval_class_widget_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "backup_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("kind", models.TextField(db_default="manual")),
                ("outcome", models.TextField()),
                ("product_version", models.TextField()),
                ("config_version", models.BigIntegerField()),
                ("artefact_path", models.TextField()),
                ("sha256", models.TextField(blank=True, default="")),
                ("size_bytes", models.BigIntegerField(db_default=0)),
                ("detail", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "backup_run",
                "indexes": [
                    models.Index(fields=["org_id", "-created_at"], name="backup_run_org_time")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["scheduled", "manual", "pre_upgrade"])),
                        name="backup_run_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outcome__in", ["ok", "failed"])),
                        name="backup_run_outcome_valid",
                    ),
                ],
            },
        ),
    ]
