# Generated by Django 5.2.17 on 2026-10-07 13:49

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0012_backuprun"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "version_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("from_version", models.TextField()),
                ("to_version", models.TextField()),
                ("outcome", models.TextField()),
                ("key_id", models.TextField(blank=True, default="")),
                ("backup_id", models.UUIDField(null=True)),
                ("detail", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "version_history",
                "indexes": [
                    models.Index(
                        fields=["org_id", "-created_at"],
                        name="version_history_org_time",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("outcome__in", ["authorised", "failed"])),
                        name="version_history_outcome_valid",
                    )
                ],
            },
        ),
    ]
