# Generated by Django 5.2.17 on 2026-10-07 14:50

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0013_versionhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("recipient_id", models.UUIDField()),
                ("category", models.TextField()),
                ("level", models.TextField(db_default="info")),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                ("link", models.TextField(blank=True, default="")),
                ("subject_ref", models.TextField(blank=True, default="")),
                ("read_at", models.DateTimeField(null=True)),
                ("emailed_at", models.DateTimeField(null=True)),
                ("digest", models.BooleanField(db_default=False)),
            ],
            options={
                "db_table": "notification",
                "indexes": [
                    models.Index(
                        fields=["org_id", "recipient_id", "-created_at"],
                        name="notification_inbox",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "category__in",
                                [
                                    "scorecard_ready",
                                    "grade_change",
                                    "behind_pace",
                                    "feed_missed",
                                    "load_quarantined",
                                    "query_raised",
                                    "query_resolved",
                                    "coverage_incomplete",
                                    "input_due",
                                    "input_overdue",
                                    "escalation",
                                    "digest",
                                    "system",
                                ],
                            )
                        ),
                        name="notification_category_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("level__in", ["info", "warning", "critical"])),
                        name="notification_level_valid",
                    ),
                ],
            },
        ),
    ]
