# Generated by Django 5.2.17 on 2026-10-07 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0014_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoArtifact",
            fields=[
                (
                    "demo_artifact_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("batch_id", models.UUIDField()),
                ("model_label", models.TextField()),
                ("object_pk", models.TextField()),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "demo_artifact",
                "indexes": [
                    models.Index(fields=["org_id", "batch_id"], name="demo_artifact_batch")
                ],
            },
        ),
    ]
