# Generated by Django 5.2.17 on 2026-10-07 18:42

import django.contrib.postgres.fields
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0015_demoartifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "endpoint_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("name", models.TextField()),
                ("url", models.TextField()),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("min_level", models.TextField(db_default="info")),
                ("secret_ref", models.UUIDField(null=True)),
                ("status", models.TextField(db_default="active")),
                ("last_delivery_at", models.DateTimeField(null=True)),
                ("last_status", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "webhook_endpoint",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "name"), name="webhook_endpoint_name_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_level__in", ["info", "warning", "critical"])),
                        name="webhook_endpoint_level_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "disabled"])),
                        name="webhook_endpoint_status_valid",
                    ),
                ],
            },
        ),
    ]
