# Generated by Django 5.2.17 on 2026-10-08 14:09

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0016_webhookendpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportDraft",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "import_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("filename", models.TextField()),
                ("content_hash", models.TextField()),
                ("kind", models.TextField()),
                ("status", models.TextField(db_default="drafted")),
                ("proposals", models.JSONField()),
                ("summary", models.JSONField()),
                ("applied", models.JSONField(null=True)),
                ("applied_at", models.DateTimeField(null=True)),
                ("applied_by", models.BigIntegerField(null=True)),
            ],
            options={
                "db_table": "import_draft",
                "indexes": [
                    models.Index(fields=["org_id", "-created_at"], name="import_draft_org_time")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["scorecard", "roster", "unknown"])),
                        name="import_draft_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["drafted", "applied", "discarded"])),
                        name="import_draft_status_valid",
                    ),
                ],
            },
        ),
    ]
