# Generated by Django 5.2.17 on 2026-10-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0017_importdraft"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="importdraft",
            name="import_draft_kind_valid",
        ),
        migrations.AddConstraint(
            model_name="importdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["scorecard", "roster", "powerbi", "unknown"])),
                name="import_draft_kind_valid",
            ),
        ),
    ]
