# Generated by Django 5.2.17 on 2026-10-05 23:08

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WidgetDefinition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "widget_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("widget_key", models.TextField()),
                ("version", models.IntegerField()),
                ("is_current", models.BooleanField(db_default=True)),
                ("state", models.TextField()),
                ("title", models.TextField(db_default="")),
                ("widget_type", models.TextField(null=True)),
                (
                    "definition",
                    models.JSONField(db_default=models.Value({}, output_field=models.JSONField())),
                ),
                ("change", models.TextField()),
                ("approval_request_id", models.UUIDField(null=True)),
                ("first_detected_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "widget_definition",
                "indexes": [
                    models.Index(fields=["org_id", "state"], name="widget_definition_state")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "widget_key", "version"),
                        name="widget_definition_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("org_id", "widget_key"),
                        name="widget_definition_one_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["available", "placed", "removed"])),
                        name="widget_definition_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "change__in",
                                [
                                    "detected",
                                    "declared",
                                    "placed",
                                    "updated",
                                    "type_changed",
                                    "thresholds_changed",
                                    "removed",
                                ],
                            )
                        ),
                        name="widget_definition_change_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("widget_type__isnull", True),
                            (
                                "widget_type__in",
                                [
                                    "kpi_card",
                                    "bullet",
                                    "gauge",
                                    "bar",
                                    "line",
                                    "pie",
                                    "ranked_list",
                                    "table",
                                    "funnel",
                                ],
                            ),
                            _connector="OR",
                        ),
                        name="widget_definition_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state", "available"),
                            ("widget_type__isnull", False),
                            _connector="OR",
                        ),
                        name="widget_definition_typed_unless_available",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("widget_key__regex", "^[a-z][a-z0-9_]{0,63}$")),
                        name="widget_definition_key_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="widget_definition_version_positive",
                    ),
                ],
            },
        ),
    ]
