# Generated by Django 5.2.17 on 2026-10-06 08:55

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("executive", "0001_initial"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutiveManualInput",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "input_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("metric_code", models.TextField()),
                ("dimension_type", models.TextField(db_default="")),
                ("member_code", models.TextField(db_default="")),
                ("period_key", models.CharField(max_length=6)),
                ("value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency_code", models.CharField(max_length=3, null=True)),
                ("note", models.TextField(db_default="")),
                ("change", models.TextField(db_default="entered")),
                ("submitted_by", models.BigIntegerField(null=True)),
                ("submitted_at", models.DateTimeField()),
                ("approval_request_id", models.UUIDField(null=True)),
                ("version", models.IntegerField(db_default=1)),
                ("is_current", models.BooleanField(db_default=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "executive_manual_input",
                "indexes": [
                    models.Index(
                        fields=["org_id", "metric_code", "period_key"],
                        name="executive_input_metric_period",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("change__in", ["entered", "restated"])),
                        name="executive_manual_input_change_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="executive_manual_input_period_key_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("dimension_type", ""), ("member_code", "")),
                            models.Q(
                                models.Q(("dimension_type", ""), _negated=True),
                                models.Q(("member_code", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="executive_manual_input_whole_dimension",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="executive_manual_input_version_positive",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "org_id",
                            "metric_code",
                            "dimension_type",
                            "member_code",
                            "period_key",
                            "version",
                        ),
                        name="executive_manual_input_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=(
                            "org_id",
                            "metric_code",
                            "dimension_type",
                            "member_code",
                            "period_key",
                        ),
                        name="executive_manual_input_one_current",
                    ),
                ],
            },
        ),
    ]
