# Generated by Django 5.2.17 on 2026-10-06 10:55

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_user_preference"),
        ("executive", "0002_executivemanualinput"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutiveSavedView",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "view_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("name", models.TextField()),
                ("state", models.JSONField()),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_views",
                        to="access.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "executive_saved_view",
                "indexes": [
                    models.Index(
                        fields=["org_id", "app_user"], name="executive_view_owner"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app_user", "name"),
                        name="executive_saved_view_name_unique",
                    )
                ],
            },
        ),
    ]
