# Generated by Django 5.2.17 on 2026-10-08 21:44

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantBudget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField(primary_key=True, serialize=False)),
                ("monthly_tokens", models.BigIntegerField(null=True)),
                ("user_daily_tokens", models.BigIntegerField(null=True)),
            ],
            options={
                "db_table": "assistant_budget",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("monthly_tokens__isnull", True),
                            ("monthly_tokens__gte", 0),
                            _connector="OR",
                        ),
                        name="assistant_budget_monthly_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("user_daily_tokens__isnull", True),
                            ("user_daily_tokens__gte", 0),
                            _connector="OR",
                        ),
                        name="assistant_budget_daily_nonneg",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "conversation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("user_id", models.BigIntegerField()),
                ("title", models.TextField()),
            ],
            options={
                "db_table": "assistant_conversation",
                "indexes": [
                    models.Index(
                        fields=["org_id", "user_id", "-updated_at"],
                        name="assistant_conv_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssistantUsage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "usage_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("user_id", models.BigIntegerField(null=True)),
                ("conversation_id", models.UUIDField(null=True)),
                ("provider", models.TextField()),
                ("model", models.TextField()),
                ("input_tokens", models.IntegerField(db_default=0)),
                ("output_tokens", models.IntegerField(db_default=0)),
            ],
            options={
                "db_table": "assistant_usage",
                "indexes": [
                    models.Index(
                        fields=["org_id", "-created_at"],
                        name="assistant_usage_org_time",
                    ),
                    models.Index(
                        fields=["org_id", "user_id", "-created_at"],
                        name="assistant_usage_user",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("seq", models.IntegerField()),
                ("role", models.TextField()),
                ("content", models.TextField(db_default="")),
                ("tool_calls", models.JSONField(null=True)),
                ("tool_call_id", models.TextField(db_default="")),
                ("action_name", models.TextField(db_default="")),
                ("params", models.JSONField(null=True)),
                ("outcome", models.TextField(null=True)),
                ("result", models.JSONField(null=True)),
                ("approval_request_id", models.UUIDField(null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        db_column="conversation_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.assistantconversation",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_message",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["user", "assistant", "tool"])),
                        name="assistant_message_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outcome__isnull", True),
                            ("outcome__in", ("ok", "proposed", "refused", "error")),
                            _connector="OR",
                        ),
                        name="assistant_message_outcome_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("conversation", "seq"), name="assistant_message_seq"
                    ),
                ],
            },
        ),
    ]
