# Generated by Django 5.2.17 on 2026-10-04 21:45

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import kpigo.platform.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("periods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "dimension_type",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("dimension_type", models.TextField()),
                ("display_name", models.TextField()),
                ("is_custom", models.BooleanField(db_default=False)),
                ("sort_order", models.IntegerField(db_default=0)),
            ],
            options={
                "db_table": "dim_dimension",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("dimension_type__regex", "^[a-z][a-z0-9_]*$")),
                        name="dim_dimension_type_format",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DimMember",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "dimension_type",
                        "member_code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("dimension_type", models.TextField()),
                ("member_code", models.TextField()),
                ("member_name", models.TextField()),
                ("parent_code", models.TextField(null=True)),
                ("sort_order", models.IntegerField(db_default=0)),
                ("status", models.TextField(db_default="active")),
            ],
            options={
                "db_table": "dim_member",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "inactive"])),
                        name="dim_member_status_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RollupPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "policy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("scope_type", models.TextField()),
                ("scope_code", models.TextField()),
                ("relationship_type", models.TextField()),
                ("counts_toward_rollup", models.BooleanField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
            ],
            options={
                "db_table": "rollup_policy",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("scope_type__in", ["role", "profile"])),
                        name="rollup_policy_scope_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("relationship_type__in", ["solid", "dotted"])),
                        name="rollup_policy_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="rollup_policy_range_valid",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            ("org_id", "="),
                            ("scope_type", "="),
                            ("scope_code", "="),
                            ("relationship_type", "="),
                            (
                                kpigo.platform.db.DateRange("effective_from", "effective_to"),
                                "&&",
                            ),
                        ],
                        name="rollup_policy_no_overlap",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "subject_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("staff_no", models.TextField()),
                ("full_name", models.TextField()),
                ("email", kpigo.platform.db.CITextField()),
                ("status", models.TextField(db_default="active")),
                ("joined_at", models.DateField(null=True)),
                ("left_at", models.DateField(null=True)),
            ],
            options={
                "db_table": "subject",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "email"), name="subject_email_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("org_id", "staff_no"), name="subject_staff_no_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "inactive"])),
                        name="subject_status_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VisibilityClosure",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "period_key",
                        "viewer_subject_id",
                        "visible_subject_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("period_key", models.CharField(max_length=6)),
                ("viewer_subject_id", models.UUIDField()),
                ("visible_subject_id", models.UUIDField()),
                ("via", models.TextField()),
                ("counts_toward_rollup", models.BooleanField()),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
            ],
            options={
                "db_table": "visibility_closure",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("via__in", ["self", "solid", "dotted"])),
                        name="visibility_closure_via_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportingEdge",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "edge_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("relationship_type", models.TextField()),
                ("counts_toward_rollup", models.BooleanField(db_default=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_edges",
                        to="hierarchy.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manager_edges",
                        to="hierarchy.subject",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_edge",
                "indexes": [
                    models.Index(fields=["org_id", "manager"], name="reporting_edge_manager")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("relationship_type__in", ["solid", "dotted"])),
                        name="reporting_edge_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("subject", models.F("manager")), _negated=True),
                        name="reporting_edge_not_self",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="reporting_edge_range_valid",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            ("subject", "="),
                            ("manager", "="),
                            (
                                kpigo.platform.db.DateRange("effective_from", "effective_to"),
                                "&&",
                            ),
                        ],
                        name="reporting_edge_no_overlap",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("relationship_type", "solid")),
                        expressions=[
                            ("subject", "="),
                            (
                                kpigo.platform.db.DateRange("effective_from", "effective_to"),
                                "&&",
                            ),
                        ],
                        name="reporting_edge_one_solid_manager",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("role_code", models.TextField()),
                ("profile_code", models.TextField()),
                ("portfolio_code", models.TextField(null=True)),
                ("staff_ref", models.TextField(null=True)),
                ("branch_code", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
                ("segment_code", models.TextField(null=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="periods.performancecycle",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="hierarchy.subject",
                    ),
                ),
            ],
            options={
                "db_table": "assignment",
                "indexes": [
                    models.Index(fields=["org_id", "profile_code"], name="assignment_profile")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="assignment_range_valid",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            ("subject", "="),
                            (
                                kpigo.platform.db.DateRange("effective_from", "effective_to"),
                                "&&",
                            ),
                        ],
                        name="assignment_no_overlap",
                    ),
                ],
            },
        ),
    ]
