# Generated by Django 5.2.17 on 2026-10-04 22:28

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "group_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("code", models.TextField()),
                ("display_name", models.TextField()),
                ("sort_order", models.IntegerField(db_default=0)),
                ("module", models.TextField(db_default="agent_performance")),
                ("status", models.TextField(db_default="active")),
            ],
            options={
                "db_table": "product_group",
            },
        ),
        migrations.CreateModel(
            name="ProductLine",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "line_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("code", models.TextField()),
                ("display_name", models.TextField()),
                ("sort_order", models.IntegerField(db_default=0)),
                ("module", models.TextField(db_default="agent_performance")),
                ("status", models.TextField(db_default="available")),
                ("source_member_code", models.TextField(null=True)),
                ("first_detected_at", models.DateTimeField(null=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
            ],
            options={
                "db_table": "product_line",
            },
        ),
        migrations.RemoveConstraint(
            model_name="dimmember",
            name="dim_member_status_valid",
        ),
        migrations.AddField(
            model_name="dimmember",
            name="first_detected_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="dimmember",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["available", "active", "inactive"])),
                name="dim_member_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="productgroup",
            constraint=models.UniqueConstraint(
                fields=("org_id", "code"), name="product_group_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "retired"])),
                name="product_group_status_valid",
            ),
        ),
        migrations.AddField(
            model_name="productline",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="hierarchy.productgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="productline",
            constraint=models.UniqueConstraint(
                fields=("org_id", "code"), name="product_line_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productline",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["available", "active", "retired"])),
                name="product_line_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="productline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "available"), ("group__isnull", False), _connector="OR"
                ),
                name="product_line_grouped_unless_available",
            ),
        ),
        migrations.AddConstraint(
            model_name="productline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="product_line_range_valid",
            ),
        ),
    ]
