# Generated by Django 5.2.17 on 2026-10-05 12:13

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import kpigo.platform.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0002_product_lines_available_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLineGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "membership_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groupings",
                        to="hierarchy.productline",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.productgroup",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
            ],
            options={
                "db_table": "product_line_group",
            },
        ),
        migrations.AddField(
            model_name="productline",
            name="rag_amber",
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="productline",
            name="rag_green",
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name="productgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "module__in",
                        ["agent_performance", "agent_sales", "agent_service"],
                    )
                ),
                name="product_group_module_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="productline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "module__in",
                        ["agent_performance", "agent_sales", "agent_service"],
                    )
                ),
                name="product_line_module_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="productline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("rag_green__isnull", True), ("rag_amber__isnull", True)),
                    models.Q(("rag_amber__gt", 0), ("rag_green__gte", models.F("rag_amber"))),
                    _connector="OR",
                ),
                name="product_line_rag_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="productlinegroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="product_line_group_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="productlinegroup",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("line", "="),
                    (
                        kpigo.platform.db.DateRange("effective_from", "effective_to"),
                        "&&",
                    ),
                ],
                name="product_line_group_no_overlap",
            ),
        ),
    ]
