# Generated by Django 5.2.17 on 2026-10-04 22:28

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hierarchy", "0002_product_lines_available_members"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialSecret",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "secret_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("ciphertext", models.TextField()),
            ],
            options={
                "db_table": "credential_secret",
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "connection_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("name", models.TextField()),
                ("driver", models.TextField()),
                ("host", models.TextField()),
                ("port", models.IntegerField()),
                ("database", models.TextField()),
                ("username", models.TextField()),
                ("secret_ref", models.UUIDField(null=True)),
                ("options", models.JSONField(default=dict)),
                ("status", models.TextField(db_default="active")),
            ],
            options={
                "db_table": "connection",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "name"), name="connection_name_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("driver__in", ["postgres", "sqlserver", "oracle", "mysql"])
                        ),
                        name="connection_driver_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "disabled"])),
                        name="connection_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("port__gt", 0), ("port__lt", 65536)),
                        name="connection_port_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "feed_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("name", models.TextField()),
                ("template_name", models.TextField()),
                ("mode", models.TextField()),
                ("source_object", models.TextField(null=True)),
                ("drop_path", models.TextField(null=True)),
                ("cadence_cron", models.TextField(null=True)),
                ("owner_user_id", models.BigIntegerField(null=True)),
                ("deadline_offset_hours", models.IntegerField(null=True)),
                ("expected_row_min", models.IntegerField(null=True)),
                ("expected_row_max", models.IntegerField(null=True)),
                ("volume_warn_pct", models.IntegerField(db_default=25)),
                ("volume_reject_pct", models.IntegerField(db_default=75)),
                ("freshness_tolerance_hours", models.IntegerField(null=True)),
                ("status", models.TextField(db_default="active")),
                ("last_run_id", models.UUIDField(null=True)),
                ("last_success_at", models.DateTimeField(null=True)),
                ("last_scheduled_at", models.DateTimeField(null=True)),
                ("freshness_state", models.TextField(db_default="never_loaded")),
                ("stale_reason", models.TextField(null=True)),
                ("stale_since", models.DateTimeField(null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeds",
                        to="ingestion.connection",
                    ),
                ),
            ],
            options={
                "db_table": "feed",
            },
        ),
        migrations.CreateModel(
            name="FeedRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("trigger", models.TextField()),
                ("is_dry_run", models.BooleanField()),
                ("restatement", models.BooleanField(db_default=False)),
                ("state", models.TextField(db_default="running")),
                ("outcome", models.TextField(null=True)),
                ("source_name", models.TextField(db_default="")),
                ("rows_read", models.IntegerField(db_default=0)),
                ("rows_accepted", models.IntegerField(db_default=0)),
                ("rows_rejected", models.IntegerField(db_default=0)),
                ("warnings", models.IntegerField(db_default=0)),
                ("content_hash", models.TextField(null=True)),
                ("periods", models.JSONField(default=list)),
                ("gate_summary", models.JSONField(default=dict)),
                ("diff_summary", models.JSONField(null=True)),
                ("error_text", models.TextField(null=True)),
                ("supersedes_run_id", models.UUIDField(null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="ingestion.feed",
                    ),
                ),
            ],
            options={
                "db_table": "feed_run",
            },
        ),
        migrations.CreateModel(
            name="FeedRejection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "seq",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.IntegerField()),
                ("row_no", models.IntegerField(null=True)),
                ("column_name", models.TextField(null=True)),
                ("gate", models.TextField()),
                ("rule", models.TextField()),
                ("severity", models.TextField()),
                ("value", models.TextField(null=True)),
                ("message", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejections",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "feed_rejection",
            },
        ),
        migrations.CreateModel(
            name="TmplActualDaily",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_code", models.TextField(null=True)),
                ("subject_ref", models.TextField(null=True)),
                ("activity_date", models.TextField(null=True)),
                ("product_line_code", models.TextField(null=True)),
                ("actual_value", models.TextField(null=True)),
                ("currency_code", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_actual_daily",
            },
        ),
        migrations.CreateModel(
            name="TmplActualDimensional",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_code", models.TextField(null=True)),
                ("dimension_type", models.TextField(null=True)),
                ("member_code", models.TextField(null=True)),
                ("period_key", models.TextField(null=True)),
                ("actual_value", models.TextField(null=True)),
                ("currency_code", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_actual_dimensional",
            },
        ),
        migrations.CreateModel(
            name="TmplActualMonthly",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_code", models.TextField(null=True)),
                ("subject_ref", models.TextField(null=True)),
                ("period_key", models.TextField(null=True)),
                ("actual_value", models.TextField(null=True)),
                ("currency_code", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_actual_monthly",
            },
        ),
        migrations.CreateModel(
            name="TmplAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_no", models.TextField(null=True)),
                ("role_code", models.TextField(null=True)),
                ("profile_code", models.TextField(null=True)),
                ("manager_staff_no", models.TextField(null=True)),
                ("relationship_type", models.TextField(null=True)),
                ("branch_code", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
                ("segment_code", models.TextField(null=True)),
                ("effective_from", models.TextField(null=True)),
                ("effective_to", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_assignment",
            },
        ),
        migrations.CreateModel(
            name="TmplCampaignOutcome",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_ref", models.TextField(null=True)),
                ("metric_code", models.TextField(null=True)),
                ("campaign_code", models.TextField(null=True)),
                ("activity_date", models.TextField(null=True)),
                ("activity_value", models.TextField(null=True)),
                ("currency_code", models.TextField(null=True)),
                ("source_ref", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_campaign_outcome",
            },
        ),
        migrations.CreateModel(
            name="TmplDimension",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dimension_type", models.TextField(null=True)),
                ("member_code", models.TextField(null=True)),
                ("member_name", models.TextField(null=True)),
                ("parent_code", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_dimension",
            },
        ),
        migrations.CreateModel(
            name="TmplSubject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_no", models.TextField(null=True)),
                ("full_name", models.TextField(null=True)),
                ("email", models.TextField(null=True)),
                ("portfolio_code", models.TextField(null=True)),
                ("staff_ref", models.TextField(null=True)),
                ("status", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_subject",
            },
        ),
        migrations.CreateModel(
            name="TmplTarget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_code", models.TextField(null=True)),
                ("scope_type", models.TextField(null=True)),
                ("scope_code", models.TextField(null=True)),
                ("period_key", models.TextField(null=True)),
                ("series_type", models.TextField(null=True)),
                ("target_value", models.TextField(null=True)),
                ("target_type", models.TextField(null=True)),
                ("weight", models.TextField(null=True)),
                ("cap", models.TextField(null=True)),
                ("currency_code", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_target",
            },
        ),
        migrations.CreateModel(
            name="TmplWidgetData",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("widget_key", models.TextField(null=True)),
                ("metric_code", models.TextField(null=True)),
                ("period_key", models.TextField(null=True)),
                ("dimension_type", models.TextField(null=True)),
                ("member_code", models.TextField(null=True)),
                ("series_type", models.TextField(null=True)),
                ("value", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_widget_data",
            },
        ),
        migrations.CreateModel(
            name="FactActualDimensional",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "metric_id",
                        "dimension_type",
                        "member_code",
                        "period_key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("dimension_type", models.TextField()),
                ("member_code", models.TextField()),
                ("period_key", models.CharField(max_length=6)),
                ("actual_value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency_code", models.CharField(max_length=3, null=True)),
                ("run_id", models.UUIDField(null=True)),
                ("loaded_at", models.DateTimeField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "fact_actual_dimensional",
                "indexes": [models.Index(fields=["run_id"], name="fact_dimensional_run")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="fact_actual_dimensional_period_key_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FactActualMonthly",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "metric_id",
                        "subject_id",
                        "period_key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("period_key", models.CharField(max_length=6)),
                ("actual_value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency_code", models.CharField(max_length=3, null=True)),
                ("run_id", models.UUIDField(null=True)),
                ("loaded_at", models.DateTimeField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.assignment",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.subject",
                    ),
                ),
            ],
            options={
                "db_table": "fact_actual_monthly",
                "indexes": [
                    models.Index(
                        fields=["subject", "period_key"],
                        name="fact_monthly_subject_period",
                    ),
                    models.Index(fields=["run_id"], name="fact_monthly_run"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                        name="fact_actual_monthly_period_key_valid",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.UniqueConstraint(fields=("org_id", "name"), name="feed_name_unique"),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "template_name__in",
                        ["actual_monthly", "actual_daily", "actual_dimensional"],
                    )
                ),
                name="feed_template_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["pull", "drop", "upload"])),
                name="feed_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "paused"])),
                name="feed_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(("freshness_state__in", ["never_loaded", "fresh", "stale"])),
                name="feed_freshness_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "pull"), _negated=True),
                    models.Q(("connection__isnull", False), ("source_object__isnull", False)),
                    _connector="OR",
                ),
                name="feed_pull_has_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "drop"), _negated=True),
                    ("drop_path__isnull", False),
                    _connector="OR",
                ),
                name="feed_drop_has_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("volume_warn_pct__gte", 0),
                    ("volume_reject_pct__gte", models.F("volume_warn_pct")),
                ),
                name="feed_volume_thresholds_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="feedrun",
            index=models.Index(fields=["feed", "-started_at"], name="feed_run_recent"),
        ),
        migrations.AddIndex(
            model_name="feedrun",
            index=models.Index(
                condition=models.Q(("is_dry_run", False), ("outcome", "success")),
                fields=["feed", "content_hash"],
                name="feed_run_success_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("trigger__in", ["manual", "schedule", "drop", "upload"])),
                name="feed_run_trigger_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "queued",
                            "running",
                            "validated",
                            "committed",
                            "quarantined",
                            "failed",
                        ],
                    )
                ),
                name="feed_run_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outcome__isnull", True),
                    ("outcome__in", ("success", "quarantined", "failed")),
                    _connector="OR",
                ),
                name="feed_run_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrejection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "gate__in",
                        [
                            "schema",
                            "referential",
                            "grain",
                            "domain",
                            "volume",
                            "period_status",
                        ],
                    )
                ),
                name="feed_rejection_gate_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrejection",
            constraint=models.CheckConstraint(
                condition=models.Q(("severity__in", ["error", "warning"])),
                name="feed_rejection_severity_valid",
            ),
        ),
    ]
