# Generated by Django 5.2.17 on 2026-10-05 10:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_fact_actual_daily"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyArchive",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                ("month", models.DateField(primary_key=True, serialize=False)),
                ("partition_name", models.TextField()),
                ("archive_schema", models.TextField()),
                ("status", models.TextField(db_default="archived")),
                ("daily_rows", models.BigIntegerField()),
                ("rolled_up_rows", models.BigIntegerField()),
                ("mixed_currency_pairs", models.BigIntegerField(db_default=0)),
                ("archived_at", models.DateTimeField()),
                ("restored_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "daily_archive",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["archived", "restored"])),
                        name="daily_archive_status_valid",
                    )
                ],
            },
        ),
    ]
