# Generated by Django 5.2.17 on 2026-10-05 16:28

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0005_mv_product_line_matrix"),
    ]

    operations = [
        migrations.CreateModel(
            name="TmplCampaignContact",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_ref", models.TextField(null=True)),
                ("campaign_code", models.TextField(null=True)),
                ("channel", models.TextField(null=True)),
                ("contact_date", models.TextField(null=True)),
                ("delivered", models.TextField(null=True)),
                ("responded", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_campaign_contact",
            },
        ),
        migrations.CreateModel(
            name="TmplCampaignPopulation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.TextField(null=True)),
                ("segment_code", models.TextField(null=True)),
                ("product_code", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
                ("branch_code", models.TextField(null=True)),
                ("customer_count", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
            ],
            options={
                "db_table": "tmpl_campaign_population",
            },
        ),
        migrations.RemoveConstraint(
            model_name="feed",
            name="feed_template_valid",
        ),
        migrations.AddField(
            model_name="tmplcampaignoutcome",
            name="branch_code",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tmplcampaignoutcome",
            name="product_code",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tmplcampaignoutcome",
            name="region_code",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tmplcampaignoutcome",
            name="segment_code",
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "template_name__in",
                        [
                            "actual_monthly",
                            "actual_daily",
                            "actual_dimensional",
                            "campaign_outcome",
                            "campaign_population",
                            "campaign_contact",
                        ],
                    )
                ),
                name="feed_template_valid",
            ),
        ),
    ]
