# Generated by Django 5.2.17 on 2026-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0006_campaign_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmplcampaigncontact",
            name="holdout",
            field=models.TextField(null=True),
        ),
    ]
