# Generated by Django 5.2.17 on 2026-10-05 18:16

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0007_contact_holdout"),
    ]

    operations = [
        migrations.CreateModel(
            name="TmplCampaignWinback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("org_id", models.UUIDField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.feedrun",
                    ),
                ),
                ("row_no", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "run_id",
                        "row_no",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_ref", models.TextField(null=True)),
                ("campaign_code", models.TextField(null=True)),
                ("qualified_at", models.TextField(null=True)),
                ("winback_flag", models.TextField(null=True)),
                ("account_status", models.TextField(null=True)),
                ("retention_confirmed_at", models.TextField(null=True)),
                ("segment_code", models.TextField(null=True)),
                ("product_code", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
                ("branch_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "tmpl_campaign_winback",
            },
        ),
        migrations.RemoveConstraint(
            model_name="feed",
            name="feed_template_valid",
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "template_name__in",
                        [
                            "actual_monthly",
                            "actual_daily",
                            "actual_dimensional",
                            "campaign_outcome",
                            "campaign_population",
                            "campaign_contact",
                            "campaign_winback",
                        ],
                    )
                ),
                name="feed_template_valid",
            ),
        ),
    ]
