# Generated by Django 5.2.17 on 2026-10-05 23:08

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0008_winback_template"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactWidgetData",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "fact_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("widget_key", models.TextField()),
                ("period_key", models.CharField(max_length=6)),
                ("dimension_type", models.TextField(db_default="")),
                ("member_code", models.TextField(db_default="")),
                ("series_type", models.TextField()),
                ("value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency_code", models.CharField(max_length=3, null=True)),
                ("run_id", models.UUIDField(null=True)),
                ("loaded_at", models.DateTimeField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "fact_widget_data",
            },
        ),
        migrations.RemoveConstraint(
            model_name="feed",
            name="feed_template_valid",
        ),
        migrations.AddField(
            model_name="tmplwidgetdata",
            name="currency_code",
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name="feed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "template_name__in",
                        [
                            "actual_monthly",
                            "actual_daily",
                            "actual_dimensional",
                            "widget_data",
                            "campaign_outcome",
                            "campaign_population",
                            "campaign_contact",
                            "campaign_winback",
                        ],
                    )
                ),
                name="feed_template_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="factwidgetdata",
            index=models.Index(
                fields=["org_id", "widget_key", "period_key"], name="fact_widget_key"
            ),
        ),
        migrations.AddIndex(
            model_name="factwidgetdata",
            index=models.Index(fields=["run_id"], name="fact_widget_run"),
        ),
        migrations.AddConstraint(
            model_name="factwidgetdata",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_key__regex", "^[0-9]{4}(0[1-9]|1[0-2])$")),
                name="fact_widget_data_period_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="factwidgetdata",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "series_type__in",
                        [
                            "actual",
                            "target",
                            "forecast",
                            "budget",
                            "prior",
                            "prior_year",
                        ],
                    )
                ),
                name="fact_widget_data_series_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="factwidgetdata",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("dimension_type", ""), ("member_code", "")),
                    models.Q(
                        models.Q(("dimension_type", ""), _negated=True),
                        models.Q(("member_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="fact_widget_data_whole_dimension",
            ),
        ),
        migrations.AddConstraint(
            model_name="factwidgetdata",
            constraint=models.UniqueConstraint(
                fields=(
                    "org_id",
                    "widget_key",
                    "metric",
                    "period_key",
                    "dimension_type",
                    "member_code",
                    "series_type",
                ),
                name="fact_widget_data_grain",
            ),
        ),
    ]
