# Generated by Django 5.2.17 on 2026-10-05 10:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "product",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField()),
                ("grain", models.TextField(db_default="daily")),
                (
                    "pace_cap",
                    models.DecimalField(db_default=2, decimal_places=3, max_digits=6),
                ),
                (
                    "rag_green",
                    models.DecimalField(db_default=1, decimal_places=3, max_digits=6),
                ),
                (
                    "rag_amber",
                    models.DecimalField(db_default=0.85, decimal_places=3, max_digits=6),
                ),
            ],
            options={
                "db_table": "agent_settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("product__in", ["agent_sales", "agent_service"])),
                        name="agent_settings_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("grain__in", ["daily", "weekly"])),
                        name="agent_settings_grain_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("pace_cap__gte", 1),
                            ("rag_amber__gt", 0),
                            ("rag_green__gte", models.F("rag_amber")),
                        ),
                        name="agent_settings_thresholds_valid",
                    ),
                ],
            },
        ),
    ]
