# Generated by Django 5.2.17 on 2026-10-05 11:34; the foreign keys moved into CreateModel.

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import kpigo.platform.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
        ("hierarchy", "0002_product_lines_available_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentCohort",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "cohort_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField()),
                ("code", models.TextField()),
                ("name", models.TextField()),
                ("status", models.TextField(db_default="active")),
            ],
            options={
                "db_table": "agent_cohort",
            },
        ),
        migrations.CreateModel(
            name="AgentCohortMember",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "member_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="agents.agentcohort",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.subject",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(null=True)),
            ],
            options={
                "db_table": "agent_cohort_member",
            },
        ),
        migrations.AddField(
            model_name="agentsettings",
            name="cohort_type",
            field=models.TextField(db_default="profile"),
        ),
        migrations.AddField(
            model_name="agentsettings",
            name="rank_metric_code",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="agentsettings",
            name="tiebreak_metric_code",
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name="agentsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "cohort_type__in",
                        ["all", "profile", "branch", "region", "cohort"],
                    )
                ),
                name="agent_settings_cohort_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcohort",
            constraint=models.CheckConstraint(
                condition=models.Q(("product__in", ["agent_sales", "agent_service"])),
                name="agent_cohort_product_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcohort",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "retired"])),
                name="agent_cohort_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcohort",
            constraint=models.UniqueConstraint(
                fields=("org_id", "product", "code"), name="agent_cohort_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcohortmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="agent_cohort_member_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcohortmember",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("cohort", "="),
                    ("subject", "="),
                    (
                        kpigo.platform.db.DateRange("effective_from", "effective_to"),
                        "&&",
                    ),
                ],
                name="agent_cohort_member_no_overlap",
            ),
        ),
    ]
