# Generated by Django 5.2.17 on 2026-10-05 13:26

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_leaderboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentVisibilityRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "rule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField()),
                ("applies_to", models.TextField()),
                ("applies_code", models.TextField()),
                ("scope", models.TextField()),
            ],
            options={
                "db_table": "agent_visibility_rule",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("product__in", ["agent_sales", "agent_service"])),
                        name="agent_visibility_rule_product_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("applies_to__in", ["role", "profile"])),
                        name="agent_visibility_rule_applies_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "scope__in",
                                ["all", "subtree", "region", "branch", "self"],
                            )
                        ),
                        name="agent_visibility_rule_scope_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("org_id", "product", "applies_to", "applies_code"),
                        name="agent_visibility_rule_unique",
                    ),
                ],
            },
        ),
    ]
