# Generated by Django 5.2.17 on 2026-10-05 14:21

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "stage_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("product", models.TextField()),
                ("code", models.TextField()),
                ("display_name", models.TextField()),
                ("sort_order", models.IntegerField(db_default=0)),
                ("value_metric_code", models.TextField(null=True)),
                ("count_metric_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "pipeline_stage",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("product__in", ["agent_sales", "agent_service"])),
                        name="pipeline_stage_product_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("org_id", "product", "code"),
                        name="pipeline_stage_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("value_metric_code__isnull", False),
                            ("count_metric_code__isnull", False),
                            _connector="OR",
                        ),
                        name="pipeline_stage_has_metric",
                    ),
                ],
            },
        ),
    ]
