# Generated by Django 5.2.17 on 2026-10-05 15:21

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "campaign_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("code", models.TextField()),
                ("name", models.TextField()),
                ("campaign_type", models.TextField()),
                ("objective", models.TextField()),
                ("product_code", models.TextField(null=True)),
                ("owner_user_id", models.BigIntegerField(null=True)),
                ("description", models.TextField(db_default="")),
                ("priority", models.IntegerField(null=True)),
                ("status", models.TextField(db_default="active")),
                ("closed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "campaign",
                "constraints": [
                    models.UniqueConstraint(fields=("org_id", "code"), name="campaign_code_unique"),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "objective__in",
                                [
                                    "acquisition",
                                    "deposit_growth",
                                    "activation",
                                    "cross_sell",
                                    "attrition_winback",
                                    "collections",
                                    "awareness",
                                ],
                            )
                        ),
                        name="campaign_objective_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "closed"])),
                        name="campaign_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("priority__isnull", True),
                            ("priority__gte", 1),
                            _connector="OR",
                        ),
                        name="campaign_priority_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("event_name", models.TextField()),
                ("sequence_no", models.IntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("attribution_window_days", models.IntegerField()),
                ("budget_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("budget_currency", models.CharField(max_length=3)),
                (
                    "spend_to_date",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "channels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("state", models.TextField(db_default="draft")),
                ("version", models.IntegerField(db_default=1)),
                ("reattribute_from", models.DateField(null=True)),
                ("published_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_event",
            },
        ),
        migrations.CreateModel(
            name="CampaignAudience",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "audience_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("dimension_type", models.TextField()),
                ("member_code", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience",
                        to="campaigns.campaignevent",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_audience",
            },
        ),
        migrations.CreateModel(
            name="CampaignEventVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "version_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("version_no", models.IntegerField()),
                ("change", models.TextField()),
                ("snapshot", models.JSONField()),
                ("approval_request_id", models.UUIDField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="campaigns.campaignevent",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_event_version",
            },
        ),
        migrations.CreateModel(
            name="CampaignObjective",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "objective",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("objective", models.TextField()),
                ("default_window_days", models.IntegerField()),
                (
                    "outcome_metric_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
            ],
            options={
                "db_table": "campaign_objective",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "objective__in",
                                [
                                    "acquisition",
                                    "deposit_growth",
                                    "activation",
                                    "cross_sell",
                                    "attrition_winback",
                                    "collections",
                                    "awareness",
                                ],
                            )
                        ),
                        name="campaign_objective_objective_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("default_window_days__gte", 0)),
                        name="campaign_objective_window_valid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="campaignevent",
            index=models.Index(fields=["org_id", "period_start"], name="campaign_event_start"),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.UniqueConstraint(
                fields=("campaign", "sequence_no"),
                name="campaign_event_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "live", "paused", "closed"])),
                name="campaign_event_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="campaign_event_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("attribution_window_days__gte", 0)),
                name="campaign_event_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("budget_amount__gte", 0)),
                name="campaign_event_budget_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("budget_currency__regex", "^[A-Z]{3}$")),
                name="campaign_event_currency_iso",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "channels__contained_by",
                        [
                            "sms",
                            "email",
                            "call",
                            "ussd",
                            "branch",
                            "app_push",
                            "whatsapp",
                        ],
                    )
                ),
                name="campaign_event_channels_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignaudience",
            index=models.Index(
                fields=["dimension_type", "member_code"],
                name="campaign_audience_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignaudience",
            constraint=models.UniqueConstraint(
                fields=("event", "dimension_type", "member_code"),
                name="campaign_audience_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigneventversion",
            constraint=models.UniqueConstraint(
                fields=("event", "version_no"), name="campaign_event_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigneventversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "change__in",
                        [
                            "created",
                            "updated",
                            "audience",
                            "budget",
                            "published",
                            "paused",
                            "resumed",
                            "closed",
                        ],
                    )
                ),
                name="campaign_event_version_change_valid",
            ),
        ),
    ]
