# Generated by Django 5.2.17 on 2026-10-05 16:28

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignOutcome",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("segment_code", models.TextField(null=True)),
                ("product_code", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
                ("branch_code", models.TextField(null=True)),
                (
                    "outcome_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("customer_ref", models.TextField()),
                ("campaign_code", models.TextField(null=True)),
                ("activity_date", models.DateField()),
                (
                    "activity_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("currency_code", models.CharField(max_length=3, null=True)),
                ("source_ref", models.TextField(null=True)),
                ("run_id", models.UUIDField()),
                ("loaded_at", models.DateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_outcome",
            },
        ),
        migrations.CreateModel(
            name="CampaignAttribution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "outcome_id",
                        "event_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("credited", models.BooleanField()),
                (
                    "attributed_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("share", models.DecimalField(decimal_places=8, max_digits=9)),
                ("rule_applied", models.TextField()),
                ("candidates", models.IntegerField()),
                ("via", models.TextField()),
                ("computed_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="campaigns.campaignevent",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="campaigns.campaignoutcome",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_attribution",
            },
        ),
        migrations.CreateModel(
            name="CampaignPopulation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("segment_code", models.TextField(null=True)),
                ("product_code", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
                ("branch_code", models.TextField(null=True)),
                (
                    "population_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("snapshot_date", models.DateField()),
                ("customer_count", models.BigIntegerField()),
                ("run_id", models.UUIDField()),
                ("loaded_at", models.DateTimeField()),
            ],
            options={
                "db_table": "campaign_population",
                "indexes": [
                    models.Index(
                        fields=["org_id", "snapshot_date"],
                        name="campaign_population_day",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "org_id",
                            "snapshot_date",
                            "segment_code",
                            "product_code",
                            "region_code",
                            "branch_code",
                        ),
                        name="campaign_population_grain",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("customer_count__gte", 0)),
                        name="campaign_population_count_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignContact",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "contact_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("customer_ref", models.TextField()),
                ("channel", models.TextField()),
                ("contact_date", models.DateField()),
                ("delivered", models.BooleanField(null=True)),
                ("responded", models.BooleanField(null=True)),
                ("run_id", models.UUIDField()),
                ("loaded_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="campaigns.campaignevent",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_contact",
                "indexes": [models.Index(fields=["run_id"], name="campaign_contact_run")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "customer_ref", "channel", "contact_date"),
                        name="campaign_contact_grain",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "channel__in",
                                [
                                    "sms",
                                    "email",
                                    "call",
                                    "ussd",
                                    "branch",
                                    "app_push",
                                    "whatsapp",
                                ],
                            )
                        ),
                        name="campaign_contact_channel_valid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="campaignoutcome",
            index=models.Index(fields=["org_id", "activity_date"], name="campaign_outcome_day"),
        ),
        migrations.AddIndex(
            model_name="campaignoutcome",
            index=models.Index(
                fields=["customer_ref", "activity_date"],
                name="campaign_outcome_customer",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignoutcome",
            index=models.Index(
                condition=models.Q(("campaign__isnull", False)),
                fields=["campaign"],
                name="campaign_outcome_tagged",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignoutcome",
            index=models.Index(fields=["run_id"], name="campaign_outcome_run"),
        ),
        migrations.AddConstraint(
            model_name="campaignoutcome",
            constraint=models.UniqueConstraint(
                fields=(
                    "org_id",
                    "customer_ref",
                    "metric",
                    "activity_date",
                    "source_ref",
                ),
                name="campaign_outcome_grain",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignoutcome",
            constraint=models.CheckConstraint(
                condition=models.Q(("activity_value__gte", 0)),
                name="campaign_outcome_value_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignattribution",
            index=models.Index(fields=["event", "credited"], name="campaign_attribution_event"),
        ),
        migrations.AddConstraint(
            model_name="campaignattribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rule_applied__in",
                        [
                            "single",
                            "last_touch",
                            "first_touch",
                            "priority",
                            "split_even",
                        ],
                    )
                ),
                name="campaign_attribution_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignattribution",
            constraint=models.CheckConstraint(
                condition=models.Q(("via__in", ["tag", "criteria"])),
                name="campaign_attribution_via_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignattribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attributed_value__gte", 0), ("share__gte", 0), ("share__lte", 1)
                ),
                name="campaign_attribution_value_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignattribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("credited", True),
                    models.Q(("attributed_value", 0), ("share", 0)),
                    _connector="OR",
                ),
                name="campaign_attribution_uncredited_zero",
            ),
        ),
    ]
