# Generated by Django 5.2.17 on 2026-10-05 17:45

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_feeds_and_attribution"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignBaseline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "event_id",
                        "customer_ref",
                        "metric_id",
                        "currency_code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="campaigns.campaignevent",
                    ),
                ),
                ("customer_ref", models.TextField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                ("gross", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "baseline",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "incremental",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                ("confidence", models.TextField()),
                (
                    "contaminated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campaigns.campaignevent",
                    ),
                ),
                ("computed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "campaign_baseline",
            },
        ),
        migrations.RemoveConstraint(
            model_name="campaignattribution",
            name="campaign_attribution_rule",
        ),
        migrations.RemoveConstraint(
            model_name="campaigncontact",
            name="campaign_contact_channel_valid",
        ),
        migrations.AddField(
            model_name="campaigncontact",
            name="holdout",
            field=models.BooleanField(db_default=False),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="holdout_pct",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="campaignattribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rule_applied__in",
                        [
                            "single",
                            "holdout",
                            "last_touch",
                            "first_touch",
                            "priority",
                            "split_even",
                        ],
                    )
                ),
                name="campaign_attribution_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigncontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "channel__in",
                            (
                                "sms",
                                "email",
                                "call",
                                "ussd",
                                "branch",
                                "app_push",
                                "whatsapp",
                            ),
                        ),
                        ("holdout", False),
                    ),
                    models.Q(("channel", ""), ("holdout", True)),
                    _connector="OR",
                ),
                name="campaign_contact_channel_fits",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("holdout_pct__isnull", True),
                    models.Q(("holdout_pct__gte", 1), ("holdout_pct__lte", 50)),
                    _connector="OR",
                ),
                name="campaign_event_holdout_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignbaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "confidence__in",
                        ["high", "new_customer", "low_contaminated_baseline"],
                    )
                ),
                name="campaign_baseline_confidence_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignbaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("confidence", "low_contaminated_baseline"), _negated=True),
                    ("incremental__isnull", True),
                    _connector="OR",
                ),
                name="campaign_baseline_contaminated_withheld",
            ),
        ),
    ]
