# Generated by Django 5.2.17 on 2026-10-05 18:16

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_value_and_control"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignWinback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                ("segment_code", models.TextField(null=True)),
                ("product_code", models.TextField(null=True)),
                ("region_code", models.TextField(null=True)),
                ("branch_code", models.TextField(null=True)),
                (
                    "winback_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("customer_ref", models.TextField()),
                ("campaign_code", models.TextField(null=True)),
                ("qualified_at", models.DateField()),
                ("winback_flag", models.BooleanField()),
                ("account_status", models.TextField(null=True)),
                ("retention_confirmed_at", models.DateField(null=True)),
                ("via", models.TextField(null=True)),
                ("rule_applied", models.TextField(null=True)),
                ("candidates", models.SmallIntegerField(db_default=0)),
                ("matched_at", models.DateTimeField(null=True)),
                ("run_id", models.UUIDField()),
                ("loaded_at", models.DateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winbacks",
                        to="campaigns.campaignevent",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_winback",
                "indexes": [
                    models.Index(fields=["org_id", "qualified_at"], name="campaign_winback_day"),
                    models.Index(fields=["event"], name="campaign_winback_event"),
                    models.Index(fields=["run_id"], name="campaign_winback_run"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "customer_ref", "qualified_at"),
                        name="campaign_winback_grain",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("via__isnull", True),
                            ("via__in", ("tag", "contact", "criteria")),
                            _connector="OR",
                        ),
                        name="campaign_winback_via_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("retention_confirmed_at__isnull", True),
                            ("retention_confirmed_at__gte", models.F("qualified_at")),
                            _connector="OR",
                        ),
                        name="campaign_winback_retention_valid",
                    ),
                ],
            },
        ),
    ]
