# Generated by Django 5.2.17 on 2026-10-05 22:08

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_winbacks"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignPublishedMetric",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("created_by", models.BigIntegerField(null=True)),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("updated_by", models.BigIntegerField(null=True)),
                (
                    "published_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("result_kind", models.TextField()),
                ("status", models.TextField(db_default="active")),
                ("withdrawn_at", models.DateTimeField(null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_metrics",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_published_metric",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "result_kind__in",
                                [
                                    "attributed_value",
                                    "incremental_value",
                                    "conversions",
                                    "conversion_rate",
                                    "winbacks_confirmed",
                                ],
                            )
                        ),
                        name="campaign_published_result_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "withdrawn"])),
                        name="campaign_published_status_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("campaign", "result_kind"),
                        name="campaign_published_one_per_result",
                    ),
                ],
            },
        ),
    ]
