"""The shipped starter packs (Starter Packs doc §3–6). Data only — no actuals, no targets.

Each ship of this file is a release artefact; bump a pack's ``version`` when its definitions
change so a client can see which pack version they adopted. ``ratio`` metrics map to the
``score`` unit (a dimensionless number); ``manual`` collection maps to ``manual_input``.
"""

from __future__ import annotations

from kpigo.platform.packs import Pack, PackBand, PackMetric

# The default four-band ramp the RM and Service Officer scorecards adopt (doc §3.3).
_BANKING_BANDS = (
    PackBand("Needs Focus", "0", 1),
    PackBand("Gaining Momentum", "0.75", 2),
    PackBand("On Target", "1.00", 3),
    PackBand("Exemplary", "1.20", 4),
)

RETAIL_RM = Pack(
    key="retail_rm",
    version="1.1",
    title="Retail Banking — Relationship Manager",
    role="Relationship Manager",
    summary="A monthly scorecard for an RM carrying a portfolio, over a four-objective taxonomy.",
    objectives=(
        "Grow the balance sheet",
        "Deepen relationships",
        "Serve reliably",
        "Grow income",
    ),
    metrics=(
        PackMetric(
            "rm_casa_growth",
            "CASA balance growth",
            "higher_is_better",
            "sum",
            "currency",
            ("scorecards",),
            objective="Grow the balance sheet",
            target_scope="subject",
            decimal_places=2,
            weight=20,
            cap=30,
        ),
        PackMetric(
            "rm_ntb_accounts",
            "New-to-bank accounts",
            "higher_is_better",
            "sum",
            "count",
            ("scorecards",),
            objective="Grow the balance sheet",
            target_scope="subject",
            weight=15,
            cap=22,
        ),
        PackMetric(
            "rm_cross_sell",
            "Cross-sell ratio",
            "higher_is_better",
            "average",
            "score",
            ("scorecards",),
            objective="Deepen relationships",
            decimal_places=2,
            weight=15,
            cap=22,
        ),
        PackMetric(
            "rm_digital_act",
            "Digital activation rate",
            "higher_is_better",
            "average",
            "percent",
            ("scorecards",),
            objective="Deepen relationships",
            is_percentage=True,
            decimal_places=1,
            weight=10,
            cap=15,
        ),
        PackMetric(
            "rm_tat_service",
            "Service turnaround time",
            "lower_is_better",
            "average",
            "days",
            ("scorecards",),
            objective="Serve reliably",
            decimal_places=1,
            weight=15,
            cap=22,
        ),
        PackMetric(
            "rm_complaints",
            "Complaints per 1,000 clients",
            "lower_is_better",
            "average",
            "count",
            ("scorecards",),
            objective="Serve reliably",
            weight=10,
            cap=15,
        ),
        PackMetric(
            "rm_fee_income",
            "Fee & commission income",
            "higher_is_better",
            "sum",
            "currency",
            ("scorecards",),
            objective="Grow income",
            target_scope="subject",
            decimal_places=2,
            weight=15,
            cap=22,
        ),
    ),
    bands=_BANKING_BANDS,
    feed_template="tmpl_actual_monthly",
)

RETAIL_SERVICE_OFFICER = Pack(
    key="retail_service_officer",
    version="1.1",
    title="Retail Banking — Service Officer",
    role="Service Officer",
    summary="A daily operational view plus a monthly service scorecard; lower-is-better leads.",
    objectives=("Serve reliably", "Quality and satisfaction"),
    metrics=(
        PackMetric(
            "so_tat",
            "Average handling time",
            "lower_is_better",
            "average",
            "hours",
            ("agent_service",),
            objective="Serve reliably",
            decimal_places=1,
            weight=20,
            cap=30,
        ),
        PackMetric(
            "so_sla_breach",
            "SLA breach rate",
            "lower_is_better",
            "average",
            "percent",
            ("agent_service",),
            objective="Serve reliably",
            is_percentage=True,
            decimal_places=1,
            weight=20,
            cap=30,
        ),
        PackMetric(
            "so_resolution",
            "First-contact resolution",
            "higher_is_better",
            "average",
            "percent",
            ("agent_service",),
            objective="Serve reliably",
            is_percentage=True,
            decimal_places=1,
            weight=15,
            cap=22,
        ),
        PackMetric(
            "so_quality",
            "Quality assurance score",
            "higher_is_better",
            "average",
            "score",
            ("scorecards",),
            objective="Quality and satisfaction",
            decimal_places=1,
            weight=15,
            cap=22,
        ),
        PackMetric(
            "so_complaints",
            "Complaints handled",
            "higher_is_better",
            "sum",
            "count",
            ("agent_service",),
            objective="Serve reliably",
            target_scope="subject",
            weight=10,
            cap=15,
        ),
        PackMetric(
            "so_csat",
            "Customer satisfaction",
            "higher_is_better",
            "average",
            "score",
            ("scorecards",),
            objective="Quality and satisfaction",
            collection="manual_input",
            decimal_places=1,
            weight=20,
            cap=30,
        ),
    ),
    bands=_BANKING_BANDS,
    widgets=("SLA heatmap", "TAT distribution", "queue trend", "leaderboard by resolution"),
    feed_template="tmpl_actual_daily",
)

EXECUTIVE_BANKING = Pack(
    key="executive_banking",
    version="1.1",
    title="Executive — Banking",
    role="CFO / Regional Head",
    summary="Mixed roll-up and independent metrics on a widget dashboard for an executive.",
    metrics=(
        PackMetric(
            "ex_revenue",
            "Total revenue",
            "higher_is_better",
            "sum",
            "currency",
            ("executive",),
            decimal_places=2,
        ),
        PackMetric(
            "ex_cti",
            "Cost-to-income ratio",
            "lower_is_better",
            "average",
            "percent",
            ("executive",),
            is_percentage=True,
            decimal_places=1,
        ),
        PackMetric(
            "ex_casa_growth",
            "CASA growth",
            "higher_is_better",
            "sum",
            "currency",
            ("executive",),
            decimal_places=2,
        ),
        PackMetric(
            "ex_nps",
            "Net promoter score",
            "higher_is_better",
            "average",
            "score",
            ("executive",),
            collection="manual_input",
            decimal_places=1,
        ),
        PackMetric(
            "ex_esg",
            "ESG score",
            "higher_is_better",
            "average",
            "score",
            ("executive",),
            collection="manual_input",
            decimal_places=1,
        ),
        PackMetric(
            "ex_digital_adopt",
            "Digital adoption",
            "higher_is_better",
            "average",
            "percent",
            ("executive",),
            is_percentage=True,
            decimal_places=1,
        ),
        PackMetric(
            "ex_attrition",
            "Customer attrition",
            "lower_is_better",
            "average",
            "percent",
            ("executive",),
            is_percentage=True,
            decimal_places=1,
        ),
        PackMetric(
            "ex_campaign_roi",
            "Campaign effectiveness",
            "higher_is_better",
            "average",
            "score",
            ("executive",),
            decimal_places=2,
        ),
    ),
    widgets=(
        "ex_revenue: KPI card + line",
        "ex_cti: gauge",
        "ex_casa_growth: bar by region",
        "ex_nps: KPI card",
        "ex_esg: gauge",
        "ex_digital_adopt: KPI card",
        "ex_attrition: KPI card + line",
        "ex_campaign_roi: ranked list",
    ),
    feed_template="tmpl_actual_monthly",
)

CAMPAIGN_BANKING = Pack(
    key="campaign_banking",
    version="1.1",
    title="Campaign — Banking",
    role="Campaign Manager",
    summary="Objectives, outcome metrics and attribution defaults for bank campaigns.",
    objectives=("Deposit growth", "Acquisition", "Activation", "Cross-sell", "Attrition win-back"),
    metrics=(
        PackMetric(
            "cmp_deposit_value",
            "Deposit value",
            "higher_is_better",
            "sum",
            "currency",
            ("campaign",),
            objective="Deposit growth",
            decimal_places=2,
        ),
        PackMetric(
            "cmp_ntb_count",
            "New-to-bank count",
            "higher_is_better",
            "sum",
            "count",
            ("campaign",),
            objective="Acquisition",
        ),
        PackMetric(
            "cmp_first_txn",
            "First transactions",
            "higher_is_better",
            "sum",
            "count",
            ("campaign",),
            objective="Activation",
        ),
        PackMetric(
            "cmp_product_takeup",
            "Product take-up",
            "higher_is_better",
            "sum",
            "count",
            ("campaign",),
            objective="Cross-sell",
        ),
        PackMetric(
            "cmp_revenue",
            "Campaign revenue",
            "higher_is_better",
            "sum",
            "currency",
            ("campaign",),
            objective="Cross-sell",
            decimal_places=2,
        ),
        PackMetric(
            "cmp_reactivation",
            "Reactivations",
            "higher_is_better",
            "sum",
            "count",
            ("campaign",),
            objective="Attrition win-back",
        ),
        PackMetric(
            "cmp_winback_value",
            "Win-back value",
            "higher_is_better",
            "sum",
            "currency",
            ("campaign",),
            objective="Attrition win-back",
            decimal_places=2,
        ),
    ),
    campaign_defaults={
        "attribution_rule": "last_touch",
        "value_basis": "incremental",
        "winback_retention_days": 90,
        "attribution_windows": {
            "cmp_deposit_value": 30,
            "cmp_ntb_count": 45,
            "cmp_first_txn": 30,
            "cmp_product_takeup": 60,
            "cmp_revenue": 60,
            "cmp_reactivation": 90,
            "cmp_winback_value": 90,
        },
        "funnel": ["targeted", "reached", "responded", "converted", "actualized"],
    },
    feed_template="tmpl_actual_monthly",
)

ALL_PACKS: dict[str, Pack] = {
    p.key: p for p in (RETAIL_RM, RETAIL_SERVICE_OFFICER, EXECUTIVE_BANKING, CAMPAIGN_BANKING)
}
